SELECT
	CASE IT_IN_STATUS
		WHEN '' THEN 'Ativa'
		WHEN '*' THEN 'Inativa'
	END AS IT_IN_STATUS,
	CASE IT_NU_CGC_CPF
		WHEN '0' THEN NULL
		ELSE RIGHT(REPLICATE('0', 14) + RTRIM(IT_NU_CGC_CPF), 14)
	END AS IT_NU_CGC_CPF,
	IT_CO_UNIDADE_GESTORA,
	RIGHT(REPLICATE('0', 6) + RTRIM(IT_CO_UNIDADE_GESTORA), 6) AS IT_CO_UNIDADE_GESTORA,
	IT_NO_UNIDADE_GESTORA,
	CASE IT_IN_USO_SISG_UASG
		WHEN 'S' THEN 'Sim'
		WHEN 'N' THEN 'Não'
	END AS IT_IN_USO_SISG_UASG,
	CASE IT_IN_ADESAO_SIASG
		WHEN 'S' THEN 'Sim'
		WHEN 'N' THEN 'Não'
	END AS IT_IN_ADESAO_SIASG,
	IT_DA_MOVIMENTO,
	CASE IT_DA_IMPLANTACAO_SIDEC
		WHEN '0' THEN NULL
		ELSE IT_DA_IMPLANTACAO_SIDEC
	END AS IT_DA_IMPLANTACAO_SIDEC,
	IT_SG_UF,
	SG_UF,
	CASE IT_CO_MUNICIPIO
		WHEN '0' THEN NULL
		ELSE IT_CO_MUNICIPIO
	END AS IT_CO_MUNICIPIO,
	NOME_MUN_SIASG,
	NOME_MUN_IBGE,
	CASE IT_CO_UNIDADE_POLO
		WHEN '0' THEN NULL
		ELSE IT_CO_UNIDADE_POLO
	END AS IT_CO_UNIDADE_POLO,
	IT_NO_UNIDADE_GESTORA_POLO,
	CASE IT_CO_UNIDADE_ESPELHO
		WHEN '0' THEN NULL
		ELSE IT_CO_UNIDADE_ESPELHO
	END AS IT_CO_UNIDADE_ESPELHO,
	IT_NO_UNIDADE_GESTORA_ESPELHO,
	CASE IT_IN_UASG_CADASTRADORA
		WHEN 'S' THEN 'Sim'
		WHEN 'N' THEN 'Não'
	END AS IT_IN_UASG_CADASTRADORA,
	IT_IN_STATUS_ORGAO,
	IT_CO_ORGAO,
	IT_NO_ORGAO,
	IT_NO_MNEMONICO,
	CASE IT_NU_CGC_CPF_ORGAO
		WHEN '0' THEN NULL
		ELSE IT_NU_CGC_CPF_ORGAO
	END AS IT_NU_CGC_CPF_ORGAO,
	IT_CO_ORGAO_VINCULADO,
	IT_NO_ORGAO_VINCULADO,
	iT_CO_ORGAO_SUPERIOR,
	IT_NO_ORGAO_SUPERIOR,
	CASE CAST(IT_IN_TIPO_ADMINISTRACAO AS VARCHAR)
		WHEN '1' THEN 'Administração Direta'
		WHEN '2' THEN 'Estatal'
		WHEN '3' THEN 'Autarquia'
		WHEN '4' THEN 'Fundação'
		WHEN '5' THEN 'Empresa Pública Com. e Fin.'
		WHEN '6' THEN 'Economia Mista'
		WHEN '7' THEN 'Fundos'
		WHEN '8' THEN 'Empresa Pública Ind. E agric.'
		WHEN '11' THEN 'Administração Direta Estadual'
		WHEN '12' THEN 'Administração Direta Municipal'
		WHEN '13' THEN 'Administração Indireta Estadual'
		WHEN '14' THEN 'Administração Indireta Municipal'
		WHEN '15' THEN 'Empresa Privada'
		WHEN '' THEN NULL
		ELSE CAST(IT_IN_TIPO_ADMINISTRACAO AS VARCHAR)
	END AS IT_IN_TIPO_ADMINISTRACAO,
	CASE CAST(IT_IN_TIPO_PODER AS VARCHAR)
		WHEN '0' THEN 'Executivo'
		WHEN '1' THEN 'Legislativo'
		WHEN '2' THEN 'Judiciário'
		WHEN '' THEN NULL
		ELSE CAST(IT_IN_TIPO_PODER AS VARCHAR)
	END AS IT_IN_TIPO_PODER,
	CASE IT_IN_ESFERA
		WHEN 'M' THEN 'Municipal'
		WHEN 'E' THEN 'Estadual'
		WHEN 'F' THEN 'Federal'
		WHEN '' THEN NULL
		ELSE IT_IN_ESFERA
	END AS IT_IN_ESFERA
FROM seges_delog_cgscg_stage.dbo.siasg_uasgs_orgaos;