SELECT DISTINCT COUNT(*)
--	l.lanCod,l.ipgCod,l.cliente_id,l.lanData,l.lanValor,l.lanStatus,l.lanDataExclui,l.lanIndExclPreg,l.lanIndExclLances,l.lanClassif,l.lanIndConvocacao,l.lanIndConvocacao7174,l.dataInclusao,l.dataAlteracao, -- l.idLanceSalaDisputa,l.etapaSalaDisputa,l.lanIndConvocacaoDisputaFinal,
--	pri.ippCod,pri.prpCod,pri.ipgCod,pri.ippValor,pri.sppCod,pri.ippMarcaFornec,pri.ippDescrFornec,pri.ippData,pri.ippQtd,pri.ipgMotivoDesclassif,pri.prpSequencial,pri.ippUFFaturaNF,pri.ippFatorEqualizICMS,pri.ippLanceMin,pri.ippLanceMinClassif,pri.ippValorClassif,pri.ippIndAceito,pri.ippIndHabilitado,pri.ippIndAdjudicado,pri.ippValNegAceit,pri.ippValNegAdj,pri.ippObsAceitacao,pri.ippObsAdjudicacao,pri.ippDataUltLance,pri.ippFabricante,pri.ippOrdemConvocacao,pri.ippDataIniConvocacao,pri.ippDataFimConvocacao,pri.ippStatusConvocacao,pri.ippIndPropOriginal,pri.ippIndCadSubcontratada,pri.ippJustificativaSubPreg,pri.ippJustificativaSubFornec,pri.ippIndAnexo,pri.ippOrdemConvocacao7174,pri.ippDataIniConvocacao7174,pri.ippDataFimConvocacao7174,pri.ippStatusConvocacao7174,pri.ippMens5Min7174,pri.ippIndTP,pri.ippIndPPB,pri.contadorDePunicoes,pri.ippDeclaracaoProdNacional,pri.ippCodPaisOrigem,pri.ippIndPossuiPessoasEmComum,pri.ippCadReservaStatus,pri.ippCadReservaDataAceite,pri.ippModeloVersao,pri.dataInclusao,pri.dataAlteracao,pri.convocadoNaDisputaFechada,pri.ippLanceMinFaseFechada,pri.ippLanceMinClassifFaseFechada,pri.ippDataUltLanceFaseFechada,pri.dataFimConvocacaoDisputaFechada,pri.ordemSorteioEletronico,pri.versaoSalaDisputa, -- pri.tipoItem,pri.apelidoItem,pri.ippUnico,pri.ippDataIniConvocacaoDisputaFinal,pri.ippDataFimConvocacaoDisputaFinal,pri.ippStatusConvocacaoDisputaFinal,
--	pr.prpCod,pr.prgCod,pr.Cliente_ID,pr.prpData,pr.prpCNPJ,pr.prpRazaoSocial,pr.prpNomeAnexo,pr.prpNomeAnexoRetif,pr.prpCaminhoAnexoRetif,pr.prpDataRetif,pr.prpPorteEmpresa,pr.prpIndParticiparConvocacao,pr.prpDataParticiparConvocacao,pr.prpDeclaracaoInfantil,pr.prpDeclaracaoSuperveniente,pr.prpDataDeclaracao,pr.prpIndConvocarDeclaracao,pr.prpDeclaracaoPropIndependente,pr.prpDecTrabForcado,pr.prpUnico,pr.dataInclusao,pr.dataAlteracao,pr.prpDecAcessibilidade,pr.prpDeclaracaoCotaAprendizagem,pr.cliente_id_original,
--	pi.ipgIndDecreto7174,pi.ipgUltimoSpgCod,pi.ipgDataUltLanceMin,pi.ipgIndMargemPreferencial,pi.ipgPercMargemPreferencial,pi.ipgPercIntermediario,pi.ipgPercMargemPrefAdicional,pi.ipgCadReservaDataConv,pi.ipgCadReservaStatus,pi.dataInclusao,pi.dataAlteracao,pi.ipgValorIntermediario,pi.qtdePropostasEmpatadas,pi.ipgValorMinFaseFechada,pi.ipgClienteLanceMinFaseFechada,pi.ipgValorMinClassifFaseFechada,pi.ipgDataUltLanceMinFaseFechada,pi.objetoItem,pi.criterioValor,pi.valorSigiloso,pi.versaoSalaDisputa,pi.qtdePropostasEmpatadasFaseFechada,pi.qtdeItensDoGrupo,pi.tipo,pi.dataHoraPrevisaoAbertura,pi.priorizarAbertura,pi.ipgItemCota,pi.faseItem,pi.situacaoItem,pi.apelido,pi.sugestaoApelido,pi.numeroUasg,pi.numeroAnoCompra,pi.dataHoraAlteracaoCompraFaseInterna,pi.ipgNumeroGrupo,pi.codigoModalidade,pi.spgCodSalaDisputa,
--	p.prgCod,p.coduasg,p.numprp,p.prgObjeto,p.prgDescricao,p.prgDataAbertura,p.prgDataInclusao,p.prgPregoeiroCad,p.prgPregoeiroExec,p.prgBat,p.prgTimeBat,p.prgTempoLimite,p.prgStatus,p.prgDataAberturaReal,p.prgDataHom,p.prgCPFHom,p.prgNomePregoeiro,p.prgMembro1,p.prgMembro2,p.prgMembro3,p.prgPortaria,p.prgDataPortaria,p.prgProcesso,p.codPregoeiro,p.codMembro1,p.codMembro2,p.codMembro3,p.prgDataEntregaProp,p.prgDataEncerramento,p.prgDataAbreIntencaoRecurso,p.prgDataFechaIntencaoRecurso,p.prgIndSRP,p.prgDataJulg,p.prgCPFJulg,p.prgNomeHom,p.prgClienteIDChat,p.prgDataLimiteRecurso,p.prgDataLimiteContraRazao,p.prgDataAdjudic,p.prgCPFAdjudic,p.prgDataLimiteDecisao,p.prgNomeJulg,p.prgNomeAdjudic,p.prgDataUltimaVoltaFase,p.prgFaseUltimaVoltaFase,p.prgDataReaberturaSessao,p.prgMotivoUltimaVoltaFase,p.prgRecursoInter,p.prgOrigemRecurso,p.prgPercentualLance,p.prgCodEvento,p.prgIndElet,p.prgIndICMS,p.prgCodTipoSuspensao,p.prgCodAvisoEvento,p.prgDataPublicacaoEvento,p.prgCodEventoAnterior,p.tempoMinimoLance,p.numOcorrenciasLance,p.prgDataConsultaPessoasEmComum,p.dataInclusao,p.dataAlteracao,p.prgModoDisputa,p.retornoServicoRestAbrirSessaoPublica,p.faseSalaDisputa,p.prgSeqSessao,p.prgIndEmergencial,
--	u.coduasg,u.nomuasg,u.titulo01,u.titulo02,u.titulo03,u.titulo04,u.titulo05,u.titulo06,u.titulo07,u.titulo08,u.titulo09,u.titulo10,u.titulo11,u.titulo12,u.uf,u.CodOrgao,u.CodSiorg,u.SiglaUasg,u.NomeOrgao,u.CodMunic,u.Endereco,u.Cep,u.DDD,u.Telefone1,u.Ramal1,u.Telefone2,u.Ramal2,u.Fax,u.IndicadorFornec,u.nomeBrasao,u.bloqueioCertificado,u.coduasgPolo,u.Situacao,u.indSISG,u.adesaoSIASG,
--	o.CodOrgao,o.NomeOrgao,o.Logo,o.TipoAdm,o.Esfera,o.Poder,o.CodOrgaoVinculado,o.cnpj,
--	o2.CodOrgao,o2.NomeOrgao,o2.Logo,o2.TipoAdm,o2.Esfera,o2.Poder,o2.CodOrgaoVinculado,o2.cnpj,
--	''
FROM Stg_Comprasnet.dbo.tbl_Lances l
	JOIN Stg_Comprasnet.dbo.tbl_pregaoitem pi ON pi.ipgCod = l.ipgCod
	JOIN Stg_Comprasnet.dbo.tbl_Pregao p ON p.prgCod = pi.prgCod 
	JOIN Stg_Comprasnet.dbo.tbl_PropostaItem pri ON pri.ipgCod = l.ipgCod
	JOIN Stg_Comprasnet.dbo.tbl_Proposta pr ON (pr.prpCod = pri.prpCod AND pr.Cliente_ID = l.cliente_id)
	JOIN Stg_Comprasnet.dbo.tb_uasg u ON p.coduasg = u.coduasg
	JOIN Stg_Comprasnet.dbo.tb_orgao o ON o.CodOrgao = u.CodOrgao
	LEFT JOIN Stg_Comprasnet.dbo.tb_orgao o2 ON o2.CodOrgao= o.CodOrgaoVinculado
WHERE 1=1
--	AND l.lanData BETWEEN '2015-01-01 00:00:00' AND '2015-02-01 00:00:00' 
	AND (o2.CodOrgao IN (95430) OR p.coduasg IN (986001))
	AND l.lanData BETWEEN '2010-01-01 00:00:00' AND '2018-01-01 00:00:00' 
--	AND p.coduasg IN (986001)
--	AND lanCod = 337231120
;
UNION
SELECT DISTINCT COUNT(*)
--	l.lanCod,l.ipgCod,l.cliente_id,l.lanData,l.lanValor,l.lanStatus,'' AS lanDataExclui, '' AS lanIndExclPreg, '' AS lanIndExclLances,l.lanClassif,l.lanIndConvocacao,l.lanIndConvocacao7174,l.dataInclusao,l.dataAlteracao,l.idLanceSalaDisputa,l.etapaSalaDisputa,l.lanIndConvocacaoDisputaFinal,
--	pri.ippCod,pri.prpCod,pri.ipgCod,pri.ippValor,pri.sppCod,pri.ippMarcaFornec,pri.ippDescrFornec,pri.ippData,pri.ippQtd,pri.ipgMotivoDesclassif,pri.prpSequencial,pri.ippUFFaturaNF,pri.ippFatorEqualizICMS,pri.ippLanceMin,pri.ippLanceMinClassif,pri.ippValorClassif,pri.ippIndAceito,pri.ippIndHabilitado,pri.ippIndAdjudicado,pri.ippValNegAceit,pri.ippValNegAdj,pri.ippObsAceitacao,pri.ippObsAdjudicacao,pri.ippDataUltLance,pri.ippFabricante,pri.ippOrdemConvocacao,pri.ippDataIniConvocacao,pri.ippDataFimConvocacao,pri.ippStatusConvocacao,pri.ippIndPropOriginal,pri.ippIndCadSubcontratada,pri.ippJustificativaSubPreg,pri.ippJustificativaSubFornec,pri.ippIndAnexo,pri.ippOrdemConvocacao7174,pri.ippDataIniConvocacao7174,pri.ippDataFimConvocacao7174,pri.ippStatusConvocacao7174,pri.ippMens5Min7174,pri.ippIndTP,pri.ippIndPPB,pri.contadorDePunicoes,pri.ippDeclaracaoProdNacional,pri.ippCodPaisOrigem,pri.ippIndPossuiPessoasEmComum,pri.ippCadReservaStatus,pri.ippCadReservaDataAceite,pri.ippModeloVersao,pri.dataInclusao,pri.dataAlteracao,pri.convocadoNaDisputaFechada,pri.ippLanceMinFaseFechada,pri.ippLanceMinClassifFaseFechada,pri.ippDataUltLanceFaseFechada,pri.dataFimConvocacaoDisputaFechada,pri.ordemSorteioEletronico,pri.versaoSalaDisputa,pri.tipoItem,pri.apelidoItem,pri.ippUnico,pri.ippDataIniConvocacaoDisputaFinal,pri.ippDataFimConvocacaoDisputaFinal,pri.ippStatusConvocacaoDisputaFinal,
--	pr.prpCod,pr.prgCod,pr.Cliente_ID,pr.prpNomeAnexo,pr.prpCaminhoAnexo,pr.prpData,pr.prpCNPJ,pr.prpRazaoSocial,pr.prpNomeAnexoRetif,pr.prpCaminhoAnexoRetif,pr.prpDataRetif,pr.prpPorteEmpresa,pr.prpIndParticiparConvocacao,pr.prpDataParticiparConvocacao,pr.prpDeclaracaoInfantil,pr.prpDeclaracaoSuperveniente,pr.prpDataDeclaracao,pr.prpIndConvocarDeclaracao,pr.prpDeclaracaoPropIndependente,pr.prpDecTrabForcado,pr.prpUnico,pr.dataInclusao,pr.dataAlteracao,pr.prpDecAcessibilidade,pr.prpDeclaracaoCotaAprendizagem,pr.cliente_id_original,
--	pi.ipgIndDecreto7174,pi.ipgUltimoSpgCod,pi.ipgDataUltLanceMin,pi.ipgIndMargemPreferencial,pi.ipgPercMargemPreferencial,pi.ipgPercIntermediario,pi.ipgPercMargemPrefAdicional,pi.ipgCadReservaDataConv,pi.ipgCadReservaStatus,pi.dataInclusao,pi.dataAlteracao,pi.ipgValorIntermediario,pi.qtdePropostasEmpatadas,pi.ipgValorMinFaseFechada,pi.ipgClienteLanceMinFaseFechada,pi.ipgValorMinClassifFaseFechada,pi.ipgDataUltLanceMinFaseFechada,pi.objetoItem,pi.criterioValor,pi.valorSigiloso,pi.versaoSalaDisputa,pi.qtdePropostasEmpatadasFaseFechada,pi.qtdeItensDoGrupo,pi.tipo,pi.dataHoraPrevisaoAbertura,pi.priorizarAbertura,pi.ipgItemCota,pi.faseItem,pi.situacaoItem,pi.apelido,pi.sugestaoApelido,pi.numeroUasg,pi.numeroAnoCompra,pi.dataHoraAlteracaoCompraFaseInterna,pi.ipgNumeroGrupo,pi.codigoModalidade,pi.spgCodSalaDisputa,
--	p.prgCod,p.coduasg,p.numprp,p.prgObjeto,p.prgDescricao,p.prgDataAbertura,p.prgDataInclusao,p.prgPregoeiroCad,p.prgPregoeiroExec,p.prgBat,p.prgTimeBat,p.prgTempoLimite,p.prgStatus,p.prgDataAberturaReal,p.prgDataHom,p.prgCPFHom,p.prgNomePregoeiro,p.prgMembro1,p.prgMembro2,p.prgMembro3,p.prgPortaria,p.prgDataPortaria,p.prgProcesso,p.codPregoeiro,p.codMembro1,p.codMembro2,p.codMembro3,p.prgDataEntregaProp,p.prgDataEncerramento,p.prgDataAbreIntencaoRecurso,p.prgDataFechaIntencaoRecurso,p.prgIndSRP,p.prgDataJulg,p.prgCPFJulg,p.prgNomeHom,p.prgClienteIDChat,p.prgDataLimiteRecurso,p.prgDataLimiteContraRazao,p.prgDataAdjudic,p.prgCPFAdjudic,p.prgDataLimiteDecisao,p.prgNomeJulg,p.prgNomeAdjudic,p.prgDataUltimaVoltaFase,p.prgFaseUltimaVoltaFase,p.prgDataReaberturaSessao,p.prgMotivoUltimaVoltaFase,p.prgRecursoInter,p.prgOrigemRecurso,p.prgPercentualLance,p.prgCodEvento,p.prgIndElet,p.prgIndICMS,p.prgCodTipoSuspensao,p.prgCodAvisoEvento,p.prgDataPublicacaoEvento,p.prgCodEventoAnterior,p.tempoMinimoLance,p.numOcorrenciasLance,p.prgDataConsultaPessoasEmComum,p.dataInclusao,p.dataAlteracao,p.prgModoDisputa,p.retornoServicoRestAbrirSessaoPublica,p.faseSalaDisputa,p.prgSeqSessao,p.prgIndEmergencial,
--	u.coduasg,u.nomuasg,u.titulo01,u.titulo02,u.titulo03,u.titulo04,u.titulo05,u.titulo06,u.titulo07,u.titulo08,u.titulo09,u.titulo10,u.titulo11,u.titulo12,u.uf,u.CodOrgao,u.CodSiorg,u.SiglaUasg,u.NomeOrgao,u.CodMunic,u.Endereco,u.Cep,u.DDD,u.Telefone1,u.Ramal1,u.Telefone2,u.Ramal2,u.Fax,u.IndicadorFornec,u.nomeBrasao,u.bloqueioCertificado,u.coduasgPolo,u.Situacao,u.indSISG,u.adesaoSIASG,
--	o.CodOrgao,o.NomeOrgao,o.Logo,o.TipoAdm,o.Esfera,o.Poder,o.CodOrgaoVinculado,o.cnpj,
--	o2.CodOrgao,o2.NomeOrgao,o2.Logo,o2.TipoAdm,o2.Esfera,o2.Poder,o2.CodOrgaoVinculado,o2.cnpj,
--	o3.CodOrgao,o3.NomeOrgao,o3.Logo,o3.TipoAdm,o3.Esfera,o3.Poder,o3.CodOrgaoVinculado,o3.cnpj,
--	o4.CodOrgao,o4.NomeOrgao,o4.Logo,o4.TipoAdm,o4.Esfera,o4.Poder,o4.CodOrgaoVinculado,o4.cnpj,
--	o5.CodOrgao,o5.NomeOrgao,o5.Logo,o5.TipoAdm,o5.Esfera,o5.Poder,o5.CodOrgaoVinculado,o5.cnpj,
--	''
FROM Stg_Comprasnet.dbo.tbl_Lances_Encerrados l
	JOIN Stg_Comprasnet.dbo.tbl_pregaoitem pi ON pi.ipgCod = l.ipgCod
	JOIN Stg_Comprasnet.dbo.tbl_Pregao p ON p.prgCod = pi.prgCod 
	JOIN Stg_Comprasnet.dbo.tbl_PropostaItem pri ON pri.ipgCod = l.ipgCod
	JOIN Stg_Comprasnet.dbo.tbl_Proposta pr ON (pr.prpCod = pri.prpCod AND pr.Cliente_ID = l.cliente_id)
	JOIN Stg_Comprasnet.dbo.tb_uasg u ON p.coduasg = u.coduasg
	JOIN Stg_Comprasnet.dbo.tb_orgao o ON o.CodOrgao = u.CodOrgao
	LEFT JOIN Stg_Comprasnet.dbo.tb_orgao o2 ON o2.CodOrgao= o.CodOrgaoVinculado
	LEFT JOIN Stg_Comprasnet.dbo.tb_orgao o3 ON o3.CodOrgao= o2.CodOrgaoVinculado
WHERE 1=1
--	AND l.lanData BETWEEN '2015-01-01 00:00:00' AND '2015-02-01 00:00:00' 
	AND (o2.CodOrgao IN (95430) OR p.coduasg IN (986001))
	AND l.lanData BETWEEN '2010-01-01 00:00:00' AND '2018-01-01 00:00:00' 
--	AND p.coduasg IN (986001)
--	AND lanCod = 337231120
;