-- Órgãos Ativos
select	distinct
	a12.ID_UNDD_SIT_ATUAL_UNIDADE  ID_UNDD_SIT_ATUAL_UNIDADE,
	a16.DS_UNDD_SIT_ATUAL_UNIDADE  DS_UNDD_SIT_ATUAL_UNIDADE,
	a12.ID_UNDD_ORGAO  ID_UNDD_ORGAO,
	a17.DS_UNDD_ORGAO  DS_UNDD_ORGAO,
	a11.ID_UNDD_ESFERA  ID_UNDD_ESFERA,
	a11.DS_UNDD_ESFERA  DS_UNDD_ESFERA,
	a12.ID_UNDD_PODER  ID_UNDD_PODER,
	a15.DS_UNDD_PODER  DS_UNDD_PODER,
	a13.ID_LCAL_REGIAO  ID_LCAL_REGIAO,
	a18.DS_LCAL_REGIAO  DS_LCAL_REGIAO,
	a12.ID_LCAL_UF_UNIDADE  ID_LCAL_UF,
	a13.DS_LCAL_UF  DS_LCAL_UF,
	a12.ID_LCAL_MUNICIPIO_UNIDADE  ID_LCAL_MUNICIPIO,
	a14.DS_LCAL_MUNICIPIO  DS_LCAL_MUNICIPIO
from	Siasg_DW_VBL.D_UNDD_ESFERA	a11
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a12
	  on 	(a11.ID_UNDD_ESFERA = a12.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_LCAL_UF	a13
	  on 	(a12.ID_LCAL_UF_UNIDADE = a13.ID_LCAL_UF)
	join	Siasg_DW_VBL.D_LCAL_MUNICIPIO	a14
	  on 	(a12.ID_LCAL_MUNICIPIO_UNIDADE = a14.ID_LCAL_MUNICIPIO)
	join	Siasg_DW_VBL.D_UNDD_PODER	a15
	  on 	(a12.ID_UNDD_PODER = a15.ID_UNDD_PODER)
	join	Siasg_DW_VBL.D_UNDD_SIT_ATUAL_UNIDADE	a16
	  on 	(a12.ID_UNDD_SIT_ATUAL_UNIDADE = a16.ID_UNDD_SIT_ATUAL_UNIDADE)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a17
	  on 	(a12.ID_UNDD_ORGAO = a17.ID_UNDD_ORGAO)
	join	Siasg_DW_VBL.D_LCAL_REGIAO	a18
	  on 	(a13.ID_LCAL_REGIAO = a18.ID_LCAL_REGIAO)
where	a12.ID_UNDD_SIT_ATUAL_UNIDADE in (1)
;

-- Órgãos Ativos com Compras (Com Municípios)
with temp  as (
select	
--	a13.ID_DT_ANO  ID_DT_ANO,
	a14.ID_UNDD_ESFERA  ID_UNDD_ESFERA,
	a14.ID_LCAL_MUNICIPIO_UNIDADE  ID_LCAL_MUNICIPIO,
	a14.ID_UNDD_PODER  ID_UNDD_PODER,
	a14.ID_UNDD_ORGAO  ID_UNDD_ORGAO
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
--	join	Siasg_DW_VBL.D_DT_DATA	a13
--	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
	  on 	(a12.ID_UNDD_RESP_COMPRA = a14.ID_UNDD_UNIDADE)
where	(a14.ID_UNDD_ORGAO > 0
 and a14.ID_UNDD_SIT_ATUAL_UNIDADE in (1))
group by	
--	a13.ID_DT_ANO,
	a14.ID_UNDD_ESFERA,
	a14.ID_LCAL_MUNICIPIO_UNIDADE,
	a14.ID_UNDD_PODER,
	a14.ID_UNDD_ORGAO
having	sum(a11.VL_PRECO_TOTAL_HOMOLOG) > 0 
)
select	distinct pa11.ID_UNDD_ORGAO  ID_UNDD_ORGAO,
	a18.DS_UNDD_ORGAO  DS_UNDD_ORGAO,
	pa11.ID_UNDD_ESFERA  ID_UNDD_ESFERA,
	a15.DS_UNDD_ESFERA  DS_UNDD_ESFERA,
	pa11.ID_UNDD_PODER  ID_UNDD_PODER,
	a17.DS_UNDD_PODER  DS_UNDD_PODER,
--	a13.ID_LCAL_REGIAO  ID_LCAL_REGIAO,
	a19.DS_LCAL_REGIAO  DS_LCAL_REGIAO,
	a12.ID_LCAL_UF_UNIDADE  ID_LCAL_UF,
--	a13.DS_LCAL_UF  DS_LCAL_UF,
	pa11.ID_LCAL_MUNICIPIO  ID_LCAL_MUNICIPIO,
	a16.DS_LCAL_MUNICIPIO  DS_LCAL_MUNICIPIO
--	pa11.ID_DT_ANO  ID_DT_ANO,
--	a14.DS_DT_ANO  DS_DT_ANO
from	temp	pa11
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a12
	  on 	(pa11.ID_UNDD_ESFERA = a12.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_LCAL_UF	a13
	  on 	(a12.ID_LCAL_UF_UNIDADE = a13.ID_LCAL_UF)
--	join	Siasg_DW_VBL.D_DT_ANO	a14
--	  on 	(pa11.ID_DT_ANO = a14.ID_DT_ANO)
	join	Siasg_DW_VBL.D_UNDD_ESFERA	a15
	  on 	(pa11.ID_UNDD_ESFERA = a15.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_LCAL_MUNICIPIO	a16
	  on 	(pa11.ID_LCAL_MUNICIPIO = a16.ID_LCAL_MUNICIPIO)
	join	Siasg_DW_VBL.D_UNDD_PODER	a17
	  on 	(pa11.ID_UNDD_PODER = a17.ID_UNDD_PODER)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a18
	  on 	(pa11.ID_UNDD_ORGAO = a18.ID_UNDD_ORGAO)
	join	Siasg_DW_VBL.D_LCAL_REGIAO	a19
	  on 	(a13.ID_LCAL_REGIAO = a19.ID_LCAL_REGIAO)
where	(pa11.ID_UNDD_ORGAO > 0
 and a12.ID_UNDD_SIT_ATUAL_UNIDADE in (1))
;

-- Órgãos Ativos com Compras (Sem Municípios)
with temp  as (
select
	a13.ID_DT_ANO  ID_DT_ANO,
	a14.ID_UNDD_ESFERA  ID_UNDD_ESFERA,
	a14.ID_UNDD_PODER  ID_UNDD_PODER,
	a14.ID_LCAL_UF_UNIDADE  ID_LCAL_UF,
	a14.ID_UNDD_ORGAO  ID_UNDD_ORGAO
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
	  on 	(a12.ID_UNDD_RESP_COMPRA = a14.ID_UNDD_UNIDADE)
where	(a14.ID_UNDD_ORGAO > 0
 and a14.ID_UNDD_SIT_ATUAL_UNIDADE in (1))
group by	a13.ID_DT_ANO,
	a14.ID_UNDD_ESFERA,
	a14.ID_UNDD_PODER,
	a14.ID_LCAL_UF_UNIDADE,
	a14.ID_UNDD_ORGAO
having	sum(a11.VL_PRECO_TOTAL_HOMOLOG) > 0 
)
select	distinct
	pa11.ID_UNDD_ORGAO  ID_UNDD_ORGAO,
	a17.DS_UNDD_ORGAO  DS_UNDD_ORGAO,
	pa11.ID_UNDD_ESFERA  ID_UNDD_ESFERA,
	a15.DS_UNDD_ESFERA  DS_UNDD_ESFERA,
	pa11.ID_UNDD_PODER  ID_UNDD_PODER,
	a16.DS_UNDD_PODER  DS_UNDD_PODER,
	a13.ID_LCAL_REGIAO  ID_LCAL_REGIAO,
	a18.DS_LCAL_REGIAO  DS_LCAL_REGIAO,
	pa11.ID_LCAL_UF  ID_LCAL_UF,
	a13.DS_LCAL_UF  DS_LCAL_UF
--	pa11.ID_DT_ANO  ID_DT_ANO,
--	a14.DS_DT_ANO  DS_DT_ANO
from	temp	pa11
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a12
	  on 	(pa11.ID_UNDD_ESFERA = a12.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_LCAL_UF	a13
	  on 	(pa11.ID_LCAL_UF = a13.ID_LCAL_UF)
--	join	Siasg_DW_VBL.D_DT_ANO	a14
--	  on 	(pa11.ID_DT_ANO = a14.ID_DT_ANO)
	join	Siasg_DW_VBL.D_UNDD_ESFERA	a15
	  on 	(pa11.ID_UNDD_ESFERA = a15.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_UNDD_PODER	a16
	  on 	(pa11.ID_UNDD_PODER = a16.ID_UNDD_PODER)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a17
	  on 	(pa11.ID_UNDD_ORGAO = a17.ID_UNDD_ORGAO)
	join	Siasg_DW_VBL.D_LCAL_REGIAO	a18
	  on 	(a13.ID_LCAL_REGIAO = a18.ID_LCAL_REGIAO)
where	(pa11.ID_UNDD_ORGAO > 0
 and a12.ID_UNDD_SIT_ATUAL_UNIDADE in (1))
;

-- Órgãos Ativos com Compras (Estados e Municípios)
with temp as (
select	a13.ID_DT_ANO  ID_DT_ANO,
	a14.ID_UNDD_ESFERA  ID_UNDD_ESFERA,
	a14.ID_UNDD_PODER  ID_UNDD_PODER,
	a14.ID_LCAL_UF_UNIDADE  ID_LCAL_UF,
	a14.ID_UNDD_ORGAO  ID_UNDD_ORGAO
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
	  on 	(a12.ID_UNDD_RESP_COMPRA = a14.ID_UNDD_UNIDADE)
where	(a14.ID_UNDD_ORGAO > 0
 and a14.ID_UNDD_SIT_ATUAL_UNIDADE in (1)
 and a14.ID_UNDD_ESFERA in (1, 2))
group by	a13.ID_DT_ANO,
	a14.ID_UNDD_ESFERA,
	a14.ID_UNDD_PODER,
	a14.ID_LCAL_UF_UNIDADE,
	a14.ID_UNDD_ORGAO
having	sum(a11.VL_PRECO_TOTAL_HOMOLOG) > 0 
)
select	distinct pa11.ID_UNDD_ORGAO  ID_UNDD_ORGAO,
	a17.DS_UNDD_ORGAO  DS_UNDD_ORGAO,
	pa11.ID_UNDD_ESFERA  ID_UNDD_ESFERA,
	a15.DS_UNDD_ESFERA  DS_UNDD_ESFERA,
	pa11.ID_UNDD_PODER  ID_UNDD_PODER,
	a16.DS_UNDD_PODER  DS_UNDD_PODER,
	a13.ID_LCAL_REGIAO  ID_LCAL_REGIAO,
	a18.DS_LCAL_REGIAO  DS_LCAL_REGIAO,
	pa11.ID_LCAL_UF  ID_LCAL_UF
--	a13.DS_LCAL_UF  DS_LCAL_UF,
--	pa11.ID_DT_ANO  ID_DT_ANO,
--	a14.DS_DT_ANO  DS_DT_ANO
from	temp	pa11
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a12
	  on 	(pa11.ID_UNDD_ESFERA = a12.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_LCAL_UF	a13
	  on 	(pa11.ID_LCAL_UF = a13.ID_LCAL_UF)
--	join	Siasg_DW_VBL.D_DT_ANO	a14
--	  on 	(pa11.ID_DT_ANO = a14.ID_DT_ANO)
	join	Siasg_DW_VBL.D_UNDD_ESFERA	a15
	  on 	(pa11.ID_UNDD_ESFERA = a15.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_UNDD_PODER	a16
	  on 	(pa11.ID_UNDD_PODER = a16.ID_UNDD_PODER)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a17
	  on 	(pa11.ID_UNDD_ORGAO = a17.ID_UNDD_ORGAO)
	join	Siasg_DW_VBL.D_LCAL_REGIAO	a18
	  on 	(a13.ID_LCAL_REGIAO = a18.ID_LCAL_REGIAO)
where	(pa11.ID_UNDD_ORGAO > 0
 and a12.ID_UNDD_SIT_ATUAL_UNIDADE in (1)
 and pa11.ID_UNDD_ESFERA in (1, 2))
;