WITH temp1 AS (
	SELECT
		a11.ID_FRND_FORNECEDOR_COMPRA  		AS ID_FRND_FORNECEDOR,
		a12.ID_CMPR_COMPRA  				AS DS_CMPR_COMPRA_EDIT,
		a11.ID_ITCP_ITEM_COMPRA  			AS ID_ITCP_ITEM_COMPRA
	FROM    Siasg_DW_VBL.F_ITEM_FORNECEDOR				a11
		JOIN    Siasg_DW_VBL.D_CMPR_COMPRA				a12
		ON     (a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
		JOIN    Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a13
		ON     (a12.ID_CMPR_MODALIDADE_COMPRA = a13.ID_CMPR_MODALIDADE_COMPRA)
		JOIN    Siasg_DW_VBL.D_DT_DATA					a14
		ON     (a12.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
	WHERE    (a13.ID_CMPR_MODALIDADE_GRUPO in (6)
		AND a12.ID_CMPR_IN_COTACAO_ELETR in (1)
		AND a14.ID_DT_ANO IN ('2022'))
	GROUP BY
		a11.ID_FRND_FORNECEDOR_COMPRA,
		a12.ID_CMPR_COMPRA,
		a11.ID_ITCP_ITEM_COMPRA
	HAVING SUM(a11.VL_ULT_LANCE) >=  0.0 
)
, temp3 AS (
SELECT
	a15.ID_DT_MES											AS ID_DT_MES,
	CAST(COUNT(DISTINCT a11.ID_FRND_FORNECEDOR) AS FLOAT)	AS CONTA_ID_FRND_FORNECEDOR
FROM    Siasg_DW_VBL.D_FRND_FORNECEDOR				a11
	JOIN    temp1									pa12
	ON     (a11.ID_FRND_FORNECEDOR = pa12.ID_FRND_FORNECEDOR)
	JOIN    Siasg_DW_VBL.D_CMPR_COMPRA				a13
	ON     (pa12.DS_CMPR_COMPRA_EDIT = a13.ID_CMPR_COMPRA)
	JOIN    Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a14
	ON     (a13.ID_CMPR_MODALIDADE_COMPRA = a14.ID_CMPR_MODALIDADE_COMPRA)
	JOIN    Siasg_DW_VBL.D_DT_DATA					a15
	ON     (a13.DT_CMPR_RESULTADO_COMPRA = a15.ID_DT_DATA)
WHERE    (a14.ID_CMPR_MODALIDADE_GRUPO in (6)
	AND a13.ID_CMPR_IN_COTACAO_ELETR in (1)
	AND a15.ID_DT_ANO IN ('2022'))
GROUP BY
	a15.ID_DT_MES
)
SELECT ID_DT_MES as anomes, SUM(CONTA_ID_FRND_FORNECEDOR) AS contapropostasunicascotacoesdispensas, NOW() AS datahoraregisto
FROM temp3
GROUP BY ID_DT_MES
ORDER BY ID_DT_MES