with ZZT1O6OVJITMQ000  as (
	select	a13.ID_DT_ANO  ID_DT_ANO,
		a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
		a12.ID_CMPR_MODALIDADE_COMPRA  ID_CMPR_MODALIDADE_COMPRA,
		a12.ID_UNDD_RESP_COMPRA  CD_UNDD_UNIDADE,
		a14.ID_UNDD_PODER  ID_UNDD_PODER
	from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
		join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
		  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
		join	Siasg_DW_VBL.D_DT_DATA	a13
		  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
		join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
		  on 	(a12.ID_UNDD_RESP_COMPRA = a14.ID_UNDD_UNIDADE)
		join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a15
		  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a15.ID_ITCP_TP_COD_MAT_SERV)
	where	(a13.ID_DT_ANO in (2020, 2021, 2022)
	 and a15.ID_ITCP_TP_MATERIAL_SERVICO in (1)
	 and a12.ID_UNDD_RESP_COMPRA in (130024))
	group by	
		a13.ID_DT_ANO,
		a11.ID_ITCP_TP_COD_MAT_SERV,
		a12.ID_CMPR_MODALIDADE_COMPRA,
		a12.ID_UNDD_RESP_COMPRA,
		a14.ID_UNDD_PODER
	having	sum(a11.VL_PRECO_TOTAL_HOMOLOG) > 0 
),
ZZTWS1SZXH7SP001 as (
	select	a14.ID_UNDD_PODER  ID_UNDD_PODER,
		a12.ID_UNDD_RESP_COMPRA  CD_UNDD_UNIDADE,
		a12.ID_CMPR_MODALIDADE_COMPRA  ID_CMPR_MODALIDADE_COMPRA,
		a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
		a13.ID_DT_ANO  ID_DT_ANO,
		sum(a11.QT_ITCP_ITEM_COMPRAS)  WJXBFS1
	from	Siasg_DW_VBL.F_ITEM_COMPRA	a11
		join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
		  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
		join	Siasg_DW_VBL.D_DT_DATA	a13
		  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
		join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
		  on 	(a12.ID_UNDD_RESP_COMPRA = a14.ID_UNDD_UNIDADE)
		join	ZZT1O6OVJITMQ000	pa15
		  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = pa15.ID_ITCP_TP_COD_MAT_SERV and 
		a12.ID_CMPR_MODALIDADE_COMPRA = pa15.ID_CMPR_MODALIDADE_COMPRA and 
		a12.ID_UNDD_RESP_COMPRA = pa15.CD_UNDD_UNIDADE and 
		a13.ID_DT_ANO = pa15.ID_DT_ANO and 
		a14.ID_UNDD_PODER = pa15.ID_UNDD_PODER)
		join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a16
		  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a16.ID_ITCP_TP_COD_MAT_SERV)
	where	(a13.ID_DT_ANO in (2020, 2021, 2022)
	 and a16.ID_ITCP_TP_MATERIAL_SERVICO in (1)
	 and a12.ID_UNDD_RESP_COMPRA in (130024))
	group by	
		a14.ID_UNDD_PODER,
		a12.ID_UNDD_RESP_COMPRA,
		a12.ID_CMPR_MODALIDADE_COMPRA,
		a11.ID_ITCP_TP_COD_MAT_SERV,
		a13.ID_DT_ANO 
),
ZZT5O28VWR9SP002 as (
	select	a14.ID_UNDD_PODER  ID_UNDD_PODER,
		a12.ID_UNDD_RESP_COMPRA  CD_UNDD_UNIDADE,
		a12.ID_CMPR_MODALIDADE_COMPRA  ID_CMPR_MODALIDADE_COMPRA,
		a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
		a13.ID_DT_ANO  ID_DT_ANO,
		sum(a11.VL_PRECO_TOTAL_HOMOLOG)  WJXBFS1,
		sum(a11.VL_PRECO_UNIT_HOMOLOG)  WJXBFS2
	from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
		join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
		  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
		join	Siasg_DW_VBL.D_DT_DATA	a13
		  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
		join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
		  on 	(a12.ID_UNDD_RESP_COMPRA = a14.ID_UNDD_UNIDADE)
		join	ZZT1O6OVJITMQ000	pa15
		  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = pa15.ID_ITCP_TP_COD_MAT_SERV and 
		a12.ID_CMPR_MODALIDADE_COMPRA = pa15.ID_CMPR_MODALIDADE_COMPRA and 
		a12.ID_UNDD_RESP_COMPRA = pa15.CD_UNDD_UNIDADE and 
		a13.ID_DT_ANO = pa15.ID_DT_ANO and 
		a14.ID_UNDD_PODER = pa15.ID_UNDD_PODER)
		join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a16
		  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a16.ID_ITCP_TP_COD_MAT_SERV)
	where	(a13.ID_DT_ANO in (2020, 2021, 2022)
	 and a16.ID_ITCP_TP_MATERIAL_SERVICO in (1)
	 and a12.ID_UNDD_RESP_COMPRA in (130024))
	group by	
		a14.ID_UNDD_PODER,
		a12.ID_UNDD_RESP_COMPRA,
		a12.ID_CMPR_MODALIDADE_COMPRA,
		a11.ID_ITCP_TP_COD_MAT_SERV,
		a13.ID_DT_ANO 
)
select	distinct 
	pa11.ID_CMPR_MODALIDADE_COMPRA  	ID_CMPR_MODALIDADE_COMPRA,
	a18.DS_CMPR_MODALIDADE_COMPRA  		DS_CMPR_MODALIDADE_COMPRA,
	pa11.ID_DT_ANO  					ID_DT_ANO,
	a16.DS_DT_ANO 						DS_DT_ANO,
	a15.ID_UNDD_ORGAO_SUP  				ID_UNDD_ORGAO_SUP,
	a112.DS_UNDD_ORGAO_SUP  			DS_UNDD_ORGAO_SUP,
	a13.ID_UNDD_ORGAO  					ID_UNDD_ORGAO,
	a14.DS_UNDD_ORGAO  					DS_UNDD_ORGAO,
	a13.ID_UNDD_ESFERA  				ID_UNDD_ESFERA,
	a110.DS_UNDD_ESFERA  				DS_UNDD_ESFERA,
	pa11.ID_UNDD_PODER  				ID_UNDD_PODER,
	a19.DS_UNDD_PODER  					DS_UNDD_PODER,
	a13.ID_UNDD_IN_SISG  				ID_UNDD_IN_SISG,
	a111.DS_UNDD_IN_SISG  				DS_UNDD_IN_SISG,
	pa11.CD_UNDD_UNIDADE  				CD_UNDD_UNIDADE,
	a13.NO_UNDD_UNIDADE  				NO_UNDD_UNIDADE,
	pa11.ID_ITCP_TP_COD_MAT_SERV  		ID_ITCP_TP_COD_MAT_SERV,
	a17.DS_ITCP_MATERIAL_SERVICO  		DS_ITCP_MATERIAL_SERVICO,
	a17.ID_ITCP_MATERIAL_SERVICO  		ID_ITCP_MATERIAL_SERVICO,
	pa11.WJXBFS1  						QtdeItemCompra, 			-- WJXBFS1,
	pa12.WJXBFS1  						ValorUnitarioHomologado, 	-- WJXBFS2,
	pa12.WJXBFS2  						ValorTotalHomologado 		-- WJXBFS3
from	ZZTWS1SZXH7SP001	pa11
	join	ZZT5O28VWR9SP002	pa12
	  on 	(pa11.CD_UNDD_UNIDADE = pa12.CD_UNDD_UNIDADE and 
			pa11.ID_CMPR_MODALIDADE_COMPRA = pa12.ID_CMPR_MODALIDADE_COMPRA and 
			pa11.ID_DT_ANO = pa12.ID_DT_ANO and 
			pa11.ID_ITCP_TP_COD_MAT_SERV = pa12.ID_ITCP_TP_COD_MAT_SERV and 
			pa11.ID_UNDD_PODER = pa12.ID_UNDD_PODER)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a13
	  on 	(pa11.CD_UNDD_UNIDADE = a13.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a14
	  on 	(a13.ID_UNDD_ORGAO = a14.ID_UNDD_ORGAO)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_VINC	a15
	  on 	(a14.ID_UNDD_ORGAO_VINC = a15.ID_UNDD_ORGAO_VINC)
	join	Siasg_DW_VBL.D_DT_ANO	a16
	  on 	(pa11.ID_DT_ANO = a16.ID_DT_ANO)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a17
	  on 	(pa11.ID_ITCP_TP_COD_MAT_SERV = a17.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a18
	  on 	(pa11.ID_CMPR_MODALIDADE_COMPRA = a18.ID_CMPR_MODALIDADE_COMPRA)
	join	Siasg_DW_VBL.D_UNDD_PODER	a19
	  on 	(pa11.ID_UNDD_PODER = a19.ID_UNDD_PODER)
	join	Siasg_DW_VBL.D_UNDD_ESFERA	a110
	  on 	(a13.ID_UNDD_ESFERA = a110.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_UNDD_IN_SISG	a111
	  on 	(a13.ID_UNDD_IN_SISG = a111.ID_UNDD_IN_SISG)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_SUP	a112
	  on 	(a15.ID_UNDD_ORGAO_SUP = a112.ID_UNDD_ORGAO_SUP)
	
--		select
--		[Ano Resultado Compra]@[ID_DT_ANO],
--		[Ano Resultado Compra]@[DS_DT_ANO],
--		[Codigo Material Serviço]@[ID_ITCP_TP_COD_MAT_SERV],
--		[Codigo Material Serviço]@[DS_ITCP_MATERIAL_SERVICO],
--		[Codigo Material Serviço]@[ID_ITCP_MATERIAL_SERVICO],
--		[Esfera UResp Compra]@[ID_UNDD_ESFERA],
--		[Esfera UResp Compra]@[DS_UNDD_ESFERA],
--		[Ind UResp SISG]@[ID_UNDD_IN_SISG],
--		[Ind UResp SISG]@[DS_UNDD_IN_SISG],
--		[Modalidade Compra]@[ID_CMPR_MODALIDADE_COMPRA],
--		[Modalidade Compra]@[DS_CMPR_MODALIDADE_COMPRA],
--		[Nome UResp Compra]@[CD_UNDD_UNIDADE],
--		[Nome UResp Compra]@[NO_UNDD_UNIDADE],
--		[Poder UResp Compra]@[ID_UNDD_PODER],
--		[Poder UResp Compra]@[DS_UNDD_PODER],
--		[Órgão Sup UResp Compra]@[ID_UNDD_ORGAO_SUP],
--		[Órgão Sup UResp Compra]@[DS_UNDD_ORGAO_SUP],
--		[Órgão UResp Compra]@[ID_UNDD_ORGAO],
--		[Órgão UResp Compra]@[DS_UNDD_ORGAO],
--		[Qtde Item Compra],
--		[Valor Unitário Homologado],
--		[Valor Total Homologado]