select	
	a16.ID_UNDD_TP_ADM  ID_UNDD_TP_ADM,
	a122.DS_UNDD_TP_ADM  DS_UNDD_TP_ADM,
	a16.ID_UNDD_ORGAO  ID_UNDD_ORGAO,
	a17.DS_UNDD_ORGAO  DS_UNDD_ORGAO,
	a13.ID_CMPR_TP_LICITACAO  ID_CMPR_TP_LICITACAO,
	a116.DS_CMPR_TP_LICITACAO  DS_CMPR_TP_LICITACAO,
	a13.ID_CMPR_SIT_ATUAL_COMPRA  ID_CMPR_SIT_ATUAL_COMPRA,
	a115.DS_CMPR_SIT_ATUAL_COMPRA  DS_CMPR_SIT_ATUAL_COMPRA,
	a12.ID_ITCP_PADRAO_DESC_MAT  ID_ITCP_PADRAO_DESC_MAT,
	a113.DS_ITCP_PADRAO_DESC_MAT  DS_ITCP_PADRAO_DESC_MAT,
	a12.ID_ITCP_GRUPO_MATERIAL  ID_ITCP_GRUPO_MATERIAL,
	a120.DS_ITCP_GRUPO_MATERIAL  DS_ITCP_GRUPO_MATERIAL,
	a12.ID_ITCP_CLASSE_MAT_SERV  ID_ITCP_CLASSE_MAT_SERV,
	a19.ID_ITCP_CLASSE_MAT_SERV_EDIT  DS_ITCP_CLASSE_MAT_SERV,
	a19.DS_ITCP_CLASSE_MAT_SERV  DS_ITCP_CLASSE_MAT_SERV0,
	a15.ID_DT_MES  ID_DT_MES,
	a112.DS_DT_MES  DS_DT_MES,
	a14.ID_DT_ANO  ID_DT_ANO,
	a117.DS_DT_ANO  DS_DT_ANO,
	a14.ID_DT_MES  ID_DT_MES0,
	a111.DS_DT_MES  DS_DT_MES0,
	a11.ID_ITCP_ITEM_COMPRA  ID_ITCP_ITEM_COMPRA,
	a110.DS_ITCP_COMPL_ITEM_COMPRA  DS_ITCP_COMPL_ITEM_COMPRA,
	a18.ID_UNDD_ORGAO_SUP  ID_UNDD_ORGAO_SUP,
	a123.DS_UNDD_ORGAO_SUP  DS_UNDD_ORGAO_SUP,
	a13.ID_UNDD_RESP_COMPRA  CD_UNDD_UNIDADE,
	a16.NO_UNDD_UNIDADE  NO_UNDD_UNIDADE,
	a16.ID_UNDD_PODER  ID_UNDD_PODER,
	a114.DS_UNDD_PODER  DS_UNDD_PODER,
	a16.ID_UNDD_IN_SISG  ID_UNDD_IN_SISG,
	a121.DS_UNDD_IN_SISG  DS_UNDD_IN_SISG,
	a16.ID_UNDD_ESFERA  ID_UNDD_ESFERA,
	a119.DS_UNDD_ESFERA  DS_UNDD_ESFERA,
	a15.ID_DT_ANO  ID_DT_ANO0,
	a118.DS_DT_ANO  DS_DT_ANO0,
	sum(a11.VL_PRECO_TOTAL_HOMOLOG)  WJXBFS1
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a12
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a12.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a13
	  on 	(a11.ID_CMPR_COMPRA = a13.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a14
	  on 	(a13.DT_HOMOLOG_PREGAO = a14.ID_DT_DATA)
	join	Siasg_DW_VBL.D_DT_DATA	a15
	  on 	(a13.DT_CMPR_RESULTADO_COMPRA = a15.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a16
	  on 	(a13.ID_UNDD_RESP_COMPRA = a16.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a17
	  on 	(a16.ID_UNDD_ORGAO = a17.ID_UNDD_ORGAO)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_VINC	a18
	  on 	(a17.ID_UNDD_ORGAO_VINC = a18.ID_UNDD_ORGAO_VINC)
	join	Siasg_DW_VBL.D_ITCP_CLASSE_MAT_SERV	a19
	  on 	(a12.ID_ITCP_CLASSE_MAT_SERV = a19.ID_ITCP_CLASSE_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_ITEM_COMPRA	a110
	  on 	(a11.ID_ITCP_ITEM_COMPRA = a110.ID_ITCP_ITEM_COMPRA)
	join	Siasg_DW_VBL.D_DT_MES	a111
	  on 	(a14.ID_DT_MES = a111.ID_DT_MES)
	join	Siasg_DW_VBL.D_DT_MES	a112
	  on 	(a15.ID_DT_MES = a112.ID_DT_MES)
	join	Siasg_DW_VBL.D_ITCP_PADRAO_DESC_MAT	a113
	  on 	(a12.ID_ITCP_PADRAO_DESC_MAT = a113.ID_ITCP_PADRAO_DESC_MAT)
	join	Siasg_DW_VBL.D_UNDD_PODER	a114
	  on 	(a16.ID_UNDD_PODER = a114.ID_UNDD_PODER)
	join	Siasg_DW_VBL.D_CMPR_SIT_ATUAL_COMPRA	a115
	  on 	(a13.ID_CMPR_SIT_ATUAL_COMPRA = a115.ID_CMPR_SIT_ATUAL_COMPRA)
	join	Siasg_DW_VBL.D_CMPR_TP_LICITACAO	a116
	  on 	(a13.ID_CMPR_TP_LICITACAO = a116.ID_CMPR_TP_LICITACAO)
	join	Siasg_DW_VBL.D_DT_ANO	a117
	  on 	(a14.ID_DT_ANO = a117.ID_DT_ANO)
	join	Siasg_DW_VBL.D_DT_ANO	a118
	  on 	(a15.ID_DT_ANO = a118.ID_DT_ANO)
	join	Siasg_DW_VBL.D_UNDD_ESFERA	a119
	  on 	(a16.ID_UNDD_ESFERA = a119.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_MATERIAL	a120
	  on 	(a12.ID_ITCP_GRUPO_MATERIAL = a120.ID_ITCP_GRUPO_MATERIAL)
	join	Siasg_DW_VBL.D_UNDD_IN_SISG	a121
	  on 	(a16.ID_UNDD_IN_SISG = a121.ID_UNDD_IN_SISG)
	join	Siasg_DW_VBL.D_UNDD_TP_ADM	a122
	  on 	(a16.ID_UNDD_TP_ADM = a122.ID_UNDD_TP_ADM)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_SUP	a123
	  on 	(a18.ID_UNDD_ORGAO_SUP = a123.ID_UNDD_ORGAO_SUP)
where	
	(a12.ID_ITCP_GRUPO_MATERIAL in (89)
--	(a12.ID_ITCP_PADRAO_DESC_MAT in ('01219')
 	and a15.ID_DT_ANO in (2020))
group by	a16.ID_UNDD_TP_ADM,
	a122.DS_UNDD_TP_ADM,
	a16.ID_UNDD_ORGAO,
	a17.DS_UNDD_ORGAO,
	a13.ID_CMPR_TP_LICITACAO,
	a116.DS_CMPR_TP_LICITACAO,
	a13.ID_CMPR_SIT_ATUAL_COMPRA,
	a115.DS_CMPR_SIT_ATUAL_COMPRA,
	a12.ID_ITCP_PADRAO_DESC_MAT,
	a113.DS_ITCP_PADRAO_DESC_MAT,
	a12.ID_ITCP_GRUPO_MATERIAL,
	a120.DS_ITCP_GRUPO_MATERIAL,
	a12.ID_ITCP_CLASSE_MAT_SERV,
	a19.ID_ITCP_CLASSE_MAT_SERV_EDIT,
	a19.DS_ITCP_CLASSE_MAT_SERV,
	a15.ID_DT_MES,
	a112.DS_DT_MES,
	a14.ID_DT_ANO,
	a117.DS_DT_ANO,
	a14.ID_DT_MES,
	a111.DS_DT_MES,
	a11.ID_ITCP_ITEM_COMPRA,
	a110.DS_ITCP_COMPL_ITEM_COMPRA,
	a18.ID_UNDD_ORGAO_SUP,
	a123.DS_UNDD_ORGAO_SUP,
	a13.ID_UNDD_RESP_COMPRA,
	a16.NO_UNDD_UNIDADE,
	a16.ID_UNDD_PODER,
	a114.DS_UNDD_PODER,
	a16.ID_UNDD_IN_SISG,
	a121.DS_UNDD_IN_SISG,
	a16.ID_UNDD_ESFERA,
	a119.DS_UNDD_ESFERA,
	a15.ID_DT_ANO,
	a118.DS_DT_ANO