SELECT 
	i.ID_ITCP_TP_COD_MAT_SERV AS CODIGO,
	CASE WHEN i.ID_ITCP_TP_COD_MAT_SERV < 2000000000 THEN 'Material'
		 WHEN i.ID_ITCP_TP_COD_MAT_SERV > 2000000000 THEN 'Serviço'
		 END AS TIPO,
	TRIM(c.DS_ITCP_MATERIAL_SERVICO) AS DESCRICAO,
	COUNT(i.ID_ITCP_TP_COD_MAT_SERV) AS CONTA
FROM Siasg_DW_VBL.F_ITEM_COMPRA i
JOIN Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO c ON c.ID_ITCP_TP_COD_MAT_SERV = i.ID_ITCP_TP_COD_MAT_SERV
GROUP BY i.ID_ITCP_TP_COD_MAT_SERV,c.DS_ITCP_MATERIAL_SERVICO
ORDER BY CONTA DESC
--LIMIT 50000