SELECT 
	c.DS_CMPR_COMPRA,
	m.DS_CMPR_MODALIDADE_COMPRA,
	s.DS_CMPR_SIT_ATUAL_COMPRA,
	c.DT_REFERENCIA_COMPRA,
	c.DT_CMPR_RESULTADO_COMPRA,
	c.DT_ENTREGA_EDITAL,
	c.DT_ABERT_SESSAO_PUBL
FROM Siasg_DW_VBL.D_CMPR_COMPRA AS c
	INNER JOIN Siasg_DW_VBL.D_CMPR_SIT_ATUAL_COMPRA AS s
	ON c.ID_CMPR_SIT_ATUAL_COMPRA = s.ID_CMPR_SIT_ATUAL_COMPRA
	INNER JOIN Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA AS m
	ON c.ID_CMPR_MODALIDADE_COMPRA = m.ID_CMPR_MODALIDADE_COMPRA
WHERE c.DT_REFERENCIA_COMPRA > '2020-00-00'
ORDER BY c.DS_CMPR_COMPRA ASC;