with ZZSP00  as (
select	a14.ID_ITCP_PADRAO_DESC_MAT  ID_ITCP_PADRAO_DESC_MAT,
	a14.ID_ITCP_CLASSE_MAT_SERV  ID_ITCP_CLASSE_MAT_SERV,
	sum(a11.QT_ITCP_ITEM_COMPRAS)  WJXBFS1
from	Siasg_DW_VBL.F_ITEM_COMPRA	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a14
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a14.ID_ITCP_TP_COD_MAT_SERV)
where	(a14.ID_ITCP_SIT_ATUAL_MAT_SERV in (1)
 and a13.ID_DT_ANO in (2019, 2021, 2022)
 and a14.ID_ITCP_TP_MATERIAL_SERVICO in (1))
group by	a14.ID_ITCP_PADRAO_DESC_MAT,
	a14.ID_ITCP_CLASSE_MAT_SERV 
), ZZSP01  as (
select	
	a14.ID_ITCP_PADRAO_DESC_MAT  ID_ITCP_PADRAO_DESC_MAT,
	a14.ID_ITCP_CLASSE_MAT_SERV  ID_ITCP_CLASSE_MAT_SERV,
	sum(a11.VL_PRECO_TOTAL_HOMOLOG)  WJXBFS1,
	sum(a11.QT_FORNECEDOR_COMPRA)  WJXBFS2
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a14
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a14.ID_ITCP_TP_COD_MAT_SERV)
where	(a14.ID_ITCP_SIT_ATUAL_MAT_SERV in (1)
 and a13.ID_DT_ANO in (2019, 2021, 2022)
 and a14.ID_ITCP_TP_MATERIAL_SERVICO in (1))
group by	a14.ID_ITCP_PADRAO_DESC_MAT,
	a14.ID_ITCP_CLASSE_MAT_SERV 
)
select	
	a13.ID_ITCP_GRUPO_MATERIAL  ID_ITCP_GRUPO_MATERIAL,
	a13.ID_ITCP_CLASSE_MAT_SERV_EDIT  DS_ITCP_CLASSE_MAT_SERV,
	cast(pa11.ID_ITCP_PADRAO_DESC_MAT as integer)  ID_ITCP_PADRAO_DESC_MAT,
	a15.DS_ITCP_GRUPO_MATERIAL  DS_ITCP_GRUPO_MATERIAL,
--	pa11.ID_ITCP_CLASSE_MAT_SERV  ID_ITCP_CLASSE_MAT_SERV,
	a13.DS_ITCP_CLASSE_MAT_SERV  DS_ITCP_CLASSE_MAT_SERV0,
	a14.DS_ITCP_PADRAO_DESC_MAT  DS_ITCP_PADRAO_DESC_MAT,
	pa12.WJXBFS1  VL_PRECO_TOTAL_HOMOLOG, -- WJXBFS2
	pa12.WJXBFS2  QT_FORNECEDOR_COMPRA, -- WJXBFS3
	pa11.WJXBFS1  QT_ITCP_ITEM_COMPRAS, -- WJXBFS1
	pa12.WJXBFS2/pa11.WJXBFS1 FORCEDORES_POR_COMRA
from	ZZSP00	pa11
	join	ZZSP01	pa12
	  on 	(pa11.ID_ITCP_CLASSE_MAT_SERV = pa12.ID_ITCP_CLASSE_MAT_SERV and 
	pa11.ID_ITCP_PADRAO_DESC_MAT = pa12.ID_ITCP_PADRAO_DESC_MAT)
	join	Siasg_DW_VBL.D_ITCP_CLASSE_MAT_SERV	a13
	  on 	(pa11.ID_ITCP_CLASSE_MAT_SERV = a13.ID_ITCP_CLASSE_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_PADRAO_DESC_MAT	a14
	  on 	(pa11.ID_ITCP_PADRAO_DESC_MAT = a14.ID_ITCP_PADRAO_DESC_MAT)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_MATERIAL	a15
	  on 	(a13.ID_ITCP_GRUPO_MATERIAL = a15.ID_ITCP_GRUPO_MATERIAL)
;