with ZZMQ00  as (
select	a12.ID_CMPR_COMPRA  DS_CMPR_COMPRA_EDIT
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
where	a13.ID_DT_ANO in (2016, 2017, 2018, 2019, 2020, 2021)
group by	a12.ID_CMPR_COMPRA
having	(sum(a11.VL_PRECO_TOTAL_HOMOLOG) > 0
 and sum(a11.VL_PRECO_TOTAL_HOMOLOG) < 8000000000) 
), ZZSP01  as (
select	a12.ID_CMPR_COMPRA  DS_CMPR_COMPRA_EDIT,
	sum(a11.VL_PRECO_TOTAL_HOMOLOG)  VL_PRECO_TOTAL_HOMOLOG
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	ZZMQ00	pa13
	  on 	(a12.ID_CMPR_COMPRA = pa13.DS_CMPR_COMPRA_EDIT)
	join	Siasg_DW_VBL.D_DT_DATA	a14
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
where	a14.ID_DT_ANO in (2016, 2017, 2018, 2019, 2020, 2021)
group by	a12.ID_CMPR_COMPRA 
), ZZSP02  as (
select	a12.ID_CMPR_COMPRA  DS_CMPR_COMPRA_EDIT,
	sum(a11.QT_COMPRAS)  QT_COMPRAS
from	Siasg_DW_VBL.F_COMPRA	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	ZZMQ00	pa13
	  on 	(a12.ID_CMPR_COMPRA = pa13.DS_CMPR_COMPRA_EDIT)
	join	Siasg_DW_VBL.D_DT_DATA	a14
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
where	a14.ID_DT_ANO in (2016, 2017, 2018, 2019, 2020, 2021)
group by	a12.ID_CMPR_COMPRA 
)
select	distinct 
	a15.DS_DT_ANO  						DS_DT_ANO,
--	a14.ID_DT_ANO  						ID_DT_ANO,
--	pa11.DS_CMPR_COMPRA_EDIT  			DS_CMPR_COMPRA_EDIT,
--	a13.DS_CMPR_COMPRA_EDIT  			DS_CMPR_COMPRA,
--	a13.ID_CMPR_MODALIDADE_COMPRA  		ID_CMPR_MODALIDADE_COMPRA,
	a16.DS_CMPR_MODALIDADE_COMPRA  		DS_CMPR_MODALIDADE_COMPRA,
	SUM(pa12.QT_COMPRAS)  				QT_COMPRAS,
	SUM(pa11.VL_PRECO_TOTAL_HOMOLOG)  	VL_PRECO_TOTAL_HOMOLOG
from	ZZSP01	pa11
	join	ZZSP02	pa12
	  on 	(pa11.DS_CMPR_COMPRA_EDIT = pa12.DS_CMPR_COMPRA_EDIT)
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a13
	  on 	(pa11.DS_CMPR_COMPRA_EDIT = a13.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a14
	  on 	(a13.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
	join	Siasg_DW_VBL.D_DT_ANO	a15
	  on 	(a14.ID_DT_ANO = a15.ID_DT_ANO)
	join	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a16
	  on 	(a13.ID_CMPR_MODALIDADE_COMPRA = a16.ID_CMPR_MODALIDADE_COMPRA)
 group by 
--	a14.ID_DT_ANO,
--	pa11.DS_CMPR_COMPRA_EDIT,
--	a13.DS_CMPR_COMPRA_EDIT,
--	a13.ID_CMPR_MODALIDADE_COMPRA,
	a16.DS_CMPR_MODALIDADE_COMPRA,
	a15.DS_DT_ANO
order by a15.DS_DT_ANO, a16.DS_CMPR_MODALIDADE_COMPRA