select	distinct a12.ID_CMPR_COMPRA  DS_CMPR_COMPRA_EDIT,
	a12.DS_CMPR_COMPRA_EDIT  DS_CMPR_COMPRA,
	a12.ID_CMPR_COMPRA  ID_CMPR_COMPRA,
	a12.DS_CMPR_OBJETO_COMPRA  DS_CMPR_COMPRA0,
	a11.ID_FRND_FORNECEDOR  ID_FRND_FORNECEDOR,
	CASE a11.ID_FRND_FORNECEDOR
	WHEN '            -7' THEN 'Inválido'
    WHEN '            -8' THEN 'Não Informado'
	WHEN '            -9' THEN 'Não se Aplica'
	ELSE a11.ID_FRND_FORNECEDOR END  ID_FRND_FORNECEDOR0,
	a11.ID_FRND_FORNECEDOR  ID_FRND_FORNECEDOR1,
	a11.NO_FRND_FORNECEDOR  NO_FRND_FORNECEDOR,
	a11.ID_FRND_SIT_ATUAL_FORNEC  ID_FRND_SIT_ATUAL_FORNEC,
	a16.DS_FRND_SIT_ATUAL_FORNEC  DS_FRND_SIT_ATUAL_FORNEC,
	a11.ID_FRND_TP_PESSOA_FORNEC  ID_FRND_TP_PESSOA_FORNEC,
	a17.DS_FRND_TP_PESSOA_FORNEC  DS_FRND_TP_PESSOA_FORNEC,
	a15.ID_LCAL_UF  ID_LCAL_UF,
	a18.DS_LCAL_UF  DS_LCAL_UF,
	a13.ID_ITCP_ITEM_COMPRA  ID_ITCP_ITEM_COMPRA,
	a13.CH_ITCP_ITEM_COMPRA_EDIT  DS_ITCP_ITEM_COMPRA,
	a14.ID_ITFN_SIT_FORNEC_COMPRA  ID_ITFN_SIT_FORNEC_COMPRA,
	a14.DS_ITFN_SIT_FORNEC_COMPRA  DS_ITFN_SIT_FORNEC_COMPRA
FROM Siasg_DW_VBL.D_CMPR_COMPRA	a12
	JOIN Siasg_DW_VBL.D_ITCP_ITEM_COMPRA a13 ON a12.ID_CMPR_COMPRA = a13.CH_ITCP_ITEM_COMPRA
	JOIN Siasg_DW_VBL.F_ITEM_FORNECEDOR a21 ON 
	JOIN Siasg_DW_VBL.D_FRND_FORNECEDOR	a11
	
	cross join	Siasg_DW_VBL.D_ITFN_SIT_FORNEC_COMPRA	a14
	join	Siasg_DW_VBL.D_LCAL_MUNICIPIO	a15
	  on 	(a11.ID_LCAL_MUNICIPIO_FORNEC = a15.ID_LCAL_MUNICIPIO)
	join	Siasg_DW_VBL.D_FRND_SIT_ATUAL_FORNEC	a16
	  on 	(a11.ID_FRND_SIT_ATUAL_FORNEC = a16.ID_FRND_SIT_ATUAL_FORNEC)
	join	Siasg_DW_VBL.D_FRND_TP_PESSOA_FORNEC	a17
	  on 	(a11.ID_FRND_TP_PESSOA_FORNEC = a17.ID_FRND_TP_PESSOA_FORNEC)
	join	Siasg_DW_VBL.D_LCAL_UF	a18
	  on 	(a15.ID_LCAL_UF = a18.ID_LCAL_UF)
where	a11.ID_FRND_TP_PESSOA_FORNEC in (3);

SELECT *
FROM Siasg_DW_VBL.D_CMPR_COMPRA	a12
JOIN Siasg_DW_VBL.D_ITCP_ITEM_COMPRA a13 ON a12.ID_CMPR_COMPRA = a13.CH_ITCP_ITEM_COMPRA
LIMIT 20;