SELECT DISTINCT
         IT.ID_ITCP_ITEM_COMPRA
        ,COUNT(VF.VL_UNIT_PROPOSTO) AS N_PROPOSTAS
        ,IFR.QT_COMPRADA_ITEM AS QTD
        ,IFR.VL_PRECO_ITEM_COMPRA AS VL_UNITARIO
        ,CM.VL_ITCP_PRECO_UNIT_ESTIM AS VL_UN_ESTIM
        ,IT.DS_ITCP_UNIDADE_FORNECIMENTO AS UNIDADE
        ,CASE WHEN SUM(VF.QT_ITFN_LANCES_ITEM_FORNEC) IS NULL THEN 0 ELSE SUM(VF.QT_ITFN_LANCES_ITEM_FORNEC) END AS QTD_LANCES_TOTAL
        ,CASE WHEN IT.DS_ITCP_MODELO_VERSAO IS NOT NULL THEN 1
              WHEN IT.DS_ITCP_MODELO_VERSAO IS NULL THEN 0
              WHEN IT.DS_ITCP_MODELO_VERSAO = 'NAO SE APLICA' THEN 0
              END AS MARCA
        ,IFR.ID_ITCP_TP_COD_MAT_SERV AS CODMATSERV
        ,UN.ID_LCAL_MUNICIPIO_UNIDADE AS MUNIC_SIAFI
        ,CASE WHEN IT.ID_ITCP_IN_PREF_PROD_NACIONAL = 1 THEN 1 ELSE 0 END AS PREFERENCIA_NACIONAL
		,'' AS VALOR_SIGILOSO --        ,CASE WHEN IT.ID_ITCP_IN_VL_SIGILOSO = 1 THEN 1 ELSE 0 END AS VALOR_SIGILOSO
        ,CP.DT_REFERENCIA_COMPRA AS DT_COMPRA
    FROM Siasg_DW_VBL.D_ITCP_ITEM_COMPRA AS IT
    INNER JOIN Siasg_DW_VBL.F_ITEM_UNID_FORNEC AS IFR ON IFR.ID_ITCP_ITEM_COMPRA = IT.ID_ITCP_ITEM_COMPRA
    INNER JOIN Siasg_DW_VBL.F_ITEM_FORNECEDOR AS VF ON VF.ID_ITCP_ITEM_COMPRA = IT.ID_ITCP_ITEM_COMPRA
    INNER JOIN Siasg_DW_VBL.F_ITEM_COMPRA AS CM ON CM.ID_ITCP_ITEM_COMPRA = IT.ID_ITCP_ITEM_COMPRA
    INNER JOIN Siasg_DW_VBL.D_CMPR_COMPRA AS CP ON CP.ID_CMPR_COMPRA = CM.ID_CMPR_COMPRA
    INNER JOIN Siasg_DW_VBL.D_UNDD_UNIDADE AS UN ON UN.ID_UNDD_UNIDADE = CP.ID_UNDD_RESP_COMPRA
    WHERE CM.ID_ITCP_SIT_ATUAL_ITEM = 1 AND (SUBSTRING(CP.DT_REFERENCIA_COMPRA,1,4) BETWEEN 2010 AND 2020) -- AND IFR.ID_ITCP_TP_COD_MAT_SERV IN ({})
    GROUP BY IT.ID_ITCP_ITEM_COMPRA,
             IT.DS_ITCP_MODELO_VERSAO,
             IFR.QT_COMPRADA_ITEM,
             IFR.VL_PRECO_ITEM_COMPRA,
             IT.DS_ITCP_UNIDADE_FORNECIMENTO,
             IFR.ID_ITCP_TP_COD_MAT_SERV,
             IT.ID_ITCP_IN_PREF_PROD_NACIONAL,
--             IT.ID_ITCP_IN_VL_SIGILOSO,
             CM.VL_ITCP_PRECO_UNIT_ESTIM,
             UN.ID_LCAL_MUNICIPIO_UNIDADE,
             CP.DT_REFERENCIA_COMPRA
