select
	a111.DS_ITCP_PADRAO_DESC_MAT,
--	REPLACE(REPLACE(REPLACE(REPLACE(a111.DS_ITCP_PADRAO_DESC_MAT, '"', ''), '*', ''), 'DE PIPOCA', 'PIPOCA'), ' - ', ' ')    DS_ITCP_PADRAO_DESC_MAT,
	SUM(CASE WHEN a12.ID_DT_ANO = '2010' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2011' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2012' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2013' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2014' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2015' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2016' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2017' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2018' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2019' THEN a11.VL_ITEP_EMPENHADO END),
	SUM(CASE WHEN a12.ID_DT_ANO = '2020' THEN a11.VL_ITEP_EMPENHADO END)
--	sum(a11.VL_ITEP_EMPENHADO)  VALOR_TOTAL_EMPENHADO
from	Siasg_DW_VBL.F_ITEM_EMPENHO	a11
	join	Siasg_DW_VBL.D_DT_DATA	a12
	  on 	(a11.DT_EMPN_CONTAB_EMPENHO = a12.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a13
	  on 	(a11.ID_UNDD_UG_RESP_EMPENHO = a13.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_EMPN_PLACA_INDICADORES	a14
	  on 	(a11.ID_EMPN_PLACA_INDICADORES = a14.ID_EMPN_PLACA_INDICADORES)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a15
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a15.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_DT_ANO	a16
	  on 	(a12.ID_DT_ANO = a16.ID_DT_ANO)
	join	Siasg_DW_VBL.D_UNDD_ESFERA	a17
	  on 	(a13.ID_UNDD_ESFERA = a17.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_EMPN_ESPECIE_EMPENHO	a18
	  on 	(a14.ID_EMPN_ESPECIE_EMPENHO = a18.ID_EMPN_ESPECIE_EMPENHO)
	join	Siasg_DW_VBL.D_UNDD_IN_SISG	a19
	  on 	(a13.ID_UNDD_IN_SISG = a19.ID_UNDD_IN_SISG)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_SUP	a110
	  on 	(a13.ID_UNDD_ORGAO_SUP = a110.ID_UNDD_ORGAO_SUP)
	join	Siasg_DW_VBL.D_ITCP_PADRAO_DESC_MAT	a111
	  on 	(a15.ID_ITCP_PADRAO_DESC_MAT = a111.ID_ITCP_PADRAO_DESC_MAT)
	join	Siasg_DW_VBL.D_UNDD_PODER	a112
	  on 	(a13.ID_UNDD_PODER = a112.ID_UNDD_PODER)
	join	Siasg_DW_VBL.D_UNDD_TP_ADM	a113
	  on 	(a13.ID_UNDD_TP_ADM = a113.ID_UNDD_TP_ADM)
where	(a12.ID_DT_ANO in (2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)
 and (
 	a111.DS_ITCP_PADRAO_DESC_MAT LIKE '%CARNE%'
	))
group by
	a111.DS_ITCP_PADRAO_DESC_MAT