WITH temp AS (
    SELECT	
      CAST(a13.ID_DT_DATA AS STRING)				AS DATA,
      CASE WHEN a16.ID_ITCP_IN_COMPRA_GRUPO = 0 	THEN a16.CH_ITCP_ITEM_COMPRA_EDIT
		   WHEN a16.ID_ITCP_IN_COMPRA_GRUPO != 0 	THEN a12.DS_CMPR_COMPRA_EDIT||'GR'||LPAD(a16.ID_ITCP_IN_COMPRA_GRUPO, 3, 0) END AS COD_ITEM_GRUPO,
	  COUNT(DISTINCT a11.ID_FRND_FORNECEDOR_COMPRA)	AS CONTA_FORNECEDOR,
      SUM(a15.VL_ITCP_PRECO_GLOBAL_ESTIM)			AS VALOR_TOTAL_ESTIMADO
    FROM	Siasg_DW_VBL.F_ITEM_FORNECEDOR			a11
      JOIN	Siasg_DW_VBL.D_CMPR_COMPRA				a12
        ON 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
      JOIN	Siasg_DW_VBL.D_DT_DATA					a13
        ON 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
      JOIN	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a14
        ON 	(a12.ID_CMPR_MODALIDADE_COMPRA = a14.ID_CMPR_MODALIDADE_COMPRA)
      JOIN  Siasg_DW_VBL.F_ITEM_COMPRA				a15
        ON  (a11.ID_ITCP_ITEM_COMPRA = a15.ID_ITCP_ITEM_COMPRA)
      JOIN	Siasg_DW_VBL.D_ITCP_ITEM_COMPRA			a16
	  ON 	(a11.ID_ITCP_ITEM_COMPRA = a16.ID_ITCP_ITEM_COMPRA)
	WHERE	(a14.ID_CMPR_MODALIDADE_GRUPO in (5)
	 AND a13.ID_DT_ANO BETWEEN '2021' AND '2021'
--	 AND a13.ID_DT_MES IN ('202101', '202102')
	 AND a12.ID_CMPR_TP_PREGAO in (1))
	GROUP BY
		a13.ID_DT_DATA,
----		a12.DS_CMPR_COMPRA,
----		a16.ID_ITCP_IN_COMPRA_GRUPO,
----		a15.VL_ITCP_PRECO_GLOBAL_ESTIM,
--		a16.CH_ITCP_ITEM_COMPRA_EDIT
----		a12.DS_CMPR_COMPRA_EDIT,
		CASE WHEN a16.ID_ITCP_IN_COMPRA_GRUPO = 0  THEN a16.CH_ITCP_ITEM_COMPRA_EDIT
		     WHEN a16.ID_ITCP_IN_COMPRA_GRUPO != 0 THEN a12.DS_CMPR_COMPRA_EDIT||'GR'||LPAD(a16.ID_ITCP_IN_COMPRA_GRUPO, 3, 0) END
	HAVING	SUM(a11.VL_ULT_LANCE) > 0.0
	ORDER BY DATA, COD_ITEM_GRUPO
)
--, temp2 AS (
--SELECT
--	CAST(a14.ID_DT_MES AS STRING)				AS ID_DT_MES,
--	CASE WHEN a16.ID_ITCP_IN_COMPRA_GRUPO = 0 THEN a16.CH_ITCP_ITEM_COMPRA_EDIT
--		 WHEN a16.ID_ITCP_IN_COMPRA_GRUPO != 0 THEN a13.DS_CMPR_COMPRA_EDIT||'GR'||LPAD(a16.ID_ITCP_IN_COMPRA_GRUPO, 3, 0) END AS COD_ITEM_GRUPO,
--	COUNT(DISTINCT a11.ID_FRND_FORNECEDOR) 		AS CONTA_FORNECEDOR,
--	SUM(pa12.VL_PRECO_TOTAL_HOMOLOG)			AS VL_PRECO_TOTAL_HOMOLOG,
--	SUM(pa12.VL_PRECO_TOTAL_ESTIM) 				AS VL_PRECO_TOTAL_ESTIM
--FROM	Siasg_DW_VBL.D_FRND_FORNECEDOR				a11
--	JOIN	temp									pa12
--	  ON 	(a11.ID_FRND_FORNECEDOR = pa12.ID_FRND_FORNECEDOR)
--	JOIN	Siasg_DW_VBL.D_CMPR_COMPRA				a13
--	  ON 	(pa12.ID_CMPR_COMPRA = a13.ID_CMPR_COMPRA)
--	JOIN	Siasg_DW_VBL.D_DT_DATA					a14
--	  ON 	(a13.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
--	JOIN	Siasg_DW_VBL.D_ITCP_ITEM_COMPRA			a16
--	  ON 	(pa12.ID_ITCP_ITEM_COMPRA = a16.ID_ITCP_ITEM_COMPRA)
--	JOIN	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a17
--	  ON 	(a13.ID_CMPR_MODALIDADE_COMPRA = a17.ID_CMPR_MODALIDADE_COMPRA)
--WHERE	(a17.ID_CMPR_MODALIDADE_GRUPO in (5)
--	 AND a14.ID_DT_ANO IN (2021)
--	 AND a14.ID_DT_MES IN ('202101', '202102')
--	 AND a13.ID_CMPR_TP_PREGAO in (1)
--	 )
--GROUP BY
--	a14.ID_DT_MES,
--	CASE WHEN a16.ID_ITCP_IN_COMPRA_GRUPO = 0 	THEN a16.CH_ITCP_ITEM_COMPRA_EDIT
--		 WHEN a16.ID_ITCP_IN_COMPRA_GRUPO != 0 	THEN a13.DS_CMPR_COMPRA_EDIT||'GR'||LPAD(a16.ID_ITCP_IN_COMPRA_GRUPO, 3, 0) END
--)
SELECT
	DATA AS data, 
	CAST(AVG(CONTA_FORNECEDOR) AS FLOAT) AS mediaparticipantespregao, 
	CAST(SUM(CONTA_FORNECEDOR) AS FLOAT) AS totalparticipantespregao, 
	COUNT(DISTINCT SUBSTRING(COD_ITEM_GRUPO, 1, 17)) AS contacompras, 
	COUNT(DISTINCT COD_ITEM_GRUPO) AS contaitensgrupos, 
	SUM(VALOR_TOTAL_ESTIMADO) AS valortotalestimado
FROM temp
GROUP BY DATA
ORDER BY DATA;