select	
	a19.DS_DT_ANO  DS_DT_ANO,
	a112.DS_UNDD_ESFERA  DS_UNDD_ESFERA,
	a111.DS_UNDD_PODER  DS_UNDD_PODER,
	a113.DS_UNDD_IN_SISG  DS_UNDD_IN_SISG,
	a15.CD_UNDD_UNIDADE  CD_UNDD_UNIDADE, --
	a15.NO_UNDD_UNIDADE  NO_UNDD_UNIDADE, --
	a18.DS_ITCP_TP_MATERIAL_SERVICO  DS_ITCP_TP_MATERIAL_SERVICO,
	a17.DS_ITCP_IN_SUSTENTAVEL  DS_ITCP_IN_SUSTENTAVEL,
	count(distinct a16.CH_ITCP_ITEM_COMPRA_EDIT)  DS_ITCP_ITEM_COMPRA,
	sum(a11.VL_PRECO_TOTAL_HOMOLOG)  VL_PRECO_TOTAL_HOMOLOG
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a13
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a13.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_DT_DATA	a14
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a15
	  on 	(a12.ID_UNDD_RESP_COMPRA = a15.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_ITCP_ITEM_COMPRA	a16
	  on 	(a11.ID_ITCP_ITEM_COMPRA = a16.ID_ITCP_ITEM_COMPRA)
	join	Siasg_DW_VBL.D_ITCP_IN_SUSTENTAVEL	a17
	  on 	(a13.ID_ITCP_IN_SUSTENTAVEL = a17.ID_ITCP_IN_SUSTENTAVEL)
	join	Siasg_DW_VBL.D_ITCP_TP_MATERIAL_SERVICO	a18
	  on 	(a13.ID_ITCP_TP_MATERIAL_SERVICO = a18.ID_ITCP_TP_MATERIAL_SERVICO)
	join	Siasg_DW_VBL.D_DT_ANO	a19
	  on 	(a14.ID_DT_ANO = a19.ID_DT_ANO)
	join	Siasg_DW_VBL.D_ITCP_IN_SUSTENTAVEL	a110
	  on 	(a16.ID_ITCP_IN_SUSTENTAVEL = a110.ID_ITCP_IN_SUSTENTAVEL)
	join	Siasg_DW_VBL.D_UNDD_PODER	a111
	  on 	(a15.ID_UNDD_PODER = a111.ID_UNDD_PODER)
	join	Siasg_DW_VBL.D_UNDD_ESFERA	a112
	  on 	(a15.ID_UNDD_ESFERA = a112.ID_UNDD_ESFERA)
	join	Siasg_DW_VBL.D_UNDD_IN_SISG	a113
	  on 	(a15.ID_UNDD_IN_SISG = a113.ID_UNDD_IN_SISG)
where	(a15.ID_UNDD_ESFERA in (3)
		 and a15.ID_UNDD_PODER in (1)
		 and a15.ID_UNDD_IN_SISG in (1)
		 and a13.ID_ITCP_TP_MATERIAL_SERVICO in (1)
		 and a15.ID_UNDD_ORGAO in (26248) --
		 and a14.ID_DT_ANO in (2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)
		 and a11.VL_PRECO_TOTAL_HOMOLOG < 8000000000
		 )
group by	
	a14.ID_DT_ANO,
	a19.DS_DT_ANO,
	a15.ID_UNDD_ESFERA,
	a112.DS_UNDD_ESFERA,
	a13.ID_ITCP_TP_MATERIAL_SERVICO,
	a18.DS_ITCP_TP_MATERIAL_SERVICO,
	a15.ID_UNDD_PODER,
	a111.DS_UNDD_PODER,
	a15.ID_UNDD_IN_SISG,
	a113.DS_UNDD_IN_SISG,
	a12.ID_UNDD_RESP_COMPRA, --
	a15.CD_UNDD_UNIDADE, --
	a15.NO_UNDD_UNIDADE, --
	a12.ID_UNDD_RESP_COMPRA, --
	a15.NO_UNDD_UNIDADE, --
	a13.ID_ITCP_IN_SUSTENTAVEL, 
	a17.DS_ITCP_IN_SUSTENTAVEL
order by
	a19.DS_DT_ANO,
	a17.DS_ITCP_IN_SUSTENTAVEL