WITH pregao AS (
   SELECT	
   		a14.ID_DT_MES							AS ID_DT_MES,
   		a11.ID_FRND_FORNECEDOR_COMPRA  			AS ID_FRND_FORNECEDOR,
		COUNT(DISTINCT a12.ID_CMPR_COMPRA) 		AS CONTA_PREGAO,
		COUNT(DISTINCT a11.ID_ITCP_ITEM_COMPRA) AS CONTA_PREGAO_ITEM
    FROM	Siasg_DW_VBL.F_ITEM_FORNECEDOR			a11
      JOIN	Siasg_DW_VBL.D_CMPR_COMPRA				a12
        ON 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
      JOIN	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a13
        ON 	(a12.ID_CMPR_MODALIDADE_COMPRA = a13.ID_CMPR_MODALIDADE_COMPRA)
      JOIN	Siasg_DW_VBL.D_DT_DATA					a14
        ON 	(a12.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
	WHERE	(a13.ID_CMPR_MODALIDADE_GRUPO in (5)
		AND a12.ID_CMPR_TP_PREGAO in (1)
		AND a14.ID_DT_ANO IN (2021,2020,2019,2018,2017,2016,2015,2014,2013,2012))
	GROUP BY	
		a14.ID_DT_MES,
		a11.ID_FRND_FORNECEDOR_COMPRA
	HAVING	SUM(a11.VL_ULT_LANCE) > 0.0
)
, cotacao AS (
	SELECT
		a14.ID_DT_MES							AS ID_DT_MES,
		a11.ID_FRND_FORNECEDOR_COMPRA  			AS ID_FRND_FORNECEDOR,
		COUNT(DISTINCT a12.ID_CMPR_COMPRA) 		AS CONTA_COTACAO,
		COUNT(DISTINCT a11.ID_ITCP_ITEM_COMPRA) AS CONTA_COTACAO_ITEM
	FROM    Siasg_DW_VBL.F_ITEM_FORNECEDOR				a11
		JOIN    Siasg_DW_VBL.D_CMPR_COMPRA				a12
		ON     (a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
		JOIN    Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a13
		ON     (a12.ID_CMPR_MODALIDADE_COMPRA = a13.ID_CMPR_MODALIDADE_COMPRA)
		JOIN    Siasg_DW_VBL.D_DT_DATA					a14
		ON     (a12.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
	WHERE	(a13.ID_CMPR_MODALIDADE_GRUPO in (6)
		AND a12.ID_CMPR_IN_COTACAO_ELETR in (1)
		AND a14.ID_DT_ANO in (2021,2020,2019,2018,2017,2016,2015,2014,2013,2012))
	GROUP BY
		a14.ID_DT_MES,
		a11.ID_FRND_FORNECEDOR_COMPRA
	HAVING SUM(a11.VL_ULT_LANCE) >=  0.0
)
SELECT p.ID_DT_MES as anomes, CAST(AVG(CONTA_PREGAO_ITEM) AS FLOAT) AS mediaitenspregao, CAST(AVG(CONTA_COTACAO_ITEM) AS FLOAT) AS razaopregaocotacao, CAST(AVG(CONTA_PREGAO_ITEM) AS FLOAT)/CAST(AVG(CONTA_COTACAO_ITEM) AS FLOAT) AS mediaitenspregao,NOW() AS datahoraregisto
FROM cotacao c
	JOIN pregao p ON c.ID_FRND_FORNECEDOR = p.ID_FRND_FORNECEDOR  
GROUP BY p.ID_DT_MES
ORDER BY p.ID_DT_MES