WITH ZZMQ00  as (
	select	
		a11.ID_FRND_FORNECEDOR_COMPRA  	ID_FRND_FORNECEDOR,
		a12.ID_CMPR_COMPRA  			DS_CMPR_COMPRA_EDIT,
		a11.ID_ITCP_ITEM_COMPRA  		ID_ITCP_ITEM_COMPRA
	from	Siasg_DW_VBL.F_ITEM_FORNECEDOR				a11
		join	Siasg_DW_VBL.D_CMPR_COMPRA				a12
		  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
		join	Siasg_DW_VBL.D_DT_DATA					a13
		  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
		join	Siasg_DW_VBL.D_UNDD_UNIDADE				a14
		  on 	(a12.ID_UNDD_RESP_COMPRA = a14.ID_UNDD_UNIDADE)
		join	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a15
		  on 	(a12.ID_CMPR_MODALIDADE_COMPRA = a15.ID_CMPR_MODALIDADE_COMPRA)
	where	(a15.ID_CMPR_MODALIDADE_GRUPO in (5)
	 and a14.ID_UNDD_IN_SISG in (2, 1)
	 and a13.ID_DT_ANO in (2021)
	 and a13.ID_DT_MES in (202101)
	 and a12.DT_CMPR_RESULTADO_COMPRA BETWEEN '2021-01-01' AND '2021-02-01'
	 and a12.ID_CMPR_TP_PREGAO in (1))
	group by
		a11.ID_FRND_FORNECEDOR_COMPRA,
		a12.ID_CMPR_COMPRA,
		a11.ID_ITCP_ITEM_COMPRA
	having	sum(a11.VL_ULT_LANCE) > 0.0 
), ZZSP01  as (
	select	
		a11.ID_ITCP_ITEM_COMPRA  ID_ITCP_ITEM_COMPRA,
		a12.ID_CMPR_COMPRA  DS_CMPR_COMPRA_EDIT,
		a11.ID_FRND_FORNECEDOR_COMPRA  ID_FRND_FORNECEDOR
	from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
		join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
		  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
		join	ZZMQ00	pa13
		  on 	(a11.ID_FRND_FORNECEDOR_COMPRA = pa13.ID_FRND_FORNECEDOR and 
				a11.ID_ITCP_ITEM_COMPRA = pa13.ID_ITCP_ITEM_COMPRA and 
				a12.ID_CMPR_COMPRA = pa13.DS_CMPR_COMPRA_EDIT)
		join	Siasg_DW_VBL.D_DT_DATA	a14
		  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
		join	Siasg_DW_VBL.D_UNDD_UNIDADE	a15
		  on 	(a12.ID_UNDD_RESP_COMPRA = a15.ID_UNDD_UNIDADE)
		join	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a16
		  on 	(a12.ID_CMPR_MODALIDADE_COMPRA = a16.ID_CMPR_MODALIDADE_COMPRA)
	where	(a16.ID_CMPR_MODALIDADE_GRUPO in (5)
	 and a15.ID_UNDD_IN_SISG in (2, 1)
	 and a14.ID_DT_ANO in (2021)
	 and a14.ID_DT_MES in (202101)
	 and a12.DT_CMPR_RESULTADO_COMPRA BETWEEN '2021-01-01' AND '2021-02-01'
	 and a12.ID_CMPR_TP_PREGAO in (1))
	group by	
		a11.ID_ITCP_ITEM_COMPRA,
		a12.ID_CMPR_COMPRA,
		a11.ID_FRND_FORNECEDOR_COMPRA 
), ZZSP02  as (
	select	
		pa12.ID_ITCP_ITEM_COMPRA  ID_ITCP_ITEM_COMPRA,
		pa12.DS_CMPR_COMPRA_EDIT  DS_CMPR_COMPRA_EDIT,
		a11.ID_FRND_FORNECEDOR  ID_FRND_FORNECEDOR
	from	Siasg_DW_VBL.D_FRND_FORNECEDOR	a11
		join	ZZMQ00	pa12
		  on 	(a11.ID_FRND_FORNECEDOR = pa12.ID_FRND_FORNECEDOR)
		join	Siasg_DW_VBL.D_CMPR_COMPRA	a13
		  on 	(pa12.DS_CMPR_COMPRA_EDIT = a13.ID_CMPR_COMPRA)
		join	Siasg_DW_VBL.D_DT_DATA	a14
		  on 	(a13.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
		join	Siasg_DW_VBL.D_UNDD_UNIDADE	a15
		  on 	(a13.ID_UNDD_RESP_COMPRA = a15.ID_UNDD_UNIDADE)
		join	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a16
		  on 	(a13.ID_CMPR_MODALIDADE_COMPRA = a16.ID_CMPR_MODALIDADE_COMPRA)
	where	(a16.ID_CMPR_MODALIDADE_GRUPO in (5)
	 and a15.ID_UNDD_IN_SISG in (2, 1)
	 and a14.ID_DT_ANO in (2021)
	 and a14.ID_DT_MES in (202101)
	 and a13.DT_CMPR_RESULTADO_COMPRA BETWEEN '2021-01-01' AND '2021-02-01'
	 and a13.ID_CMPR_TP_PREGAO in (1))
	group by	
		pa12.ID_ITCP_ITEM_COMPRA,
		pa12.DS_CMPR_COMPRA_EDIT,
		a11.ID_FRND_FORNECEDOR 
)
select
--	a14.ID_DT_ANO  		ID_DT_ANO,
	a115.DS_DT_ANO  				DS_DT_ANO,
	a14.ID_DT_MES  					ID_DT_MES,
--	a113.DS_DT_MES  				DS_DT_MES,
--	a15.ID_UNDD_IN_SISG  			ID_UNDD_IN_SISG,
	a110.DS_UNDD_IN_SISG  			DS_UNDD_IN_SISG,
--	a15.ID_LCAL_UF_UNIDADE  		ID_LCAL_UF,
--	a114.DS_LCAL_UF  				DS_LCAL_UF,
--	a17.ID_CMPR_MODALIDADE_GRUPO  	ID_CMPR_MODALIDADE_GRUPO,
	a112.DS_CMPR_MODALIDADE_GRUPO  	DS_CMPR_MODALIDADE_GRUPO,
--	a13.ID_CMPR_TP_PREGAO  			ID_CMPR_TP_PREGAO,
	a19.DS_CMPR_TP_PREGAO  			DS_CMPR_TP_PREGAO,
--	pa11.DS_CMPR_COMPRA_EDIT  		DS_CMPR_COMPRA_EDIT,
	a13.DS_CMPR_COMPRA_EDIT  		DS_CMPR_COMPRA,
--	pa11.ID_ITCP_ITEM_COMPRA  		ID_ITCP_ITEM_COMPRA,
--	a16.CH_ITCP_ITEM_COMPRA_EDIT  	DS_ITCP_ITEM_COMPRA,
--	pa11.ID_FRND_FORNECEDOR  		ID_FRND_FORNECEDOR,
--     decode(a18.ID_FRND_FORNECEDOR, '            -7', 'Inválido',
--                '            -8', 'Não Informado',
--                '            -9', 'Não se Aplica',
--                                   a18.ID_FRND_FORNECEDOR)  ID_FRND_FORNECEDOR0,
	a16.ID_ITCP_IN_COMPRA_GRUPO  	ID_ITCP_IN_COMPRA_GRUPO,
	a111.DS_ITCP_IN_COMPRA_GRUPO  	DS_ITCP_IN_COMPRA_GRUPO,
	CASE WHEN a16.ID_ITCP_IN_COMPRA_GRUPO = 0 THEN a16.CH_ITCP_ITEM_COMPRA_EDIT
		 WHEN a16.ID_ITCP_IN_COMPRA_GRUPO != 0 THEN a13.DS_CMPR_COMPRA_EDIT||'GR'||LPAD(a16.ID_ITCP_IN_COMPRA_GRUPO, 3, 0) END AS COD_ITEM_GRUPO,
--	pa11.VL_ULT_LANCE  				VL_ULT_LANCE,
	COUNT(a18.ID_FRND_FORNECEDOR) 	CONTA_FORNECEDOR
from		ZZSP01														pa11
	join	ZZSP02														pa12
	  on 	(pa11.DS_CMPR_COMPRA_EDIT = pa12.DS_CMPR_COMPRA_EDIT and 
			 pa11.ID_FRND_FORNECEDOR = pa12.ID_FRND_FORNECEDOR and 
			 pa11.ID_ITCP_ITEM_COMPRA = pa12.ID_ITCP_ITEM_COMPRA)
	join	Siasg_DW_VBL.D_CMPR_COMPRA									a13
	  on 	(pa11.DS_CMPR_COMPRA_EDIT = a13.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA										a14
	  on 	(a13.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE									a15
	  on 	(a13.ID_UNDD_RESP_COMPRA = a15.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_ITCP_ITEM_COMPRA								a16
	  on 	(pa11.ID_ITCP_ITEM_COMPRA = a16.ID_ITCP_ITEM_COMPRA)
	join	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA						a17
	  on 	(a13.ID_CMPR_MODALIDADE_COMPRA = a17.ID_CMPR_MODALIDADE_COMPRA)
	join	Siasg_DW_VBL.D_FRND_FORNECEDOR								a18
	  on 	(pa11.ID_FRND_FORNECEDOR = a18.ID_FRND_FORNECEDOR)
	join	Siasg_DW_VBL.D_CMPR_TP_PREGAO								a19
	  on 	(a13.ID_CMPR_TP_PREGAO = a19.ID_CMPR_TP_PREGAO)
	join	Siasg_DW_VBL.D_UNDD_IN_SISG									a110
	  on 	(a15.ID_UNDD_IN_SISG = a110.ID_UNDD_IN_SISG)
	join	Siasg_DW_VBL.D_ITCP_IN_COMPRA_GRUPO							a111
	  on 	(a16.ID_ITCP_IN_COMPRA_GRUPO = a111.ID_ITCP_IN_COMPRA_GRUPO)
	join	Siasg_DW_VBL.D_CMPR_MODALIDADE_GRUPO						a112
	  on 	(a17.ID_CMPR_MODALIDADE_GRUPO = a112.ID_CMPR_MODALIDADE_GRUPO)
	join	Siasg_DW_VBL.D_DT_MES										a113
	  on 	(a14.ID_DT_MES = a113.ID_DT_MES)
--	join	Siasg_DW_VBL.D_LCAL_UF										a114
--	  on 	(a15.ID_LCAL_UF_UNIDADE = a114.ID_LCAL_UF)
	join	Siasg_DW_VBL.D_DT_ANO										a115
	  on 	(a14.ID_DT_ANO = a115.ID_DT_ANO)
--where a14.ID_DT_MES = 202101
group by
  		pa11.DS_CMPR_COMPRA_EDIT,
  		a16.CH_ITCP_ITEM_COMPRA_EDIT,
  		a16.ID_ITCP_IN_COMPRA_GRUPO,
  		a115.DS_DT_ANO,
  		a110.DS_UNDD_IN_SISG,
  		a112.DS_CMPR_MODALIDADE_GRUPO,
  		a19.DS_CMPR_TP_PREGAO,
  		a14.ID_DT_MES,
  		a13.DS_CMPR_COMPRA_EDIT,
  		a111.DS_ITCP_IN_COMPRA_GRUPO,
  		pa11.DS_CMPR_COMPRA_EDIT||LPAD(a16.ID_ITCP_IN_COMPRA_GRUPO, 5, 0)