with ZZMQ00 as ( -- ZZT90K01BTRMQ000
select	a13.ID_DT_ANO  ID_DT_ANO,
	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
	a12.ID_CMPR_MODALIDADE_COMPRA  ID_CMPR_MODALIDADE_COMPRA,
	a17.ID_UNDD_ORGAO_SUP  ID_UNDD_ORGAO_SUP
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a14
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a14.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a15
	  on 	(a12.ID_UNDD_RESP_COMPRA = a15.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a16
	  on 	(a15.ID_UNDD_ORGAO = a16.ID_UNDD_ORGAO)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_VINC	a17
	  on 	(a16.ID_UNDD_ORGAO_VINC = a17.ID_UNDD_ORGAO_VINC)
where	(a13.ID_DT_ANO in (2020, 2021, 2022)
 and a14.ID_ITCP_TP_MATERIAL_SERVICO in (1)
-- and a12.ID_UNDD_RESP_COMPRA in (130024)
-- and a17.ID_UNDD_ORGAO_SUP in (22000)
--and a17.ID_UNDD_ORGAO_SUP BETWEEN 20000 AND 30000
 )
group by	a13.ID_DT_ANO,
	a11.ID_ITCP_TP_COD_MAT_SERV,
	a12.ID_CMPR_MODALIDADE_COMPRA,
	a17.ID_UNDD_ORGAO_SUP
having	sum(a11.VL_PRECO_TOTAL_HOMOLOG) > 0 
),
ZZSP01  as (
select	a16.ID_UNDD_ORGAO_SUP  ID_UNDD_ORGAO_SUP,
	a12.ID_CMPR_MODALIDADE_COMPRA  ID_CMPR_MODALIDADE_COMPRA,
	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
	a13.ID_DT_ANO  ID_DT_ANO,
	sum(a11.QT_ITCP_ITEM_COMPRAS)  WJXBFS1,
	sum(a11.QT_ITCP_SOLICITADA)  WJXBFS2
from	Siasg_DW_VBL.F_ITEM_COMPRA	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
	  on 	(a12.ID_UNDD_RESP_COMPRA = a14.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a15
	  on 	(a14.ID_UNDD_ORGAO = a15.ID_UNDD_ORGAO)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_VINC	a16
	  on 	(a15.ID_UNDD_ORGAO_VINC = a16.ID_UNDD_ORGAO_VINC)
	join	ZZMQ00	pa17
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = pa17.ID_ITCP_TP_COD_MAT_SERV and 
	a12.ID_CMPR_MODALIDADE_COMPRA = pa17.ID_CMPR_MODALIDADE_COMPRA and 
	a13.ID_DT_ANO = pa17.ID_DT_ANO and 
	a16.ID_UNDD_ORGAO_SUP = pa17.ID_UNDD_ORGAO_SUP)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a18
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a18.ID_ITCP_TP_COD_MAT_SERV)
where	(a13.ID_DT_ANO in (2020, 2021, 2022)
 and a18.ID_ITCP_TP_MATERIAL_SERVICO in (1)
-- and a12.ID_UNDD_RESP_COMPRA in (130024)
-- and a16.ID_UNDD_ORGAO_SUP in (22000)
--and a16.ID_UNDD_ORGAO_SUP BETWEEN 20000 AND 30000
 )
group by	a16.ID_UNDD_ORGAO_SUP,
	a12.ID_CMPR_MODALIDADE_COMPRA,
	a11.ID_ITCP_TP_COD_MAT_SERV,
	a13.ID_DT_ANO 
),
ZZSP02  as (
select	a16.ID_UNDD_ORGAO_SUP  ID_UNDD_ORGAO_SUP,
	a12.ID_CMPR_MODALIDADE_COMPRA  ID_CMPR_MODALIDADE_COMPRA,
	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
	a13.ID_DT_ANO  ID_DT_ANO,
	sum(a11.VL_PRECO_TOTAL_HOMOLOG)  WJXBFS1,
	avg(a11.VL_PRECO_UNIT_HOMOLOG)  WJXBFS2
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
	  on 	(a12.ID_UNDD_RESP_COMPRA = a14.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a15
	  on 	(a14.ID_UNDD_ORGAO = a15.ID_UNDD_ORGAO)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_VINC	a16
	  on 	(a15.ID_UNDD_ORGAO_VINC = a16.ID_UNDD_ORGAO_VINC)
	join	ZZMQ00	pa17
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = pa17.ID_ITCP_TP_COD_MAT_SERV and 
	a12.ID_CMPR_MODALIDADE_COMPRA = pa17.ID_CMPR_MODALIDADE_COMPRA and 
	a13.ID_DT_ANO = pa17.ID_DT_ANO and 
	a16.ID_UNDD_ORGAO_SUP = pa17.ID_UNDD_ORGAO_SUP)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a18
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a18.ID_ITCP_TP_COD_MAT_SERV)
where	(a13.ID_DT_ANO in (2020, 2021, 2022)
 and a18.ID_ITCP_TP_MATERIAL_SERVICO in (1)
-- and a12.ID_UNDD_RESP_COMPRA in (130024)
-- and a16.ID_UNDD_ORGAO_SUP in (22000)
--and a16.ID_UNDD_ORGAO_SUP BETWEEN 20000 AND 30000
 )
group by	a16.ID_UNDD_ORGAO_SUP,
	a12.ID_CMPR_MODALIDADE_COMPRA,
	a11.ID_ITCP_TP_COD_MAT_SERV,
	a13.ID_DT_ANO 
)
select	
--	pa11.ID_CMPR_MODALIDADE_COMPRA  ID_CMPR_MODALIDADE_COMPRA,
	a15.DS_CMPR_MODALIDADE_COMPRA  ModalidadeCompra,
--	pa11.ID_DT_ANO  ID_DT_ANO,
	a13.DS_DT_ANO  AnoCompra,
	pa11.ID_UNDD_ORGAO_SUP  CodOrgaoSuperior,
	a16.DS_UNDD_ORGAO_SUP  DesOrgaoSuperior,
--	pa11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
	a14.ID_ITCP_MATERIAL_SERVICO  CodCatalogo,
	a14.DS_ITCP_MATERIAL_SERVICO  DesCatalogo,
	pa11.WJXBFS1  QtdeItemCompra, -- WJXBFS1,
	pa11.WJXBFS2  QtdeSolicitada, -- WJXBFS4
	pa12.WJXBFS2  ValorUnitarioMedioHomologado, -- WJXBFS2,
	pa12.WJXBFS1  ValorTotalHomologado -- WJXBFS3,
from	ZZSP01	pa11
	join	ZZSP02	pa12
	  on 	(pa11.ID_CMPR_MODALIDADE_COMPRA = pa12.ID_CMPR_MODALIDADE_COMPRA and 
			pa11.ID_DT_ANO = pa12.ID_DT_ANO and 
			pa11.ID_ITCP_TP_COD_MAT_SERV = pa12.ID_ITCP_TP_COD_MAT_SERV and 
			pa11.ID_UNDD_ORGAO_SUP = pa12.ID_UNDD_ORGAO_SUP)
	join	Siasg_DW_VBL.D_DT_ANO	a13
	  on 	(pa11.ID_DT_ANO = a13.ID_DT_ANO)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a14
	  on 	(pa11.ID_ITCP_TP_COD_MAT_SERV = a14.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a15
	  on 	(pa11.ID_CMPR_MODALIDADE_COMPRA = a15.ID_CMPR_MODALIDADE_COMPRA)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_SUP	a16
	  on 	(pa11.ID_UNDD_ORGAO_SUP = a16.ID_UNDD_ORGAO_SUP)
order by pa11.WJXBFS2 DESC, pa12.WJXBFS1 DESC
limit 1000
;

