SELECT *
FROM DWTG_Colunar_VBL.WD_DOC_NE
WHERE NO_SISTEMA_ORIGEM LIKE 'COMPRASNET CONTRATOS' AND ID_DOC_NE LIKE '%2021NE%'
;

select 
	a15.ID_DOC_NE ID_DOC_NE,
	a17.ID_ANO_EMISSAO_DOC ID_ANO,
	a17.ID_MES_EMISSAO_DOC ID_MES,
	a17.ID_DIA_EMISSAO_DOC ID_DIA,
	max(a110.NO_DIA_COMPLETO) NO_DIA_COMPLETO,
	a16.ID_TP_ENTIDADE ID_TP_ENTIDADE,
	max(a114.NO_TP_ENTIDADE) NO_TP_ENTIDADE,
	a14.ID_TP_ENTIDADE_FAVO_DOC ID_TP_ENTIDADE0,
	a14.ID_ENTIDADE_FAVO_DOC ID_ENTIDADE,
	max(a16.NO_ENTIDADE) NO_ENTIDADE,
	a17.TX_DESCRICAO TX_DESCRICAO,
	a18.ID_FONTE_RECURSO_DETA ID_FONTE_RECURSO_DETA,
	max(a111.CO_FONTE_RECURSO_DETA) CO_FONTE_RECURSO_DETA,
	max(a111.NO_FONTE_RECURSO_DETA) NO_FONTE_RECURSO_DETA,
	a18.ID_CATEGORIA_ECONOMICA_NADE ID_CATEGORIA_ECONOMICA_NADE,
	a18.ID_GRUPO_DESPESA_NADE ID_GRUPO_DESPESA_NADE,
	a18.ID_MOAP_NADE ID_MOAP_NADE,
	a18.ID_ELEMENTO_DESPESA_NADE ID_ELEMENTO_DESPESA_NADE,
	max(a112.CO_NATUREZA_DESPESA) CO_NATUREZA_DESPESA,
	max(a112.NO_NATUREZA_DESPESA) NO_NATUREZA_DESPESA,
	a18.ID_ORGAO_PI ID_ORGAO_PI,
	a18.ID_PI ID_PI,
	max(a113.NO_PI) NO_PI,
	a14.ID_DOC_ORIGEM ID_DOC_ORIGEM,
	a17.NO_SISTEMA_ORIGEM NO_SISTEMA_ORIGEM,
	a14.ID_ANO_TRANSACAO_DOC ID_ANO0,
	a14.ID_MES_TRANSACAO_DOC ID_MES0,
	a14.ID_DIA_TRANSACAO_DOC ID_DIA0,
	max(a19.NO_DIA_COMPLETO) NO_DIA_COMPLETO0,
	a11.ID_ANO ID_ANO1,
	a11.ID_MES ID_MES1,
	a11.ID_DIA ID_DIA1,
	max(a11.NO_DIA_COMPLETO) NO_DIA_COMPLETO1
from DWTG_Colunar_VBL.WD_DIA a11
	join DWTG_Colunar_VBL.WD_MES a12
		on (a11.ID_ANO = a12.ID_ANO and	a11.ID_MES = a12.ID_MES)
	cross join (DWTG_Colunar_VBL.WD_DOCUMENTO a14
		join DWTG_Colunar_VBL.WD_DOC_RO a15
			on (a14.ID_DOC_RO = a15.ID_DOC_RO))
	join DWTG_Colunar_VBL.WD_ENTIDADE a16
		on (a14.ID_ENTIDADE_FAVO_DOC = a16.ID_ENTIDADE and a14.ID_TP_ENTIDADE_FAVO_DOC = a16.ID_TP_ENTIDADE)
	join DWTG_Colunar_VBL.WD_DOC_NE a17
		on (a15.ID_DOC_NE = a17.ID_DOC_NE)
	join DWTG_Colunar_VBL.WF_DOC_NE a18
		on (a15.ID_DOC_NE = a18.ID_DOCUMENTO)
	join DWTG_Colunar_VBL.WD_DIA a19
		on (a14.ID_ANO_TRANSACAO_DOC = a19.ID_ANO and
		a14.ID_DIA_TRANSACAO_DOC = a19.ID_DIA and
		a14.ID_MES_TRANSACAO_DOC = a19.ID_MES)
	join DWTG_Colunar_VBL.WD_DIA a110
		on (a17.ID_ANO_EMISSAO_DOC = a110.ID_ANO and
		a17.ID_DIA_EMISSAO_DOC = a110.ID_DIA and
		a17.ID_MES_EMISSAO_DOC = a110.ID_MES)
	join DWTG_Colunar_VBL.WD_FONTE_RECURSO_DETA a111
		on (a18.ID_FONTE_RECURSO_DETA = a111.ID_FONTE_RECURSO_DETA)
	join DWTG_Colunar_VBL.WD_NATUREZA_DESPESA a112
		on (a18.ID_CATEGORIA_ECONOMICA_NADE = a112.ID_CATEGORIA_ECONOMICA_NADE and
		a18.ID_ELEMENTO_DESPESA_NADE = a112.ID_ELEMENTO_DESPESA_NADE and
		a18.ID_GRUPO_DESPESA_NADE = a112.ID_GRUPO_DESPESA_NADE and
		a18.ID_MOAP_NADE = a112.ID_MOAP_NADE)
	join DWTG_Colunar_VBL.WD_PI a113
		on (a18.ID_ORGAO_PI = a113.ID_ORGAO_PI and
		a18.ID_PI = a113.ID_PI)
	join DWTG_Colunar_VBL.WD_TP_ENTIDADE a114
		on (a16.ID_TP_ENTIDADE = a114.ID_TP_ENTIDADE)
where (a15.ID_DOC_NE like '%2021NE%'
	and a17.NO_SISTEMA_ORIGEM in ('COMPRASNET CONTRATOS')
	and a17.ID_MES_EMISSAO_DOC in ('07'))
group by 
	a15.ID_DOC_NE,
	a17.ID_ANO_EMISSAO_DOC,
	a17.ID_MES_EMISSAO_DOC,
	a17.ID_DIA_EMISSAO_DOC,
	a16.ID_TP_ENTIDADE,
	a14.ID_TP_ENTIDADE_FAVO_DOC,
	a14.ID_ENTIDADE_FAVO_DOC,
	a17.TX_DESCRICAO,
	a18.ID_FONTE_RECURSO_DETA,
	a18.ID_CATEGORIA_ECONOMICA_NADE,
	a18.ID_GRUPO_DESPESA_NADE,
	a18.ID_MOAP_NADE,
	a18.ID_ELEMENTO_DESPESA_NADE,
	a18.ID_ORGAO_PI,
	a18.ID_PI,
	a14.ID_DOC_ORIGEM,
	a17.NO_SISTEMA_ORIGEM,
	a14.ID_ANO_TRANSACAO_DOC,
	a14.ID_MES_TRANSACAO_DOC,
	a14.ID_DIA_TRANSACAO_DOC,
	a11.ID_ANO,
	a11.ID_MES,
	a11.ID_DIA;

select 
	a15.ID_DOC_NE ID_DOC_NE,
	a17.ID_ANO_EMISSAO_DOC ID_ANO,
	a17.ID_MES_EMISSAO_DOC ID_MES,
	a17.ID_DIA_EMISSAO_DOC ID_DIA,
	max(a110.NO_DIA_COMPLETO) NO_DIA_COMPLETO,
--	a16.ID_TP_ENTIDADE ID_TP_ENTIDADE,
--	max(a114.NO_TP_ENTIDADE) NO_TP_ENTIDADE,
--	a14.ID_TP_ENTIDADE_FAVO_DOC ID_TP_ENTIDADE0,
--	a14.ID_ENTIDADE_FAVO_DOC ID_ENTIDADE,
--	max(a16.NO_ENTIDADE) NO_ENTIDADE,
--	a17.TX_DESCRICAO TX_DESCRICAO,
--	a18.ID_FONTE_RECURSO_DETA ID_FONTE_RECURSO_DETA,
--	max(a111.CO_FONTE_RECURSO_DETA) CO_FONTE_RECURSO_DETA,
--	max(a111.NO_FONTE_RECURSO_DETA) NO_FONTE_RECURSO_DETA,
--	a18.ID_CATEGORIA_ECONOMICA_NADE ID_CATEGORIA_ECONOMICA_NADE,
--	a18.ID_GRUPO_DESPESA_NADE ID_GRUPO_DESPESA_NADE,
--	a18.ID_MOAP_NADE ID_MOAP_NADE,
--	a18.ID_ELEMENTO_DESPESA_NADE ID_ELEMENTO_DESPESA_NADE,
--	max(a112.CO_NATUREZA_DESPESA) CO_NATUREZA_DESPESA,
--	max(a112.NO_NATUREZA_DESPESA) NO_NATUREZA_DESPESA,
--	a18.ID_ORGAO_PI ID_ORGAO_PI,
--	a18.ID_PI ID_PI,
--	max(a113.NO_PI) NO_PI,
--	a14.ID_DOC_ORIGEM ID_DOC_ORIGEM,
	a17.NO_SISTEMA_ORIGEM NO_SISTEMA_ORIGEM,
	a14.ID_ANO_TRANSACAO_DOC ID_ANO0,
	a14.ID_MES_TRANSACAO_DOC ID_MES0,
	a14.ID_DIA_TRANSACAO_DOC ID_DIA0,
	max(a19.NO_DIA_COMPLETO) NO_DIA_COMPLETO0,
	a11.ID_ANO ID_ANO1,
	a11.ID_MES ID_MES1,
	a11.ID_DIA ID_DIA1,
	max(a11.NO_DIA_COMPLETO) NO_DIA_COMPLETO1
from DWTG_Colunar_VBL.WD_DIA a11
	join DWTG_Colunar_VBL.WD_MES a12
		on (a11.ID_ANO = a12.ID_ANO and	a11.ID_MES = a12.ID_MES)
	cross join (DWTG_Colunar_VBL.WD_DOCUMENTO a14
		join DWTG_Colunar_VBL.WD_DOC_RO a15
			on (a14.ID_DOC_RO = a15.ID_DOC_RO))
--	join DWTG_Colunar_VBL.WD_ENTIDADE a16
--		on (a14.ID_ENTIDADE_FAVO_DOC = a16.ID_ENTIDADE and a14.ID_TP_ENTIDADE_FAVO_DOC = a16.ID_TP_ENTIDADE)
	join DWTG_Colunar_VBL.WD_DOC_NE a17
		on (a15.ID_DOC_NE = a17.ID_DOC_NE)
	join DWTG_Colunar_VBL.WF_DOC_NE a18
		on (a15.ID_DOC_NE = a18.ID_DOCUMENTO)
	join DWTG_Colunar_VBL.WD_DIA a19
		on (a14.ID_ANO_TRANSACAO_DOC = a19.ID_ANO and
		a14.ID_DIA_TRANSACAO_DOC = a19.ID_DIA and
		a14.ID_MES_TRANSACAO_DOC = a19.ID_MES)
	join DWTG_Colunar_VBL.WD_DIA a110
		on (a17.ID_ANO_EMISSAO_DOC = a110.ID_ANO and
		a17.ID_DIA_EMISSAO_DOC = a110.ID_DIA and
		a17.ID_MES_EMISSAO_DOC = a110.ID_MES)
--	join DWTG_Colunar_VBL.WD_FONTE_RECURSO_DETA a111
--		on (a18.ID_FONTE_RECURSO_DETA = a111.ID_FONTE_RECURSO_DETA)
--	join DWTG_Colunar_VBL.WD_NATUREZA_DESPESA a112
--		on (a18.ID_CATEGORIA_ECONOMICA_NADE = a112.ID_CATEGORIA_ECONOMICA_NADE and
--		a18.ID_ELEMENTO_DESPESA_NADE = a112.ID_ELEMENTO_DESPESA_NADE and
--		a18.ID_GRUPO_DESPESA_NADE = a112.ID_GRUPO_DESPESA_NADE and
--		a18.ID_MOAP_NADE = a112.ID_MOAP_NADE)
--	join DWTG_Colunar_VBL.WD_PI a113
--		on (a18.ID_ORGAO_PI = a113.ID_ORGAO_PI and
--		a18.ID_PI = a113.ID_PI)
--	join DWTG_Colunar_VBL.WD_TP_ENTIDADE a114
--		on (a16.ID_TP_ENTIDADE = a114.ID_TP_ENTIDADE)
where (a15.ID_DOC_NE like '%2021NE%'
	and a17.NO_SISTEMA_ORIGEM in ('COMPRASNET CONTRATOS') 
	and a17.ID_MES_EMISSAO_DOC in ('05', '06', '07'))
group by 
	a15.ID_DOC_NE,
	a17.ID_ANO_EMISSAO_DOC,
	a17.ID_MES_EMISSAO_DOC,
	a17.ID_DIA_EMISSAO_DOC,
--	a16.ID_TP_ENTIDADE,
--	a14.ID_TP_ENTIDADE_FAVO_DOC,
--	a14.ID_ENTIDADE_FAVO_DOC,
--	a17.TX_DESCRICAO,
--	a18.ID_FONTE_RECURSO_DETA,
--	a18.ID_CATEGORIA_ECONOMICA_NADE,
--	a18.ID_GRUPO_DESPESA_NADE,
--	a18.ID_MOAP_NADE,
--	a18.ID_ELEMENTO_DESPESA_NADE,
--	a18.ID_ORGAO_PI,
--	a18.ID_PI,
	a14.ID_DOC_ORIGEM,
	a17.NO_SISTEMA_ORIGEM,
	a14.ID_ANO_TRANSACAO_DOC,
	a14.ID_MES_TRANSACAO_DOC,
	a14.ID_DIA_TRANSACAO_DOC,
	a11.ID_ANO,
	a11.ID_MES,
	a11.ID_DIA;

