select	
--	a13.ID_DT_ANO  ID_DT_ANO,
	a15.DS_DT_ANO  DS_DT_ANO,
--	a12.ID_CMPR_MODALIDADE_COMPRA  ID_CMPR_MODALIDADE_COMPRA,
	a16.DS_CMPR_MODALIDADE_COMPRA  DS_CMPR_MODALIDADE_COMPRA,
--	a14.ID_FRND_TP_PESSOA_FORNEC  ID_FRND_TP_PESSOA_FORNEC,
	a19.DS_FRND_TP_PESSOA_FORNEC  DS_FRND_TP_PESSOA_FORNEC,
--	a14.ID_FRND_PORTE_EMPRESA_FORNEC  ID_FRND_PORTE_EMPRESA,
	a18.DS_FRND_PORTE_EMPRESA  DS_FRND_PORTE_EMPRESA,
--	a14.ID_FRND_NATUREZA_JURID_FORNEC  ID_FRND_NATUREZA_JURIDICA,
	a17.DS_FRND_NATUREZA_JURIDICA  ID_FRND_NATUREZA_JURIDICA0,
	sum(a11.QT_FORNECEDOR_COMPRA)  QT_FORNECEDOR_COMPRA,
	sum(a11.VL_PRECO_TOTAL_HOMOLOG)  VL_PRECO_TOTAL_HOMOLOG
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_FRND_FORNECEDOR	a14
	  on 	(a11.ID_FRND_FORNECEDOR_COMPRA = a14.ID_FRND_FORNECEDOR)
	join	Siasg_DW_VBL.D_DT_ANO	a15
	  on 	(a13.ID_DT_ANO = a15.ID_DT_ANO)
	join	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a16
	  on 	(a12.ID_CMPR_MODALIDADE_COMPRA = a16.ID_CMPR_MODALIDADE_COMPRA)
	left join	Siasg_DW_VBL.D_FRND_NATUREZA_JURIDICA	a17
	  on 	(a14.ID_FRND_NATUREZA_JURID_FORNEC = a17.ID_FRND_NATUREZA_JURIDICA)
	join	Siasg_DW_VBL.D_FRND_PORTE_EMPRESA	a18
	  on 	(a14.ID_FRND_PORTE_EMPRESA_FORNEC = a18.ID_FRND_PORTE_EMPRESA)
	join	Siasg_DW_VBL.D_FRND_TP_PESSOA_FORNEC	a19
	  on 	(a14.ID_FRND_TP_PESSOA_FORNEC = a19.ID_FRND_TP_PESSOA_FORNEC)
where	a13.ID_DT_ANO in (2018, 2019, 2020, 2021, 2022)
group by	a13.ID_DT_ANO,
	a15.DS_DT_ANO,
	a12.ID_CMPR_MODALIDADE_COMPRA,
	a16.DS_CMPR_MODALIDADE_COMPRA,
	a14.ID_FRND_TP_PESSOA_FORNEC,
	a19.DS_FRND_TP_PESSOA_FORNEC,
	a14.ID_FRND_PORTE_EMPRESA_FORNEC,
	a18.DS_FRND_PORTE_EMPRESA,
	a14.ID_FRND_NATUREZA_JURID_FORNEC,
	a17.DS_FRND_NATUREZA_JURIDICA
order by DS_DT_ANO, DS_CMPR_MODALIDADE_COMPRA, DS_FRND_TP_PESSOA_FORNEC, DS_FRND_PORTE_EMPRESA, ID_FRND_NATUREZA_JURIDICA0
