WITH temp1 AS (
    SELECT	
      a11.ID_FRND_FORNECEDOR_COMPRA  	AS ID_FRND_FORNECEDOR,
      a12.ID_CMPR_COMPRA  				AS ID_CMPR_COMPRA,
      a11.ID_ITCP_ITEM_COMPRA  			AS ID_ITCP_ITEM_COMPRA,
      SUM(a11.VL_PRECO_TOTAL_HOMOLOG)	AS VL_PRECO_TOTAL_HOMOLOG
    FROM	Siasg_DW_VBL.F_ITEM_FORNECEDOR			a11
      JOIN	Siasg_DW_VBL.D_CMPR_COMPRA				a12
        ON 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
      JOIN	Siasg_DW_VBL.D_DT_DATA					a13
        ON 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
      JOIN	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a14
        ON 	(a12.ID_CMPR_MODALIDADE_COMPRA = a14.ID_CMPR_MODALIDADE_COMPRA)
	WHERE	(a14.ID_CMPR_MODALIDADE_GRUPO in (5)
	 AND a13.ID_DT_ANO in (2021)
	 AND a12.ID_CMPR_TP_PREGAO in (1))
	GROUP BY	
		a13.ID_DT_DATA,
		a11.ID_FRND_FORNECEDOR_COMPRA,
		a12.ID_CMPR_COMPRA,
		a11.ID_ITCP_ITEM_COMPRA
	HAVING	SUM(a11.VL_ULT_LANCE) > 0.0
)
, temp2 AS (
SELECT
	CAST(a14.ID_DT_DATA AS STRING)		AS ID_DT_DATA,
	a16.CH_ITCP_ITEM_COMPRA_EDIT 		AS COD_ITEM,
	COUNT(a11.ID_FRND_FORNECEDOR) 		AS CONTA_FORNECEDOR,
	SUM(pa12.VL_PRECO_TOTAL_HOMOLOG)	AS VL_PRECO_TOTAL_HOMOLOG
FROM	Siasg_DW_VBL.D_FRND_FORNECEDOR				a11
	JOIN	TEMP1									pa12
	  ON 	(a11.ID_FRND_FORNECEDOR = pa12.ID_FRND_FORNECEDOR)
	JOIN	Siasg_DW_VBL.D_CMPR_COMPRA				a13
	  ON 	(pa12.ID_CMPR_COMPRA = a13.ID_CMPR_COMPRA)
	JOIN	Siasg_DW_VBL.D_DT_DATA					a14
	  ON 	(a13.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
	JOIN	Siasg_DW_VBL.D_ITCP_ITEM_COMPRA			a16
	  ON 	(pa12.ID_ITCP_ITEM_COMPRA = a16.ID_ITCP_ITEM_COMPRA)
	JOIN	Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA	a17
	  ON 	(a13.ID_CMPR_MODALIDADE_COMPRA = a17.ID_CMPR_MODALIDADE_COMPRA)
WHERE	(a17.ID_CMPR_MODALIDADE_GRUPO in (5)
	 AND a14.ID_DT_ANO in (2021)
	 AND a13.ID_CMPR_TP_PREGAO in (1))
GROUP BY
	a14.ID_DT_DATA,
	a13.DS_CMPR_COMPRA_EDIT,
	a16.CH_ITCP_ITEM_COMPRA_EDIT
)
SELECT ID_DT_DATA AS data, CAST(AVG(CONTA_FORNECEDOR) AS FLOAT) AS mediaparticipantespregao, CAST(SUM(CONTA_FORNECEDOR) AS FLOAT) AS totalparticipantespregao, COUNT(DISTINCT SUBSTRING(COD_ITEM, 1, 17)) AS contacompras, COUNT(DISTINCT COD_ITEM) AS contaitensgrupos, SUM(VL_PRECO_TOTAL_HOMOLOG) AS valortotalhomologado, NOW() AS datahoraregisto
FROM temp2
GROUP BY ID_DT_DATA
ORDER BY ID_DT_DATA;