select	
--	a12.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
--	max(a110.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
--	max(a110.CO_ITEM_INFORMACAO)  CO_ITEM_INFORMACAO,
--	a13.ID_ORGAO_UG  ID_ORGAO,
--	max(a18.CO_ORGAO)  CO_ORGAO,
--	max(a18.NO_ORGAO)  NO_ORGAO,
--	a13.ID_UG  ID_UG_EXEC,
--	max(a17.CO_UG)  CO_UG,
--	max(a17.NO_UG)  NO_UG,
--	a15.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
	max(a19.CO_ORGAO_MAXI)  CO_ORGAO_MAXI,
	max(a19.NO_ORGAO_MAXI)  NO_ORGAO_MAXI,
--	a16.ID_TP_ENTIDADE_FAVO_DOC  ID_TP_ENTIDADE,
	a16.ID_ENTIDADE_FAVO_DOC  ID_ENTIDADE,
	max(a111.NO_ENTIDADE)  NO_ENTIDADE,
	a11.ID_DOCUMENTO_CCOR  ID_DOCUMENTO,
--	a11.ID_DOCUMENTO_CCOR||LPAD(a116.ID_ITEM, 5, 0)  ID_ITEM,
	sum((a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO))  MOVIMLQUIDOMOEDAORIGEMITEMINF
from		DWTG_Colunar_VBL.WF_LANCAMENTO				a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON	a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
			a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO			a13
	  on 	(a11.ID_ANO_LANC = a13.ID_ANO and 
			a11.ID_UG_EXEC = a13.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO			a14
	  on 	(a13.ID_ANO = a14.ID_ANO and 
			a13.ID_ORGAO_UG = a14.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO	a15
	  on 	(a14.ID_ANO = a15.ID_ANO and 
			a14.ID_ORGAO_SUPE = a15.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_DOC_NE					a16
	  on 	(a11.ID_DOCUMENTO_CCOR = a16.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_UG						a17
	  on 	(a13.ID_UG = a17.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO					a18
	  on 	(a13.ID_ORGAO_UG = a18.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI				a19
	  on 	(a15.ID_ORGAO_MAXI = a19.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO			a110
	  on 	(a12.ID_ITEM_INFORMACAO = a110.ID_ITEM_INFORMACAO)
	join	DWTG_Colunar_VBL.WD_ENTIDADE				a111
	  on 	(a16.ID_ENTIDADE_FAVO_DOC = a111.ID_ENTIDADE and 
			a16.ID_TP_ENTIDADE_FAVO_DOC = a111.ID_TP_ENTIDADE)
	join	DWTG_Colunar_VBL.WD_DOC_NE_ITEM				a116
	  on 	(a16.ID_DOC_NE = a116.ID_DOC_NE)
where	(a12.ID_ITEM_INFORMACAO in (61)
	 and a15.ID_ORGAO_MAXI in (22000)
--	 and a13.ID_UG in (130024)
	 and a17.ID_MOEDA_UG in (790)
	 and a16.ID_ANO_EMISSAO_DOC in (2020)
	 and a16.NO_SISTEMA_ORIGEM in ('SIASG')
	 and a11.ID_TP_DOCUMENTO in ('NE', 'OB')
--	 and a11.ID_DOCUMENTO_CCOR in ('')
	 )
group by	
	a12.ID_ITEM_INFORMACAO,
--	a13.ID_ORGAO_UG,
--	a13.ID_UG,
	a15.ID_ORGAO_MAXI,
	a16.ID_TP_ENTIDADE_FAVO_DOC,
	a16.ID_ENTIDADE_FAVO_DOC,
	a11.ID_DOCUMENTO_CCOR
--	a116.ID_ITEM