select distinct
	UPPER(a14.DS_ITCP_TP_MATERIAL_SERVICO)  DS_ITCP_TP_MATERIAL_SERVICO,
	a11.ID_ITCP_GRUPO_MATERIAL	ID_ITCP_GRUPO_MATERIAL,
	a15.DS_ITCP_GRUPO_MATERIAL  DS_ITCP_GRUPO_MATERIAL,
	a12.ID_ITCP_CLASSE_MAT_SERV_EDIT ID_ITCP_CLASSE_MAT_SERV_EDIT,
	a12.DS_ITCP_CLASSE_MAT_SERV  ID_ITCP_CLASSE_MAT_SERV,
	CAST(a11.ID_ITCP_PADRAO_DESC_MAT AS INTEGER) ID_ITCP_PADRAO_DESC_MAT,
	a17.DS_ITCP_PADRAO_DESC_MAT  DS_ITCP_PADRAO_DESC_MAT,
	a11.ID_ITCP_MATERIAL_SERVICO  ID_ITCP_MATERIAL_SERVICO,
	a11.DS_ITCP_MATERIAL_SERVICO  DS_ITCP_MATERIAL_SERVICO
--	UPPER(translate(
--			substring(a11.DS_ITCP_MATERIAL_SERVICO, 2, 624),
--			N'¡¿¬√ƒ≈‡·‚„‰Â????Ê∆«Á????¢©????»… ÀËÈÍÎ??????ÃÕŒœÏÌÓÔ????£—Ò????“”‘’’÷ÿÚÛÙıˆ¯????Æäö??ﬂ??Ÿ⁄€‹˘˙˚¸????µ◊•üˇ˝›éû????-', 
--			N'aaaaaaaaaaaaaaaaaaccccccccddddeeeeeeeeeeeeeeiiiiiiiiiilllnnnnnooooooooooooooooorrsssssttuuuuuuuuuuuuuxyyyyyzzzzzz '))
--			DS_ITCP_MATERIAL_SERVICO_PROCESSADO
from	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a11
	join	Siasg_DW_VBL.D_ITCP_CLASSE_MAT_SERV	a12
	  on 	(a11.ID_ITCP_CLASSE_MAT_SERV = a12.ID_ITCP_CLASSE_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_SIT_ATUAL_MAT_SERV	a13
	  on 	(a11.ID_ITCP_SIT_ATUAL_MAT_SERV = a13.ID_ITCP_SIT_ATUAL_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_TP_MATERIAL_SERVICO	a14
	  on 	(a11.ID_ITCP_TP_MATERIAL_SERVICO = a14.ID_ITCP_TP_MATERIAL_SERVICO)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_MATERIAL	a15
	  on 	(a11.ID_ITCP_GRUPO_MATERIAL = a15.ID_ITCP_GRUPO_MATERIAL)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_SERVICO	a16
	  on 	(a11.ID_ITCP_GRUPO_SERVICO = a16.ID_ITCP_GRUPO_SERVICO)
	join	Siasg_DW_VBL.D_ITCP_PADRAO_DESC_MAT	a17
	  on 	(a11.ID_ITCP_PADRAO_DESC_MAT = a17.ID_ITCP_PADRAO_DESC_MAT)
where	a11.ID_ITCP_SIT_ATUAL_MAT_SERV in (1) and a11.ID_ITCP_TP_MATERIAL_SERVICO in (1) and a12.ID_ITCP_CLASSE_MAT_SERV_EDIT IN ('2540','4910','7610','6850','8960','3990','7610','6640','8440','8510','7810')