with ZZMQ00 as (
select
	a11.ID_FRND_FORNECEDOR_COMPRA  ID_FRND_FORNECEDOR,
    a12.ID_CMPR_COMPRA  DS_CMPR_COMPRA_EDIT,
    a11.ID_ITCP_ITEM_COMPRA  ID_ITCP_ITEM_COMPRA
from    Siasg_DW_VBL.F_ITEM_FORNECEDOR    a11
    join    Siasg_DW_VBL.D_CMPR_COMPRA    a12
      on     (a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
    join    Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA    a13
      on     (a12.ID_CMPR_MODALIDADE_COMPRA = a13.ID_CMPR_MODALIDADE_COMPRA)
    join    Siasg_DW_VBL.D_DT_DATA    a14
      on     (a12.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
where    (a13.ID_CMPR_MODALIDADE_GRUPO in (6)
	 and a12.ID_CMPR_IN_COTACAO_ELETR in (1)
	 and a14.ID_DT_ANO in (2021))
group by
	a11.ID_FRND_FORNECEDOR_COMPRA,
    a12.ID_CMPR_COMPRA,
    a11.ID_ITCP_ITEM_COMPRA
having sum(a11.VL_ULT_LANCE) >=  0.0 
)
select
	a15.ID_DT_MES  ID_DT_MES,
    pa12.DS_CMPR_COMPRA_EDIT  DS_CMPR_COMPRA_EDIT,
    a13.DS_CMPR_COMPRA_EDIT  DS_CMPR_COMPRA,
    pa12.ID_ITCP_ITEM_COMPRA  ID_ITCP_ITEM_COMPRA,
    a16.CH_ITCP_ITEM_COMPRA_EDIT  DS_ITCP_ITEM_COMPRA,
    count(a11.ID_FRND_FORNECEDOR)  CONTA_ID_FRND_FORNECEDOR
from    Siasg_DW_VBL.D_FRND_FORNECEDOR    a11
    join    ZZMQ00    pa12
      on     (a11.ID_FRND_FORNECEDOR = pa12.ID_FRND_FORNECEDOR)
    join    Siasg_DW_VBL.D_CMPR_COMPRA    a13
      on     (pa12.DS_CMPR_COMPRA_EDIT = a13.ID_CMPR_COMPRA)
    join    Siasg_DW_VBL.D_CMPR_MODALIDADE_COMPRA    a14
      on     (a13.ID_CMPR_MODALIDADE_COMPRA = a14.ID_CMPR_MODALIDADE_COMPRA)
    join    Siasg_DW_VBL.D_DT_DATA    a15
      on     (a13.DT_CMPR_RESULTADO_COMPRA = a15.ID_DT_DATA)
    join    Siasg_DW_VBL.D_ITCP_ITEM_COMPRA    a16
      on     (pa12.ID_ITCP_ITEM_COMPRA = a16.ID_ITCP_ITEM_COMPRA)
where    (a14.ID_CMPR_MODALIDADE_GRUPO in (6)
	 and a13.ID_CMPR_IN_COTACAO_ELETR in (1)
	 and a15.ID_DT_ANO in (2021))
group by
	a15.ID_DT_MES,
    pa12.DS_CMPR_COMPRA_EDIT,
    a13.DS_CMPR_COMPRA_EDIT,
    pa12.ID_ITCP_ITEM_COMPRA,
    a16.CH_ITCP_ITEM_COMPRA_EDIT