select
--	a11.ID_ITCP_SIT_ATUAL_MAT_SERV  ID_ITCP_SIT_ATUAL_MAT_SERV,
	a13.DS_ITCP_SIT_ATUAL_MAT_SERV  DS_ITCP_SIT_ATUAL_MAT_SERV,
--	a11.ID_ITCP_TP_MATERIAL_SERVICO  ID_ITCP_TP_MATERIAL_SERVICO,
	a14.DS_ITCP_TP_MATERIAL_SERVICO  DS_ITCP_TP_MATERIAL_SERVICO,
	a11.ID_ITCP_GRUPO_MATERIAL  ID_ITCP_GRUPO_MATERIAL,
	a15.DS_ITCP_GRUPO_MATERIAL  DS_ITCP_GRUPO_MATERIAL,
	a11.ID_ITCP_GRUPO_SERVICO  ID_ITCP_GRUPO_SERVICO,
	a16.DS_ITCP_GRUPO_SERVICO  DS_ITCP_GRUPO_SERVICO,
	a11.ID_ITCP_CLASSE_MAT_SERV  ID_ITCP_CLASSE_MAT_SERV,
	a12.ID_ITCP_CLASSE_MAT_SERV_EDIT  DS_ITCP_CLASSE_MAT_SERV,
	a12.DS_ITCP_CLASSE_MAT_SERV  DS_ITCP_CLASSE_MAT_SERV0,
	a11.ID_ITCP_PADRAO_DESC_MAT  ID_ITCP_PADRAO_DESC_MAT,
	a17.DS_ITCP_PADRAO_DESC_MAT  DS_ITCP_PADRAO_DESC_MAT,
--	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
	length(a17.DS_ITCP_PADRAO_DESC_MAT),
	a11.ID_ITCP_MATERIAL_SERVICO  ID_ITCP_MATERIAL_SERVICO,
	a11.DS_ITCP_MATERIAL_SERVICO  DS_ITCP_MATERIAL_SERVICO,
--	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_MATERIAL_SERVICO0,
--	a11.DS_ITCP_MATERIAL_SERVICO  DS_ITCP_MATERIAL_SERVICO0
--	substring(a11.DS_ITCP_MATERIAL_SERVICO, 2, length(a17.DS_ITCP_PADRAO_DESC_MAT)),
	translate(
			substring(a11.DS_ITCP_MATERIAL_SERVICO, 2, 624),
			N'¡¿¬√ƒ≈‡·‚„‰Â????Ê∆«Á????¢©????»… ÀËÈÍÎ??????ÃÕŒœÏÌÓÔ????£—Ò????“”‘’’÷ÿÚÛÙıˆ¯????Æäö??ﬂ??Ÿ⁄€‹˘˙˚¸????µ◊•üˇ˝›éû????-', 
			N'aaaaaaaaaaaaaaaaaaccccccccddddeeeeeeeeeeeeeeiiiiiiiiiilllnnnnnooooooooooooooooorrsssssttuuuuuuuuuuuuuxyyyyyzzzzzz ')
from	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a11
	join	Siasg_DW_VBL.D_ITCP_CLASSE_MAT_SERV	a12
	  on 	(a11.ID_ITCP_CLASSE_MAT_SERV = a12.ID_ITCP_CLASSE_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_SIT_ATUAL_MAT_SERV	a13
	  on 	(a11.ID_ITCP_SIT_ATUAL_MAT_SERV = a13.ID_ITCP_SIT_ATUAL_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_TP_MATERIAL_SERVICO	a14
	  on 	(a11.ID_ITCP_TP_MATERIAL_SERVICO = a14.ID_ITCP_TP_MATERIAL_SERVICO)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_MATERIAL	a15
	  on 	(a11.ID_ITCP_GRUPO_MATERIAL = a15.ID_ITCP_GRUPO_MATERIAL)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_SERVICO	a16
	  on 	(a11.ID_ITCP_GRUPO_SERVICO = a16.ID_ITCP_GRUPO_SERVICO)
	join	Siasg_DW_VBL.D_ITCP_PADRAO_DESC_MAT	a17
	  on 	(a11.ID_ITCP_PADRAO_DESC_MAT = a17.ID_ITCP_PADRAO_DESC_MAT)
where	a11.ID_ITCP_SIT_ATUAL_MAT_SERV in (1)
--	and SUBSTRING(a11.DS_ITCP_MATERIAL_SERVICO, 1, LENGTH(a17.DS_ITCP_PADRAO_DESC_MAT)) = a17.DS_ITCP_PADRAO_DESC_MAT
--	and substring(a11.DS_ITCP_MATERIAL_SERVICO, 2, length(a17.DS_ITCP_PADRAO_DESC_MAT)) = substring(a11.DS_ITCP_MATERIAL_SERVICO, length(a17.DS_ITCP_PADRAO_DESC_MAT)+4, length(a17.DS_ITCP_PADRAO_DESC_MAT))
--	and translate(
--			substring(a11.DS_ITCP_MATERIAL_SERVICO, 2, length(a17.DS_ITCP_PADRAO_DESC_MAT)),
--			N'¡¿¬√ƒ≈‡·‚„‰Â????Ê∆«Á????¢©????»… ÀËÈÍÎ??????ÃÕŒœÏÌÓÔ????£—Ò????“”‘’’÷ÿÚÛÙıˆ¯????Æäö??ﬂ??Ÿ⁄€‹˘˙˚¸????µ◊•üˇ˝›éû????-', 
--			N'aaaaaaaaaaaaaaaaaaccccccccddddeeeeeeeeeeeeeeiiiiiiiiiilllnnnnnooooooooooooooooorrsssssttuuuuuuuuuuuuuxyyyyyzzzzzz ')	=
--		translate(
--			substring(a11.DS_ITCP_MATERIAL_SERVICO, 4+length(a17.DS_ITCP_PADRAO_DESC_MAT), length(a17.DS_ITCP_PADRAO_DESC_MAT)),
--			N'¡¿¬√ƒ≈‡·‚„‰Â????Ê∆«Á????¢©????»… ÀËÈÍÎ??????ÃÕŒœÏÌÓÔ????£—Ò????“”‘’’÷ÿÚÛÙıˆ¯????Æäö??ﬂ??Ÿ⁄€‹˘˙˚¸????µ◊•üˇ˝›éû????-', 
--			N'aaaaaaaaaaaaaaaaaaccccccccddddeeeeeeeeeeeeeeiiiiiiiiiilllnnnnnooooooooooooooooorrsssssttuuuuuuuuuuuuuxyyyyyzzzzzz ')
;

select
--	a11.ID_ITCP_SIT_ATUAL_MAT_SERV  ID_ITCP_SIT_ATUAL_MAT_SERV,
	a13.DS_ITCP_SIT_ATUAL_MAT_SERV  SIT_ATUAL_MAT_SERV,
	a11.ID_ITCP_TP_MATERIAL_SERVICO||' - '||a14.DS_ITCP_TP_MATERIAL_SERVICO  TP_MATERIAL_SERVICO,
	REPLACE(a11.ID_ITCP_GRUPO_MATERIAL||' - '||a15.DS_ITCP_GRUPO_MATERIAL, '-9 - ', '')  GRUPO_MATERIAL,
	REPLACE(a11.ID_ITCP_GRUPO_SERVICO||' - '||a16.DS_ITCP_GRUPO_SERVICO, '-9 - ', '')  GRUPO_SERVICO,
--	a11.ID_ITCP_CLASSE_MAT_SERV  ID_ITCP_CLASSE_MAT_SERV,
	a12.ID_ITCP_CLASSE_MAT_SERV_EDIT||' - '||a12.DS_ITCP_CLASSE_MAT_SERV  CLASSE_MAT_SERV,
	a11.ID_ITCP_PADRAO_DESC_MAT||' - '||a17.DS_ITCP_PADRAO_DESC_MAT  PADRAO_DESC_MAT,
--	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
	a11.ID_ITCP_MATERIAL_SERVICO||' - '||a11.DS_ITCP_MATERIAL_SERVICO  MATERIAL_SERVICO
--	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_MATERIAL_SERVICO0,
--	a11.DS_ITCP_MATERIAL_SERVICO  DS_ITCP_MATERIAL_SERVICO0
from	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a11
	join	Siasg_DW_VBL.D_ITCP_CLASSE_MAT_SERV	a12
	  on 	(a11.ID_ITCP_CLASSE_MAT_SERV = a12.ID_ITCP_CLASSE_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_SIT_ATUAL_MAT_SERV	a13
	  on 	(a11.ID_ITCP_SIT_ATUAL_MAT_SERV = a13.ID_ITCP_SIT_ATUAL_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_TP_MATERIAL_SERVICO	a14
	  on 	(a11.ID_ITCP_TP_MATERIAL_SERVICO = a14.ID_ITCP_TP_MATERIAL_SERVICO)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_MATERIAL	a15
	  on 	(a11.ID_ITCP_GRUPO_MATERIAL = a15.ID_ITCP_GRUPO_MATERIAL)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_SERVICO	a16
	  on 	(a11.ID_ITCP_GRUPO_SERVICO = a16.ID_ITCP_GRUPO_SERVICO)
	join	Siasg_DW_VBL.D_ITCP_PADRAO_DESC_MAT	a17
	  on 	(a11.ID_ITCP_PADRAO_DESC_MAT = a17.ID_ITCP_PADRAO_DESC_MAT)
where	a11.ID_ITCP_SIT_ATUAL_MAT_SERV in (1)
	and SUBSTRING(a17.DS_ITCP_PADRAO_DESC_MAT, 1, LENGTH(a11.DS_ITCP_MATERIAL_SERVICO)) = a17.DS_ITCP_PADRAO_DESC_MAT
	and translate(substring(LENGTH(a11.DS_ITCP_MATERIAL_SERVICO)
			N'',
			N'¡¿¬√ƒ≈‡·‚„‰Â????Ê∆«Á????¢©????»… ÀËÈÍÎ??????ÃÕŒœÏÌÓÔ????£—Ò????“”‘’’÷ÿÚÛÙıˆ¯????Æäö??ﬂ??Ÿ⁄€‹˘˙˚¸????µ◊•üˇ˝›éû????', 
			N'aaaaaaaaaaaaaaaaaaccccccccddddeeeeeeeeeeeeeeiiiiiiiiiilllnnnnnooooooooooooooooorrsssssttuuuuuuuuuuuuuxyyyyyzzzzzz')
;