SELECT
    SEM.GR_EMPENHO_MATERIAL_UNIDADE
,   SUBSTR(SEM.GR_EMPENHO_MATERIAL_UNIDADE,0,21) AS GR_EMPENHO
,   SUBSTR(SEM.GR_UASG_PROC_COMPRA_ITEM,0,6) AS UASG_COMPRA
,   SUBSTR(SEM.GR_EMPENHO_MATERIAL_UNIDADE,0,6) AS UASG_EMPENHO
,   EM.IT_IN_TIPO_UASG_EMPENHO AS TIPO_DA_UASG
,   SUBSTR(EM.GR_EMPENHO_SIAFI,12,10) AS N_EMPENHO
,   EM.IT_DA_EMISSAO AS EMISSAO
,   EM.IT_NU_EMPENHO_ORIGINAL AS EMPENHO_OR
,   EM.IT_IN_TIPO_EMPENHO AS TIPO_EMPENHO
,   SEM.GR_UASG_PROC_COMPRA_ITEM
,   SEM.GR_UASG_PROC_COMPRA_ITEM||SUBSTR(SEM.GR_EMPENHO_MATERIAL_UNIDADE,0,6) AS COD_ITEM_EMP
,   SEM.IT_QT_ITEM_EMPENHO_SIAFI
FROM   Siasg_oracle_VBL.SIASG_EMPENHO_MATERIAL SEM
INNER JOIN Siasg_oracle_VBL.SIASG_EMPENHO EM
ON SUBSTR(SEM.GR_EMPENHO_MATERIAL_UNIDADE,0,21) =  EM.GR_EMPENHO
WHERE SEM.IT_IN_SITUACAO_EMPENHO =3 AND
SUBSTRING(SEM.GR_UASG_PROC_COMPRA_ITEM, 0, 6)='201057' AND
SUBSTRING(SEM.GR_UASG_PROC_COMPRA_ITEM, 14, 4) = '2018';
----------------------------------------------------------------------
SELECT
    SEM.GR_EMPENHO_MATERIAL_UNIDADE
,   SUBSTR(SEM.GR_EMPENHO_MATERIAL_UNIDADE,0,21) AS GR_EMPENHO
,   SUBSTR(SEM.GR_UASG_PROC_COMPRA_ITEM,0,6) AS UASG_COMPRA
,   SUBSTR(SEM.GR_EMPENHO_MATERIAL_UNIDADE,0,6) AS UASG_EMPENHO
,   EM.IT_IN_TIPO_UASG_EMPENHO AS TIPO_DA_UASG
,   SUBSTR(EM.GR_EMPENHO_SIAFI,12,10) AS N_EMPENHO
,   EM.IT_DA_EMISSAO AS EMISSAO
,   EM.IT_NU_EMPENHO_ORIGINAL AS EMPENHO_OR
,   EM.IT_IN_TIPO_EMPENHO AS TIPO_EMPENHO
,   SEM.GR_UASG_PROC_COMPRA_ITEM
,   SEM.GR_UASG_PROC_COMPRA_ITEM||SUBSTR(SEM.GR_EMPENHO_MATERIAL_UNIDADE,0,6) AS COD_ITEM_EMP
,   SEM.IT_QT_ITEM_EMPENHO_SIAFI
FROM   Siasg_oracle_VBL.SIASG_EMPENHO_MATERIAL SEM
INNER JOIN Siasg_oracle_VBL.SIASG_EMPENHO EM
ON SUBSTR(SEM.GR_EMPENHO_MATERIAL_UNIDADE,0,21) =  EM.GR_EMPENHO
WHERE GR_EMPENHO_SIAFI IN ('130024000012020800471');