with ZZTNWYODRQHSP000  as (
select	
	a14.ID_ITCP_CLASSE_MAT_SERV  		ID_ITCP_CLASSE_MAT_SERV,
	sum(a11.QT_FORNECEDOR_COMPRA)  		WJXBFS1,
	sum(a11.VL_PRECO_TOTAL_HOMOLOG)  	WJXBFS2
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR				a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA				a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA					a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a14
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a14.ID_ITCP_TP_COD_MAT_SERV)
where	(1=1
	 and a14.ID_ITCP_TP_MATERIAL_SERVICO in (1)
	-- and a14.ID_ITCP_SIT_ATUAL_MAT_SERV in (1)
	-- and a13.ID_DT_ANO in (2021)
 )
group by	a14.ID_ITCP_CLASSE_MAT_SERV 
), ZZTB0KGF1P5SP001  as (
select	
	a14.ID_ITCP_CLASSE_MAT_SERV  	ID_ITCP_CLASSE_MAT_SERV,
	sum(a11.QT_ITCP_ITEM_COMPRAS)  	WJXBFS1
from	Siasg_DW_VBL.F_ITEM_COMPRA					a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA				a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA					a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a14
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a14.ID_ITCP_TP_COD_MAT_SERV)
where	(1=1
	 and a14.ID_ITCP_TP_MATERIAL_SERVICO in (1)
--	 and a14.ID_ITCP_SIT_ATUAL_MAT_SERV in (1)
--	 and a13.ID_DT_ANO in (2021)
 )
group by	a14.ID_ITCP_CLASSE_MAT_SERV 
)
select	
	cast(a13.ID_ITCP_GRUPO_MATERIAL as integer) 		ID_ITCP_GRUPO_MATERIAL,
	cast(a13.ID_ITCP_CLASSE_MAT_SERV_EDIT as integer) 	ID_ITCP_CLASSE_MAT_SERV,
	a14.DS_ITCP_GRUPO_MATERIAL  						DS_ITCP_GRUPO_MATERIAL,
	a13.DS_ITCP_CLASSE_MAT_SERV  						DS_ITCP_CLASSE_MAT_SERV,
	pa11.WJXBFS2  										VL_PRECO_TOTAL_HOMOLOG, -- WJXBFS3
	pa11.WJXBFS1  										QT_FORNECEDOR_COMPRA, -- WJXBFS1
	pa12.WJXBFS1  										QT_ITCP_ITEM_COMPRAS, -- WJXBFS2
	round(pa11.WJXBFS1/pa12.WJXBFS1,2)					MD_FORNEC_POR_CLASSE
from	ZZTNWYODRQHSP000							pa11
	join	ZZTB0KGF1P5SP001						pa12
	  on 	(pa11.ID_ITCP_CLASSE_MAT_SERV = pa12.ID_ITCP_CLASSE_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_CLASSE_MAT_SERV		a13
	  on 	(pa11.ID_ITCP_CLASSE_MAT_SERV = a13.ID_ITCP_CLASSE_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_MATERIAL		a14
	  on 	(a13.ID_ITCP_GRUPO_MATERIAL = a14.ID_ITCP_GRUPO_MATERIAL)
order by	a13.ID_ITCP_GRUPO_MATERIAL, a13.DS_ITCP_CLASSE_MAT_SERV
;