with ZZT5WFKIYV9MQ000  as (
select	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a12
	  on 	(a11.ID_CMPR_COMPRA = a12.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a13
	  on 	(a12.DT_CMPR_RESULTADO_COMPRA = a13.ID_DT_DATA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a14
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a14.ID_ITCP_TP_COD_MAT_SERV)
where	(a13.ID_DT_ANO in (2019, 2020, 2021, 2022, 2023) and a14.ID_ITCP_TP_MATERIAL_SERVICO in (1))
group by	a11.ID_ITCP_TP_COD_MAT_SERV
having	sum(a11.VL_PRECO_TOTAL_HOMOLOG) > 0 
)
, ZZTITE8JGIJSP001  as (
select	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
	sum(a11.QT_ITCP_ITEM_COMPRAS)  QT_ITCP_ITEM_COMPRAS, -- WJXBFS1
	sum(a11.QT_ITCP_SOLICITADA) QT_ITCP_SOLICITADA -- WJXBFS2
from	Siasg_DW_VBL.F_ITEM_COMPRA	a11
	join	ZZT5WFKIYV9MQ000	pa12
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = pa12.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a13
	  on 	(a11.ID_CMPR_COMPRA = a13.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a14
	  on 	(a13.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a15
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a15.ID_ITCP_TP_COD_MAT_SERV)
where	(a14.ID_DT_ANO in (2019, 2020, 2021, 2022, 2023) and a15.ID_ITCP_TP_MATERIAL_SERVICO in (1))
group by	a11.ID_ITCP_TP_COD_MAT_SERV 
)
, ZZTN8SG9QQTSP002  as (
select	a11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
	sum(a11.VL_PRECO_TOTAL_HOMOLOG)  VL_PRECO_TOTAL_HOMOLOG -- WJXBFS1
from	Siasg_DW_VBL.F_ITEM_FORNECEDOR	a11
	join	ZZT5WFKIYV9MQ000	pa12
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = pa12.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_CMPR_COMPRA	a13
	  on 	(a11.ID_CMPR_COMPRA = a13.ID_CMPR_COMPRA)
	join	Siasg_DW_VBL.D_DT_DATA	a14
	  on 	(a13.DT_CMPR_RESULTADO_COMPRA = a14.ID_DT_DATA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a15
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a15.ID_ITCP_TP_COD_MAT_SERV)
where	(a14.ID_DT_ANO in (2019, 2020, 2021, 2022, 2023) and a15.ID_ITCP_TP_MATERIAL_SERVICO in (1))
group by	a11.ID_ITCP_TP_COD_MAT_SERV 
)
select
	a13.ID_ITCP_GRUPO_MATERIAL  ID_ITCP_GRUPO_MATERIAL,
	a16.DS_ITCP_GRUPO_MATERIAL  DS_ITCP_GRUPO_MATERIAL,
--	a13.ID_ITCP_CLASSE_MAT_SERV  ID_ITCP_CLASSE_MAT_SERV,
	a14.ID_ITCP_CLASSE_MAT_SERV_EDIT  ID_ITCP_CLASSE_MAT_SERV,
	a14.DS_ITCP_CLASSE_MAT_SERV  DS_ITCP_CLASSE_MAT_SERV,
	CAST(a13.ID_ITCP_PADRAO_DESC_MAT AS INTEGER)  ID_ITCP_PADRAO_DESC_MAT,
	a15.DS_ITCP_PADRAO_DESC_MAT  DS_ITCP_PADRAO_DESC_MAT,
--	pa11.ID_ITCP_TP_COD_MAT_SERV  ID_ITCP_TP_COD_MAT_SERV,
	a13.ID_ITCP_MATERIAL_SERVICO  ID_ITCP_MATERIAL_SERVICO,
	a13.DS_ITCP_MATERIAL_SERVICO  DS_ITCP_MATERIAL_SERVICO,
	pa11.QT_ITCP_ITEM_COMPRAS  QT_ITCP_ITEM_COMPRAS, -- WJXBFS1
	pa11.QT_ITCP_SOLICITADA  QT_ITCP_SOLICITADA, -- WJXBFS2
	pa12.VL_PRECO_TOTAL_HOMOLOG  VL_PRECO_TOTAL_HOMOLOG -- WJXBFS3
from	ZZTITE8JGIJSP001	pa11
	join	ZZTN8SG9QQTSP002	pa12
	  on 	(pa11.ID_ITCP_TP_COD_MAT_SERV = pa12.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a13
	  on 	(pa11.ID_ITCP_TP_COD_MAT_SERV = a13.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_CLASSE_MAT_SERV	a14
	  on 	(a13.ID_ITCP_CLASSE_MAT_SERV = a14.ID_ITCP_CLASSE_MAT_SERV)
	join	Siasg_DW_VBL.D_ITCP_PADRAO_DESC_MAT	a15
	  on 	(a13.ID_ITCP_PADRAO_DESC_MAT = a15.ID_ITCP_PADRAO_DESC_MAT)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_MATERIAL	a16
	  on 	(a13.ID_ITCP_GRUPO_MATERIAL = a16.ID_ITCP_GRUPO_MATERIAL)
order by
--	QT_ITCP_ITEM_COMPRAS desc
--	QT_ITCP_SOLICITADA desc
	VL_PRECO_TOTAL_HOMOLOG desc
limit 1000
;