-- Empenhos por Grupo Material

select	
	a13.ID_ITCP_GRUPO_MATERIAL  ID_ITCP_GRUPO_MATERIAL,
	a15.DS_ITCP_GRUPO_MATERIAL  DS_ITCP_GRUPO_MATERIAL,
	a12.ID_DT_ANO  ID_DT_ANO,
	a14.DS_DT_ANO  DS_DT_ANO,
	sum(a11.VL_ITEP_EMPENHADO)  WJXBFS1
from	Siasg_DW_VBL.F_ITEM_EMPENHO	a11
	join	Siasg_DW_VBL.D_DT_DATA	a12
	  on 	(a11.DT_EMPN_EMISSAO_EMPENHO = a12.ID_DT_DATA)
	join	Siasg_DW_VBL.D_ITCP_MATERIAL_SERVICO	a13
	  on 	(a11.ID_ITCP_TP_COD_MAT_SERV = a13.ID_ITCP_TP_COD_MAT_SERV)
	join	Siasg_DW_VBL.D_DT_ANO	a14
	  on 	(a12.ID_DT_ANO = a14.ID_DT_ANO)
	join	Siasg_DW_VBL.D_ITCP_GRUPO_MATERIAL	a15
	  on 	(a13.ID_ITCP_GRUPO_MATERIAL = a15.ID_ITCP_GRUPO_MATERIAL)
where	a12.ID_DT_ANO in (2017, 2018, 2019, 2020)
group by	a13.ID_ITCP_GRUPO_MATERIAL,
	a15.DS_ITCP_GRUPO_MATERIAL,
	a12.ID_DT_ANO,
	a14.DS_DT_ANO
;