SELECT *
FROM Siasg_DW_VBL.D_EMPN_PLACA_INDICADORES aa
	inner join (SELECT * from Siasg_DW_VBL.D_EMPN_ESPECIE_EMPENHO bb) bb
		on bb.ID_EMPN_ESPECIE_EMPENHO = aa.ID_EMPN_ESPECIE_EMPENHO
 	inner join Siasg_DW_VBL.F_EMPENHO cc
		on cc.ID_EMPN_PLACA_INDICADORES = aa.ID_EMPN_PLACA_INDICADORES
 where bb.ID_EMPN_ESPECIE_EMPENHO in (3)
 
	  
------------------------------------------------------------- APNAS ANULA E REFOR
	  
select	
	a13.ID_UNDD_ORGAO_SUP  ID_UNDD_ORGAO_SUP,
	a18.DS_UNDD_ORGAO_SUP  DS_UNDD_ORGAO_SUP,
	a15.ID_UNDD_ORGAO  ID_UNDD_ORGAO,
	a19.DS_UNDD_ORGAO  DS_UNDD_ORGAO,
	a14.ID_EMPN_ESPECIE_EMPENHO  ID_EMPN_ESPECIE_EMPENHO,
	a17.DS_EMPN_ESPECIE_EMPENHO  DS_EMPN_ESPECIE_EMPENHO,
	a12.ID_DT_ANO  ID_DT_ANO,
--	a16.DS_DT_ANO  DS_DT_ANO,
	sum(a100.VL_ITEP_EMPENHADO)  		VL_ITEP_EMPENHADO,
	sum(a11.VL_EMPN_EMP_ANULACAO)  		VL_EMPN_EMP_ANULACAO,
	sum(a11.VL_EMPN_EMP_REFORCO)  		VL_EMPN_EMP_REFORCO
from	Siasg_DW_VBL.F_EMPENHO	a11
	join	Siasg_DW_VBL.D_DT_DATA	a12
	  on 	(a11.DT_EMPN_CONTAB_EMPENHO = a12.ID_DT_DATA)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a13
	  on 	(a11.ID_UNDD_UG_RESP_EMPENHO = a13.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_EMPN_PLACA_INDICADORES	a14
	  on 	(a11.ID_EMPN_PLACA_INDICADORES = a14.ID_EMPN_PLACA_INDICADORES)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a15
	  on 	(a11.ID_UNDD_EMITENTE_EMPENHO = a15.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_DT_ANO	a16
	  on 	(a12.ID_DT_ANO = a16.ID_DT_ANO)
	join	Siasg_DW_VBL.D_EMPN_ESPECIE_EMPENHO	a17
	  on 	(a14.ID_EMPN_ESPECIE_EMPENHO = a17.ID_EMPN_ESPECIE_EMPENHO)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_SUP	a18
	  on 	(a13.ID_UNDD_ORGAO_SUP = a18.ID_UNDD_ORGAO_SUP)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a19
	  on 	(a15.ID_UNDD_ORGAO = a19.ID_UNDD_ORGAO)
	join	(
			select
				a14.ID_UNDD_ORGAO_SUP  ID_UNDD_ORGAO_SUP,
				a18.DS_UNDD_ORGAO_SUP  DS_UNDD_ORGAO_SUP,
				a15.ID_UNDD_ORGAO  ID_UNDD_ORGAO,
				a19.DS_UNDD_ORGAO  DS_UNDD_ORGAO,
--				a13.ID_EMPN_ESPECIE_EMPENHO  ID_EMPN_ESPECIE_EMPENHO,
--				a17.DS_EMPN_ESPECIE_EMPENHO  DS_EMPN_ESPECIE_EMPENHO,
				a12.ID_DT_ANO  ID_DT_ANO,
				a16.DS_DT_ANO  DS_DT_ANO,
				sum(a11.VL_ITEP_EMPENHADO)  VL_ITEP_EMPENHADO
			from	Siasg_DW_VBL.F_ITEM_EMPENHO	a11
				join	Siasg_DW_VBL.D_DT_DATA	a12
				  on 	(a11.DT_EMPN_CONTAB_EMPENHO = a12.ID_DT_DATA)
				join	Siasg_DW_VBL.D_EMPN_PLACA_INDICADORES	a13
				  on 	(a11.ID_EMPN_PLACA_INDICADORES = a13.ID_EMPN_PLACA_INDICADORES)
				join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
				  on 	(a11.ID_UNDD_UG_RESP_EMPENHO = a14.ID_UNDD_UNIDADE)
				join	Siasg_DW_VBL.D_UNDD_UNIDADE	a15
				  on 	(a11.ID_UNDD_EMITENTE_EMPENHO = a15.ID_UNDD_UNIDADE)
				join	Siasg_DW_VBL.D_DT_ANO	a16
				  on 	(a12.ID_DT_ANO = a16.ID_DT_ANO)
				join	Siasg_DW_VBL.D_EMPN_ESPECIE_EMPENHO	a17
				  on 	(a13.ID_EMPN_ESPECIE_EMPENHO = a17.ID_EMPN_ESPECIE_EMPENHO)
				join	Siasg_DW_VBL.D_UNDD_ORGAO_SUP	a18
				  on 	(a14.ID_UNDD_ORGAO_SUP = a18.ID_UNDD_ORGAO_SUP)
				join	Siasg_DW_VBL.D_UNDD_ORGAO	a19
				  on 	(a15.ID_UNDD_ORGAO = a19.ID_UNDD_ORGAO)
			where	a12.ID_DT_ANO in (2020)
			group by	
				a14.ID_UNDD_ORGAO_SUP,
				a18.DS_UNDD_ORGAO_SUP,
				a15.ID_UNDD_ORGAO,
				a19.DS_UNDD_ORGAO,
				a13.ID_EMPN_ESPECIE_EMPENHO,
				a17.DS_EMPN_ESPECIE_EMPENHO,
				a12.ID_DT_ANO,
				a16.DS_DT_ANO
				) a100 ON a100.ID_UNDD_ORGAO_SUP = a13.ID_UNDD_ORGAO_SUP AND a100.ID_UNDD_ORGAO = a15.ID_UNDD_ORGAO
where	
	(a12.ID_DT_ANO in (2020)
 	and a13.ID_UNDD_ESFERA in (3))
group by	
	a13.ID_UNDD_ORGAO_SUP,
	a18.DS_UNDD_ORGAO_SUP,
	a15.ID_UNDD_ORGAO,
	a19.DS_UNDD_ORGAO,
	a14.ID_EMPN_ESPECIE_EMPENHO,
	a17.DS_EMPN_ESPECIE_EMPENHO,
	a12.ID_DT_ANO,
	a16.DS_DT_ANO
	
	
------------------------------------------
	
select
	a14.ID_UNDD_ORGAO_SUP  ID_UNDD_ORGAO_SUP,
	a18.DS_UNDD_ORGAO_SUP  DS_UNDD_ORGAO_SUP,
	a15.ID_UNDD_ORGAO  ID_UNDD_ORGAO,
	a19.DS_UNDD_ORGAO  DS_UNDD_ORGAO,
	a13.ID_EMPN_ESPECIE_EMPENHO  ID_EMPN_ESPECIE_EMPENHO,
	a17.DS_EMPN_ESPECIE_EMPENHO  DS_EMPN_ESPECIE_EMPENHO,
	a12.ID_DT_ANO  ID_DT_ANO,
	a16.DS_DT_ANO  DS_DT_ANO,
	sum(a11.VL_ITEP_EMPENHADO)  WJXBFS1
from	Siasg_DW_VBL.F_ITEM_EMPENHO	a11
	join	Siasg_DW_VBL.D_DT_DATA	a12
	  on 	(a11.DT_EMPN_CONTAB_EMPENHO = a12.ID_DT_DATA)
	join	Siasg_DW_VBL.D_EMPN_PLACA_INDICADORES	a13
	  on 	(a11.ID_EMPN_PLACA_INDICADORES = a13.ID_EMPN_PLACA_INDICADORES)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a14
	  on 	(a11.ID_UNDD_UG_RESP_EMPENHO = a14.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_UNDD_UNIDADE	a15
	  on 	(a11.ID_UNDD_EMITENTE_EMPENHO = a15.ID_UNDD_UNIDADE)
	join	Siasg_DW_VBL.D_DT_ANO	a16
	  on 	(a12.ID_DT_ANO = a16.ID_DT_ANO)
	join	Siasg_DW_VBL.D_EMPN_ESPECIE_EMPENHO	a17
	  on 	(a13.ID_EMPN_ESPECIE_EMPENHO = a17.ID_EMPN_ESPECIE_EMPENHO)
	join	Siasg_DW_VBL.D_UNDD_ORGAO_SUP	a18
	  on 	(a14.ID_UNDD_ORGAO_SUP = a18.ID_UNDD_ORGAO_SUP)
	join	Siasg_DW_VBL.D_UNDD_ORGAO	a19
	  on 	(a15.ID_UNDD_ORGAO = a19.ID_UNDD_ORGAO)
where	a12.ID_DT_ANO in (2020)
group by	a14.ID_UNDD_ORGAO_SUP,
	a18.DS_UNDD_ORGAO_SUP,
	a15.ID_UNDD_ORGAO,
	a19.DS_UNDD_ORGAO,
	a13.ID_EMPN_ESPECIE_EMPENHO,
	a17.DS_EMPN_ESPECIE_EMPENHO,
	a12.ID_DT_ANO,
	a16.DS_DT_ANO