-- Conta IDs diferentes de grupos  

SELECT COUNT(DISTINCT ID_ITCP_IN_COMPRA_GRUPO) CONTA_GRUPOS_DIFERENTES
FROM Siasg_DW_VBL.D_ITCP_ITEM_COMPRA;

-- Conta IDs diferentes de grupos  

SELECT ID_ITCP_IN_COMPRA_GRUPO, CH_ITCP_ITEM_COMPRA
FROM Siasg_DW_VBL.D_ITCP_ITEM_COMPRA
WHERE ID_ITCP_IN_COMPRA_GRUPO >= 100;