SELECT 
	IT_NU_AVISO_LICITACAO			numerodalicitacao,
	IT_CO_UNIDADE_GESTORA			uasg,
	CASE WHEN IT_CO_MODALIDADE_LICITACAO = '01' THEN 'Convite'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '02' THEN 'Tomada de Preços'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '03' THEN 'Concorrência'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '04' THEN 'Concorrência Internacional'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '05' THEN 'Pregão'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '06' THEN 'Dispensa de Licitação'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '07' THEN 'Inexigibilidade de Licitação'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '20' THEN 'Concurso'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '22' THEN 'Tomada de Preços por Técnica e Preço'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '33' THEN 'Concorrência por Técnica e Preço'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '44' THEN 'Concorrência Internacional por Técnica e Preço'
		 WHEN IT_CO_MODALIDADE_LICITACAO = '99' THEN 'Regime Diferenciado de Contratações'
	ELSE CAST(IT_CO_MODALIDADE_LICITACAO AS INTEGER) END modalidadelicitacao,
	IT_DA_TRANSACAO					datacompra,
	IT_NU_CGC_CPF_VENCEDOR			cnpj,
	IT_NO_RAZAO_SOCIAL_VENCEDOR		razaosocial
FROM Siasg_oracle_VBL.SIDEC_RESULTADO_COMPRA r
WHERE IT_NU_CGC_CPF_VENCEDOR IN ('03066528000151','39382692000115','10821252000135','14834948000157','30953791000135','11161040000131')
AND IT_DA_TRANSACAO > '20170401'