SELECT *
FROM Siasg_oracle_VBL.SIDEC_RESULTADO_COMPRA AS c
	JOIN Siasg_oracle_VBL.SIASG_UNIDADE_GESTORA AS u ON c.IT_CO_UNIDADE_GESTORA = u.IT_CO_UNIDADE_GESTORA
WHERE (SUBSTRING(c.IT_NU_AVISO_LICITACAO,-4,4) = '2020' OR SUBSTRING(c.IT_NU_AVISO_LICITACAO,-4,4) = '2019')
	AND u.IT_SG_UF = 'CE'
--	AND (u.IT_NO_MUNICIPIO_UG = 'CASCAVEL' OR
--		 u.IT_NO_MUNICIPIO_UG = 'FORTIM' OR
--		 u.IT_NO_MUNICIPIO_UG = 'ITAPA__')
--;


SELECT DISTINCT u.IT_NO_MUNICIPIO_UG
FROM Siasg_oracle_VBL.SIDEC_RESULTADO_COMPRA AS c
	JOIN Siasg_oracle_VBL.SIASG_UNIDADE_GESTORA AS u ON c.IT_CO_UNIDADE_GESTORA = u.IT_CO_UNIDADE_GESTORA
WHERE SUBSTRING(c.IT_NU_AVISO_LICITACAO,-4,4) = '2020' OR SUBSTRING(c.IT_NU_AVISO_LICITACAO,-4,4) = '2019'
	AND u.IT_SG_UF = CE
--	AND u.IT_NO_MUNICIPIO_UG = ''
;

SELECT *
FROM Siasg_oracle_VBL.SIASG_UNIDADE_GESTORA
WHERE IT_SG_UF = 'CE'
--	AND u.IT_NO_MUNICIPIO_UG = ''
