SELECT
	 LPAD(IT_CO_UNIDADE_GESTORA, 6, 0)||LPAD(IT_CO_MODALIDADE_LICITACAO, 2, 0)||LPAD(IT_NU_AVISO_LICITACAO, 9, 0)||LPAD(IT_NU_ITEM_MATERIAL, 5 ,0) CODITEM
	,LPAD(IT_CO_UNIDADE_GESTORA, 6, 0)||LPAD(IT_CO_MODALIDADE_LICITACAO, 2, 0)||LPAD(IT_NU_AVISO_LICITACAO, 9, 0)||LPAD(IT_NU_ITEM_MATERIAL, 5 ,0) CODCOMPRA
--	,c.ISN_SIDEC_RESULTADO_COMPRA
--	,c.IT_IN_STATUS_REGISTRO
--	,c.IT_CO_USUARIO
	,c.IT_DA_TRANSACAO
--	,c.IT_HO_TRANSACAO
--	,c.IT_CO_NETNAME_TERMINAL
--	,c.IT_SG_UF
	,c.IT_CO_UNIDADE_GESTORA
	,c.IT_CO_MODALIDADE_LICITACAO
	,c.IT_NU_AVISO_LICITACAO
	,c.IT_CO_CONJUNTO_MATERIAIS
	,c.IT_CO_SERVICO
	,c.IT_NU_ITEM_MATERIAL
	,c.IT_TX_DESCRICAO_MATERIAL
	,c.IT_NU_CGC_CPF_VENCEDOR
	,c.IT_VA_PRECO_UNITARIO_ITEM
--	,c.IT_CO_UNIDADE_GESTORA_FATU
--	,c.IT_CO_GESTAO_FATU
--	,c.IT_NU_EMPENHO_FATU
--	,c.IT_DA_PUBLICACAO_DOU
--	,c.IT_CO_ULTIMO_EVENTO
--	,c.IT_CO_RUBRICA_CONTABIL
	,c.IT_VA_ESTIMADO
	,c.IT_NO_RAZAO_SOCIAL_VENCEDOR
	,c.IT_QT_MATERIAL_SERVICO
	,c.IT_NO_UNIDADE_MEDIDA
--	,c.IT_NO_MARCA_MATERIAL
--	,c.IT_IN_PENDENCIA_CISET
	,c.IT_QT_MATERIAL_ALT
--	,c.IT_IN_CONFORMIDADE_CISET
--	,c.IT_CO_USUARIO_CISET
--	,c.IT_DA_TRANSACAO_CISET
--	,c.IT_HO_TRANSACAO_CISET
--	,c.IT_CO_NETNAME_TERMINAL_CISET
--	,c.IT_CO_UNIDADE_GESTORA_CISET
	,c.GR_CONTRATO
--	,c.IT_CO_USUARIO_PRECO
--	,c.IT_DA_TRANSACAO_PRECO
--	,c.IT_HO_TRANSACAO_PRECO
--	,c.IT_CO_NETNAME_TERMINAL_PRECO
--	,c.IT_IN_PENDENCIA_PRECO
--	,c.IT_IN_CONFORMIDADE_PRECO
--	,c.IT_CO_UNIDADE_GESTORA_PRECO
--	,c.IT_SG_UNIDADE_FORNECIMENTO
--	,c.IT_QT_CAPACIDADE
--	,c.IT_SG_UNIDADE_MEDIDA
--	,c.IT_CO_MODALIDADE_PEDIDO
--	,c.IT_NU_AVISO_PEDIDO
	,c.IT_VA_REFERENCIA
--	,c.IT_CO_CPC
	,c.IT_NU_ITEM_REFERENCIA
	,c.IT_CO_SUB_ITEM
	,c.IT_IN_CRITERIO_JULGAMENTO
	,c.IT_VA_REFERENCIA_ITEM
	,c.IT_DA_RESULTADO_ITEM
--	,c.IT_DA_ENVIO_PORTAL
--	,c.IT_IN_ITEM_MEDICAMENTO
--	,c.IT_VA_PERC_MAIOR_DESC
--	,c.IT_NU_GRUPO_COMPRA
--	,c.IT_CO_TIPO_BENEFICIO_ME_EPP
--	,c.IT_QT_ORIGINAL_ITEM
--	,c.IT_NU_ORIGINAL_ITEM
--	,c.IT_VA_PERCENTUAL_SUBCONTRATACAO
--	,c.IT_VA_PERCENTUAL_SUBCONT_MAX
--	,c.IT_IN_DECRETO_7174
	,c.IT_VA_FORNECEDOR_PRINCIPAL
--	,c.IT_NU_GRUPO_COMPRA_FILHO
--	,c.IT_DA_ASSINATURA_ATA
--	,c.IT_DA_INICIO_VIGENCIA_ATA
--	,c.IT_VA_PERC_MARGEM_PREFERENCIA
--	,c.IT_VA_PERC_MARGEM_PREF_ADIC
--	,c.IT_IN_SUBCONTRATACAO
--	,c.IT_VA_PERC_DIFERENCA_LANCE
	,c.IT_IN_HOMOLOGACAO_ITEM_SIASGNET
--	,c.IT_NO_MODELO_VERSAO
	,c.IT_IN_SUSTENTAVEL
--	,c.IT_QT_ADESAO
--	,c.IT_DA_TMS_RESULTADO_ALT
FROM Siasg_oracle_VBL.SIDEC_RESULTADO_COMPRA c
WHERE 1=1
	AND IT_CO_MODALIDADE_LICITACAO = '99' 
	AND IT_CO_SERVICO IN (4553,1619,4545,1406,1414,1422,1430,1740,1767,1775,1783,1791,1805,1848,1856,1910,1929,1937,3425,4774,5622,13455,18376,22896,24481,24490,25445,25453)
--	AND IT_CO_SERVICO IN ('4553','1619','4545','1406','1414','1422','1430','1740','1767','1775','1783','1791','1805','1848','1856','1910','1929','1937','3425','4774','5622','13455','18376','22896','24481','24490','25445','25453')
--	AND IT_NU_CGC_CPF_VENCEDOR IS NOT NULL
--	AND IT_DA_TRANSACAO > '20120000'
--	AND IT_CO_NETNAME_TERMINAL = 'SIASGNET'
ORDER BY 1;