SELECT DISTINCT COD_COMPRA
FROM
	Siasg_oracle_VBL.SIDEC_CONTRATO AS c
	JOIN (
		 SELECT LPAD(IT_CO_UNIDADE_GESTORA,6,0)||LPAD(IT_CO_MODALIDADE_LICITACAO,2,0)||LPAD(IT_NU_AVISO_LICITACAO,9,0) AS COD_COMPRA,
				 IT_CO_UNIDADE_GESTORA,
				 IT_NU_CONTRATO,
				 IT_CO_CONTRATO
		 FROM Siasg_oracle_VBL.SIDEC_CONTRATO
		 ) AS a
		 ON c.IT_CO_UNIDADE_GESTORA = a.IT_CO_UNIDADE_GESTORA AND c.IT_NU_CONTRATO = a.IT_NU_CONTRATO AND c.IT_CO_CONTRATO = a.IT_CO_CONTRATO
WHERE 
	SUBSTRING(c.IT_DA_TERMINO_VIGENCIA,1,4)||'-'||SUBSTRING(c.IT_DA_TERMINO_VIGENCIA,5,2)||'-'||SUBSTRING(c.IT_DA_TERMINO_VIGENCIA,7,2) > CAST(CURDATE() AS STRING)
	AND c.IT_CO_CONTRATO = 50
	AND COD_COMPRA IS NOT NULL;