SELECT
    substring(CC.IT_DA_RESULTADO,1,4) as ANO,
    sum(RC.IT_VA_PRECO_UNITARIO_ITEM)  as VALOR,
    COUNT(CC.SP_COMPRA_COM_LICITACAO) as QTD
FROM SIDEC_COMPRA_COM_LICITACAO CC
INNER JOIN SIDEC_RESULTADO_COMPRA RC
    ON CC.SP_COMPRA_COM_LICITACAO = RC.SP_MODALIDADE_AVISO_LICITACAO
INNER JOIN SIASG_ORGAO ORG
    ON (CC.IT_CO_ORGAO = ORG.IT_CO_ORGAO
        AND ORG.IT_NO_ORGAO IS NOT NULL)
INNER JOIN SIASG_UNIDADE_GESTORA UASG
    ON (CC.IT_CO_UNIDADE_GESTORA = UASG.IT_CO_UNIDADE_GESTORA
        AND UASG.IT_NO_UNIDADE_GESTORA IS NOT NULL)
LEFT JOIN SIASG_SERVICO SERV
    ON SERV.IT_CO_SERVICO = RC.IT_CO_SERVICO   
LEFT JOIN SIASG_CONJUNTO_MATERIAIS CM
    ON CM.IT_CO_CONJUNTO_MATERIAIS = RC.IT_CO_CONJUNTO_MATERIAIS
WHERE CC.IT_CO_MODALIDADE_LICITACAO = '99'
AND substring(CC.IT_DA_RESULTADO,1,4) IN ('2018','2019','2020','2021','2022')
GROUP BY substring(CC.IT_DA_RESULTADO,1,4)
;
SELECT DISTINCT
    substring(CC.IT_DA_RESULTADO,1,4) as ANO,
    sum(RC.IT_VA_PRECO_UNITARIO_ITEM) as VALOR,
--    COUNT(CC.SP_COMPRA_COM_LICITACAO) as QTD,
--    CC.SP_COMPRA_COM_LICITACAO,
    count(RC.SP_MODALIDADE_AVISO_ITEM) QTD_ITENS
FROM SIDEC_COMPRA_COM_LICITACAO CC
	INNER JOIN SIDEC_RESULTADO_COMPRA RC
  	  ON CC.SP_COMPRA_COM_LICITACAO = RC.SP_MODALIDADE_AVISO_LICITACAO
	INNER JOIN SIASG_ORGAO ORG
	   ON (CC.IT_CO_ORGAO = ORG.IT_CO_ORGAO
	   AND ORG.IT_NO_ORGAO IS NOT NULL)
	INNER JOIN SIASG_UNIDADE_GESTORA UASG
	   ON (CC.IT_CO_UNIDADE_GESTORA = UASG.IT_CO_UNIDADE_GESTORA
	   AND UASG.IT_NO_UNIDADE_GESTORA IS NOT NULL)
	LEFT JOIN SIASG_SERVICO SERV
	   ON SERV.IT_CO_SERVICO = RC.IT_CO_SERVICO   
	LEFT JOIN SIASG_CONJUNTO_MATERIAIS CM
	   ON CM.IT_CO_CONJUNTO_MATERIAIS = RC.IT_CO_CONJUNTO_MATERIAIS
WHERE CC.IT_CO_MODALIDADE_LICITACAO = '99'
AND substring(CC.IT_DA_RESULTADO,1,4) IN ('2018','2019','2020','2021','2022')
GROUP BY CC.SP_COMPRA_COM_LICITACAO 
--	substring(CC.IT_DA_RESULTADO,1,4),
--	CC.SP_COMPRA_COM_LICITACAO -- RC.SP_MODALIDADE_AVISO_ITEM
HAVING sum(RC.IT_VA_PRECO_UNITARIO_ITEM) > 39000000
;
SELECT
    CC.SP_COMPRA_COM_LICITACAO,
    substring(CC.IT_DA_RESULTADO,1,4) as ANO,
    sum(RC.IT_VA_PRECO_UNITARIO_ITEM * CAST(IT_QT_MATERIAL_ALT AS INTEGER))  as VALOR_TOTAL
    --COUNT(CC.SP_COMPRA_COM_LICITACAO) as QTD
FROM SIDEC_COMPRA_COM_LICITACAO CC
INNER JOIN SIDEC_RESULTADO_COMPRA RC
    ON CC.SP_COMPRA_COM_LICITACAO = RC.SP_MODALIDADE_AVISO_LICITACAO
INNER JOIN SIASG_ORGAO ORG
    ON (CC.IT_CO_ORGAO = ORG.IT_CO_ORGAO
        AND ORG.IT_NO_ORGAO IS NOT NULL)
INNER JOIN SIASG_UNIDADE_GESTORA UASG
    ON (CC.IT_CO_UNIDADE_GESTORA = UASG.IT_CO_UNIDADE_GESTORA
        AND UASG.IT_NO_UNIDADE_GESTORA IS NOT NULL)
LEFT JOIN SIASG_SERVICO SERV
    ON SERV.IT_CO_SERVICO = RC.IT_CO_SERVICO   
LEFT JOIN SIASG_CONJUNTO_MATERIAIS CM
    ON CM.IT_CO_CONJUNTO_MATERIAIS = RC.IT_CO_CONJUNTO_MATERIAIS
WHERE CC.IT_CO_MODALIDADE_LICITACAO = '99' AND
RC.IT_VA_PRECO_UNITARIO_ITEM > 0
AND substring(CC.IT_DA_RESULTADO,1,4) IN ('2018','2019','2020','2021','2022')
GROUP BY CC.SP_COMPRA_COM_LICITACAO,substring(CC.IT_DA_RESULTADO,1,4)
;