SELECT
	sec.IT_CO_SECAO CO_SECAO,
	sec.IT_NO_SECAO NO_SECAO,
	d.IT_CO_DIVISAO CO_DIVISAO,
	d.IT_NO_DIVISAO NO_DIVISAO,
	g.IT_CO_GRUPO CO_GRUPO,
	g.IT_NO_GRUPO NO_GRUPO,
	c.IT_CO_CLASSE CO_CLASSE,
	c.IT_NO_CLASSE NO_CLASSE,
	sub.IT_CO_SUB_CLASSE CO_SUB_CLASSE,
	sub.IT_NO_SUB_CLASSE NO_SUB_CLASSE,	
	s.IT_CO_CPC CO_CPC,
	s.IT_CO_SERVICO CO_SERVICO,
	s.IT_NO_SERVICO,
	s.IT_NO_SERVICO_ACENT NO_SERVICO,
	s.IT_IN_ITEM_SUSPENSO ITEM_SUSPENSO
FROM Siasg_VBL.SIASG_SERVICO s
	LEFT JOIN Siasg_VBL.SIASG_CATSER_SUB_CLASSE sub ON sub.IT_CO_SUB_CLASSE = SUBSTRING(s.IT_CO_CPC, 1, 5)
	LEFT JOIN Siasg_VBL.SIASG_CATSER_CLASSE c ON c.IT_CO_CLASSE = SUBSTRING(s.IT_CO_CPC, 1, 4)
	JOIN Siasg_VBL.SIASG_CATSER_GRUPO g ON g.IT_CO_GRUPO = SUBSTRING(s.IT_CO_CPC, 1, 3)
	JOIN Siasg_VBL.SIASG_CATSER_DIVISAO d ON d.IT_CO_DIVISAO = SUBSTRING(s.IT_CO_CPC, 1, 2)
	JOIN Siasg_VBL.SIASG_CATSER_SECAO sec ON sec.IT_CO_SECAO = SUBSTRING(s.IT_CO_CPC, 1, 1)
	JOIN Siasg_VBL.SIDEC_RESULTADO_COMPRA compra ON s.IT_CO_SERVICO = compra.IT_CO_SERVICO
WHERE s.IT_IN_STATUS NOT LIKE ('%*%') AND RPAD(s.IT_CO_CPC, 5, 0) BETWEEN '50000' AND '60000' AND compra.IT_DA_RESULTADO_ITEM > 20210000
ORDER BY CO_SECAO,CO_DIVISAO,CO_GRUPO,CO_CLASSE;

