SELECT
	c.ISN_SIDEC_CONTRATO,
	b.IT_NU_EMPENHO_CONTRATO
FROM SIASG_EMPENHO a
	JOIN SIDEC_CONTRATO_GR_EMPENHO b ON (CASE WHEN a.IT_NU_EMPENHO_ORIGINAL IS NULL THEN a.GR_EMPENHO_SIAFI ELSE a.SP_EMPENHO_ORIGINAL END) = TRIM(b.IT_CO_UG_CONTRATO)||TRIM(LPAD(b.IT_CO_GESTAO_CONTRATO, 5, 0))||TRIM(SUBSTRING(b.IT_NU_EMPENHO_CONTRATO, 1, 4))||TRIM(SUBSTRING(b.IT_NU_EMPENHO_CONTRATO, 7, 6)) 
	JOIN SIDEC_CONTRATO c ON c.ISN_SIDEC_CONTRATO = b.ISN_SIDEC_CONTRATO
--WHERE c.ISN_SIDEC_CONTRATO = 1214884
	
SELECT
	CASE WHEN IT_NU_EMPENHO_ORIGINAL IS NULL THEN GR_EMPENHO_SIAFI ELSE IT_NU_EMPENHO_ORIGINAL END
FROM Siasg_Oracle_VBL.SIASG_EMPENHO