select	
	a12.ID_ANO_TRANSACAO_DOC||'-'||lpad(a12.ID_MES_TRANSACAO_DOC, 2, 0)||'-'||lpad(a12.ID_DIA_TRANSACAO_DOC, 2, 0) as DATA_TRANSACAO,
	a11.ID_ANO||'-'||lpad(a11.ID_MES, 2, 0)||'-'||lpad(a11.ID_DIA, 2, 0) as DATA_EMISSAO, 
	a13.ID_DOC_NE  					DOC_NE,
	max(a18.CO_UG)  				CO_UG,
	max(a18.NO_UG)  				NO_UG,
	substring(a13.ID_DOC_NE, 7, 5)	GESTAO,
	a14.ID_LISTA_ITENS_NE  			LISTA_ITENS_NE,
	a14.ID_ITEM  					NUM_ITEM,
	a14.ID_CATEGORIA_ECONOMICA_NADE||a14.ID_GRUPO_DESPESA_NADE||a14.ID_MOAP_NADE||a14.ID_ELEMENTO_DESPESA_NADE||lpad(a14.ID_SUBITEM_NADE, 2, 0)	as SUBELEMENTO_DESPESA,	
	max(a19.NO_NATUREZA_DESPESA_DETA) as SUBELEMENTO_DESPESA_DESC,
	a14.QT_ITEM  					QT_ITEM,
	a14.VA_ITEM  					VA_UNIT_ITEM,
	(a14.QT_ITEM * a14.VA_ITEM)		VA_TOTAL_ITEM, -- Esse cálculo é próprio do campo 'NE Item - Valor Total' no Tesouro Gerencial, não foi criado por mim
	max(a14.DS_ITEM)  				DESCRICAO_ITEM
		--	Colunas eliminadas:
		--	a12.ID_ANO_TRANSACAO_DOC  		ANO_TRANSACAO_DOC,
		--	a12.ID_MES_TRANSACAO_DOC  		MES_TRANSACAO_DOC,
		--	a12.ID_DIA_TRANSACAO_DOC  		DIA_TRANSACAO_DOC,
		--	max(a17.NO_DIA_COMPLETO)		DATA_TRANSACAO,
		--	a11.ID_ANO  					ANO_EMISSAO,
		--	a11.ID_MES  					MES_EMISSAO,
		--	a11.ID_DIA  					DIA_EMISSAO,
		--	max(a11.NO_DIA_COMPLETO)  		DATA_EMISSAO,
		--	a15.ID_UG  						ID_UG,
		--	a14.ID_DOC_NE  					ID_DOC_NE0,
		--	a14.ID_LISTA_ITENS_NE  			ID_LISTA_ITENS_NE,
		--	a14.ID_CATEGORIA_ECONOMICA_NADE	ID_CATEGORIA_ECONOMICA_NADE,
		--	a14.ID_GRUPO_DESPESA_NADE  		ID_GRUPO_DESPESA_NADE,
		--	a14.ID_MOAP_NADE  				ID_MOAP_NADE,
		--	a14.ID_ELEMENTO_DESPESA_NADE  	ID_ELEMENTO_DESPESA_NADE,
		--	a14.ID_SUBITEM_NADE  			ID_SUBITEM_NADE,
from		DWTG_Colunar_VBL.WD_DIA	a11
	join	DWTG_Colunar_VBL.WD_DOCUMENTO	a12
	  on 	(a11.ID_ANO = a12.ID_ANO_EMISSAO_DOC and 
			a11.ID_DIA = a12.ID_DIA_EMISSAO_DOC and 
			a11.ID_MES = a12.ID_MES_EMISSAO_DOC)
	join	DWTG_Colunar_VBL.WD_DOC_RO	a13
	  on 	(a12.ID_DOC_RO = a13.ID_DOC_RO)
	join	DWTG_Colunar_VBL.WD_DOC_NE_ITEM	a14
	  on 	(a13.ID_DOC_NE = a14.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO	a15
	  on 	(a12.ID_ANO_EMISSAO_DOC = a15.ID_ANO and 
			a12.ID_UG = a15.ID_UG)
	join	DWTG_Colunar_VBL.WD_DOC_NE	a16
	  on 	(a13.ID_DOC_NE = a16.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_DIA	a17
	  on 	(a12.ID_ANO_TRANSACAO_DOC = a17.ID_ANO and 
			a12.ID_DIA_TRANSACAO_DOC = a17.ID_DIA and 
			a12.ID_MES_TRANSACAO_DOC = a17.ID_MES)
	join	DWTG_Colunar_VBL.WD_UG	a18
	  on 	(a15.ID_UG = a18.ID_UG)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA_DETA	a19
	  on 	(a14.ID_CATEGORIA_ECONOMICA_NADE = a19.ID_CATEGORIA_ECONOMICA_NADE and 
			a14.ID_ELEMENTO_DESPESA_NADE = a19.ID_ELEMENTO_DESPESA_NADE and 
			a14.ID_GRUPO_DESPESA_NADE = a19.ID_GRUPO_DESPESA_NADE and 
			a14.ID_MOAP_NADE = a19.ID_MOAP_NADE and 
			a14.ID_SUBITEM_NADE = a19.ID_SUBITEM_NADE)
where	(
	a16.ID_ESPECIE_NE in (1) and -- 1:EMPENHO DE DESPESA
	a12.ID_ANO_TRANSACAO_DOC in (2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011)
--	a12.ID_MES_TRANSACAO_DOC in (1)
--	a15.ID_UG in (130024) and
	)
group by	
	a12.ID_ANO_TRANSACAO_DOC,
	a12.ID_MES_TRANSACAO_DOC,
	a12.ID_DIA_TRANSACAO_DOC,
	a11.ID_ANO,
	a11.ID_MES,
	a11.ID_DIA,
	a13.ID_DOC_NE,
	a15.ID_UG,
	a14.ID_LISTA_ITENS_NE,
	a14.ID_ITEM,
	a14.ID_DOC_NE,
	a14.ID_LISTA_ITENS_NE,
	a14.ID_CATEGORIA_ECONOMICA_NADE,
	a14.ID_GRUPO_DESPESA_NADE,
	a14.ID_MOAP_NADE,
	a14.ID_ELEMENTO_DESPESA_NADE,
	a14.ID_SUBITEM_NADE,
	a14.QT_ITEM,
	a14.VA_ITEM,
	(a14.QT_ITEM * a14.VA_ITEM)