--	CODNE | UG | DATA EMISSÃO | DATA LANÇAMENTO RO

SELECT
	ID_DOCUMENTO_LANC 		COD_DOC,
	CO_UG_EMIT_DOC			UASG,
	SUBSTRING(ID_ANO_LANC, 1, 4)||LPAD(ID_MES_LANC, 2, 0)||LPAD(ID_DIA_LANC, 2, 0) DATA_LANCAMENTO
FROM
	DWTG_Colunar_VBL.WF_LANCAMENTO a1
WHERE
	CO_UG_EMIT_DOC = '130018'
	AND a1.ID_TP_DOCUMENTO LIKE 'NE'
	AND a1.ID_ANO_LANC > '2019'
ORDER BY 
	ID_DOCUMENTO_LANC DESC;
	


select	
		a14.ID_DOC_NE  				ID_DOC_NE,
		a11.ID_DOCUMENTO 			ID_DOCUMENTO,
		max(a110.CO_ORGAO_SUPE) 	CO_ORGAO_SUPE,
		max(a110.NO_ORGAO_SUPE) 	NO_ORGAO_SUPE,
		max(a19.CO_ORGAO)  			CO_ORGAO,
		max(a19.NO_ORGAO) 			NO_ORGAO,
		max(a18.CO_UG)  			CO_UG,
		max(a18.NO_UG)  			NO_UG,
		a11.ID_ANO_TRANSACAO_DOC  	TRANSACAO_ANO,
		a11.ID_MES_TRANSACAO_DOC  	TRANSACAO_MES,
		a11.ID_DIA_TRANSACAO_DOC  	TRANSACAO_DIA,
		max(a17.NO_DIA_COMPLETO)  	TRANSACAO_DATA,
		a11.ID_ANO_EMISSAO_DOC  	EMISSAO_ANO,
		a11.ID_MES_EMISSAO_DOC  	EMISSAO_MES,
		a11.ID_DIA_EMISSAO_DOC  	EMISSAO_DIA,
		max(a16.NO_DIA_COMPLETO)  	EMISSAO_DATA
from	DWTG_Colunar_VBL.WD_DOCUMENTO			a11
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO	a12
	  on 	(a11.ID_ANO_EMISSAO_DOC = a12.ID_ANO and 
			a11.ID_UG = a12.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a13
	  on 	(a12.ID_ANO = a13.ID_ANO and 
			a12.ID_ORGAO_UG = a13.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_DOC_RO			a14
	  on 	(a11.ID_DOC_RO = a14.ID_DOC_RO)
	join	DWTG_Colunar_VBL.WD_DOC_NE			a15
	  on 	(a14.ID_DOC_NE = a15.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_DIA				a16
	  on 	(a11.ID_ANO_EMISSAO_DOC = a16.ID_ANO and 
			a11.ID_DIA_EMISSAO_DOC = a16.ID_DIA and 
			a11.ID_MES_EMISSAO_DOC = a16.ID_MES)
	join	DWTG_Colunar_VBL.WD_DIA				a17
	  on 	(a11.ID_ANO_TRANSACAO_DOC = a17.ID_ANO and 
			a11.ID_DIA_TRANSACAO_DOC = a17.ID_DIA and 
			a11.ID_MES_TRANSACAO_DOC = a17.ID_MES)
	join	DWTG_Colunar_VBL.WD_UG				a18
	  on 	(a12.ID_UG = a18.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO			a19
	  on 	(a12.ID_ORGAO_UG = a19.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE		a110
	  on 	(a13.ID_ORGAO_SUPE = a110.ID_ORGAO_SUPE)
where	a15.NO_SISTEMA_ORIGEM in ('COMPRASNET CONTRATOS')
group by	
		a14.ID_DOC_NE,
		a11.ID_DOCUMENTO,
		a13.ID_ORGAO_SUPE,
		a12.ID_ORGAO_UG,
		a12.ID_UG,
		a11.ID_ANO_TRANSACAO_DOC,
		a11.ID_MES_TRANSACAO_DOC,
		a11.ID_DIA_TRANSACAO_DOC,
		a11.ID_ANO_EMISSAO_DOC,
		a11.ID_MES_EMISSAO_DOC,
		a11.ID_DIA_EMISSAO_DOC