select	
	a12.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
	max(a123.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
	a11.ID_ANO_LANC  ID_ANO,
	a11.ID_MES_LANC  ID_MES,
	max(a124.NO_MES)  NO_MES,
	a14.ID_ORGAO_UG  ID_ORGAO,
	max(a113.CO_ORGAO)  CO_ORGAO,
	max(a113.NO_ORGAO)  NO_ORGAO,
	a11.ID_ACAO_PT  ID_ACAO_PT,
	max(a114.NO_ACAO_PT)  NO_ACAO_PT,
	a11.ID_FUNCAO_PT  ID_FUNCAO_PT,
	max(a116.NO_FUNCAO_PT)  ID_FUNCAO_PT0,
	a11.ID_SUBFUNCAO_PT  ID_SUBFUNCAO_PT,
	max(a119.NO_SUBFUNCAO_PT)  NO_SUBFUNCAO_PT,
	a11.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE  ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
	a11.ID_SUBITEM_NADE  ID_SUBITEM_NADE,
	max(a118.CO_NATUREZA_DESPESA_DETA)  CO_NATUREZA_DESPESA_DETA,
	max(a118.NO_NATUREZA_DESPESA_DETA)  NO_NATUREZA_DESPESA_DETA,
	a17.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
	max(a121.CO_ORGAO_MAXI)  CO_ORGAO_MAXI,
	max(a121.NO_ORGAO_MAXI)  NO_ORGAO_MAXI,
	a14.ID_UG  ID_UG_EXEC,
	max(a110.CO_UG)  CO_UG,
	max(a110.NO_UG)  NO_UG,
	a15.ID_ORGAO_UO  ID_ORGAO0,
	max(a112.CO_ORGAO)  CO_ORGAO0,
	max(a112.NO_ORGAO)  NO_ORGAO0,
	a19.ID_ORGAO_MAXI  ID_ORGAO_MAXI0,
	max(a122.CO_ORGAO_MAXI)  CO_ORGAO_MAXI0,
	max(a122.NO_ORGAO_MAXI)  NO_ORGAO_MAXI0,
	a111.ID_UF  ID_UF,
	max(a126.NO_UF)  NO_UF,
	a113.ID_TP_ADMIN_ORGAO  ID_TP_ADMIN_ORGAO,
	max(a127.NO_TP_ADMIN_ORGAO)  NO_TP_ADMIN_ORGAO,
	a13.ID_MODALIDADE_LICITACAO_NE  ID_MODALIDADE_LICITACAO_NE,
	max(a117.CO_MODALIDADE_LICITACAO_NE)  CO_MODALIDADE_LICITACAO_NE,
	max(a117.NO_MODALIDADE_LICITACAO_NE)  NO_MODALIDADE_LICITACAO_NE,
	a11.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE0,
	a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE0,
	a11.ID_MOAP_NADE  ID_MOAP_NADE0,
	a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE0,
	max(a125.CO_NATUREZA_DESPESA)  CO_NATUREZA_DESPESA,
	max(a125.NO_NATUREZA_DESPESA)  NO_NATUREZA_DESPESA,
	a11.ID_ANO_LANC  ID_ANO0,
	a11.ID_MES_LANC  ID_MES0,
	a11.ID_DIA_LANC  ID_DIA,
	max(a115.NO_DIA_COMPLETO)  NO_DIA_COMPLETO,
	a13.ID_TP_NE  ID_TP_NE,
	max(a120.NO_TP_NE)  NO_TP_NE,
	sum((a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO))  MOVIMLQUIDOMOEDAORIGEMITEMINF
from	DWTG_Colunar_VBL.wf_lancamento	a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON	a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
			a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WD_DOC_NE	a13
	  on 	(a11.ID_DOCUMENTO_CCOR = a13.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO	a14
	  on 	(a11.ID_ANO_LANC = a14.ID_ANO and 
			a11.ID_UG_EXEC = a14.ID_UG)
	join	DWTG_Colunar_VBL.WD_UO_EXERCICIO	a15
	  on 	(a11.ID_ANO_LANC = a15.ID_ANO and 
			a11.ID_UO = a15.ID_UO)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a16
	  on 	(a15.ID_ANO = a16.ID_ANO and 
			a15.ID_ORGAO_UO = a16.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO	a17
	  on 	(a16.ID_ANO = a17.ID_ANO and 
			a16.ID_ORGAO_SUPE = a17.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a18
	  on 	(a14.ID_ANO = a18.ID_ANO and 
			a14.ID_ORGAO_UG = a18.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO	a19
	  on 	(a18.ID_ANO = a19.ID_ANO and 
			a18.ID_ORGAO_SUPE = a19.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_UG	a110
	  on 	(a14.ID_UG = a110.ID_UG)
	join	DWTG_Colunar_VBL.WD_MUNICIPIO	a111
	  on 	(a110.ID_MUNICIPIO_UG = a111.ID_MUNICIPIO)
	join	DWTG_Colunar_VBL.WD_ORGAO	a112
	  on 	(a15.ID_ORGAO_UO = a112.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO	a113
	  on 	(a14.ID_ORGAO_UG = a113.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ACAO_PT	a114
	  on 	(a11.ID_ACAO_PT = a114.ID_ACAO_PT)
	join	DWTG_Colunar_VBL.WD_DIA	a115
	  on 	(a11.ID_ANO_LANC = a115.ID_ANO and 
			a11.ID_DIA_LANC = a115.ID_DIA and 
			a11.ID_MES_LANC = a115.ID_MES)
	join	DWTG_Colunar_VBL.WD_FUNCAO_PT	a116
	  on 	(a11.ID_FUNCAO_PT = a116.ID_FUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_MODALIDADE_LICITACAO_NE	a117
	  on 	(a13.ID_MODALIDADE_LICITACAO_NE = a117.ID_MODALIDADE_LICITACAO_NE)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA_DETA	a118
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a118.ID_CATEGORIA_ECONOMICA_NADE and 
			a11.ID_ELEMENTO_DESPESA_NADE = a118.ID_ELEMENTO_DESPESA_NADE and 
			a11.ID_GRUPO_DESPESA_NADE = a118.ID_GRUPO_DESPESA_NADE and 
			a11.ID_MOAP_NADE = a118.ID_MOAP_NADE and 
			a11.ID_SUBITEM_NADE = a118.ID_SUBITEM_NADE)
	join	DWTG_Colunar_VBL.WD_SUBFUNCAO_PT	a119
	  on 	(a11.ID_SUBFUNCAO_PT = a119.ID_SUBFUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_TP_NE	a120
	  on 	(a13.ID_TP_NE = a120.ID_TP_NE)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI	a121
	  on 	(a17.ID_ORGAO_MAXI = a121.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI	a122
	  on 	(a19.ID_ORGAO_MAXI = a122.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO	a123
	  on 	(a12.ID_ITEM_INFORMACAO = a123.ID_ITEM_INFORMACAO)
	join	DWTG_Colunar_VBL.WD_MES_BASE	a124
	  on 	(a11.ID_MES_LANC = a124.ID_MES)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA	a125
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a125.ID_CATEGORIA_ECONOMICA_NADE and 
			a11.ID_ELEMENTO_DESPESA_NADE = a125.ID_ELEMENTO_DESPESA_NADE and 
			a11.ID_GRUPO_DESPESA_NADE = a125.ID_GRUPO_DESPESA_NADE and 
			a11.ID_MOAP_NADE = a125.ID_MOAP_NADE)
	join	DWTG_Colunar_VBL.WD_UF	a126
	  on 	(a111.ID_UF = a126.ID_UF)
	join	DWTG_Colunar_VBL.WD_TP_ADMIN_ORGAO	a127
	  on 	(a113.ID_TP_ADMIN_ORGAO = a127.ID_TP_ADMIN_ORGAO)
where	(a11.ID_CATEGORIA_ECONOMICA_NADE = 3
 and (a11.ID_GRUPO_DESPESA_NADE = 3
 and (a11.ID_MOAP_NADE = 90
 and a11.ID_ELEMENTO_DESPESA_NADE in (37, 39)))
 and a11.ID_CATEGORIA_ECONOMICA_NADE = 3
 and (a11.ID_GRUPO_DESPESA_NADE = 3
 and (a11.ID_MOAP_NADE = 90
 and ((a11.ID_ELEMENTO_DESPESA_NADE = 39
 and a11.ID_SUBITEM_NADE in (10, 79, 43, 5, 16, 78, 77, 2, 47, 58, 17))
 or (a11.ID_ELEMENTO_DESPESA_NADE = 37
 and a11.ID_SUBITEM_NADE in (1, 2, 3)))))
 and a110.ID_ESFERA_ADMIN_UG in (0)
 and a112.ID_PODER_ORGAO in (0)
 and a12.ID_ITEM_INFORMACAO in (421, 423)
 and a19.ID_ORGAO_MAXI in (22000)
 and a14.ID_UG in (130024)
 and a110.ID_MOEDA_UG in (790)
 and a11.ID_ANO_LANC in (2020)
 and a11.ID_MES_LANC in (4, 5))
group by	a12.ID_ITEM_INFORMACAO,
	a11.ID_ANO_LANC,
	a11.ID_MES_LANC,
	a14.ID_ORGAO_UG,
	a11.ID_ACAO_PT,
	a11.ID_FUNCAO_PT,
	a11.ID_SUBFUNCAO_PT,
	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a11.ID_SUBITEM_NADE,
	a17.ID_ORGAO_MAXI,
	a14.ID_UG,
	a15.ID_ORGAO_UO,
	a19.ID_ORGAO_MAXI,
	a111.ID_UF,
	a113.ID_TP_ADMIN_ORGAO,
	a13.ID_MODALIDADE_LICITACAO_NE,
	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a11.ID_ANO_LANC,
	a11.ID_MES_LANC,
	a11.ID_DIA_LANC,
	a13.ID_TP_NE