select	
--	a112.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
--	max(a116.CO_ORGAO_MAXI)  CO_ORGAO_MAXI,
	max(a116.NO_ORGAO_MAXI)  EmitenteOrgaoMaximo,
--	a110.ID_UG  ID_UG,
--	max(a115.CO_UG)  CO_UG,
	max(a115.NO_UG)  EmitenteUG,
--	a16.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE,
--	a16.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
--	a16.ID_MOAP_NADE  ID_MOAP_NADE,
--	a16.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
--	a16.ID_SUBITEM_NADE  ID_SUBITEM_NADE,
--	max(a16.CO_NATUREZA_DESPESA_DETA)  CO_NATUREZA_DESPESA_DETA,
	max(a16.NO_NATUREZA_DESPESA_DETA)  DHItemNaturezaDespesaDet,
	a13.ID_DOC_HABIL  DocumentoHabil,
--	a11.ID_DIA  ID_DIA_ATESTE_DOC_HABIL,
--	a11.ID_MES  ID_MES_ATESTE_DOC_HABIL,
--	a11.ID_ANO  ID_ANO_ATESTE_DOC_HABIL,
	max(a11.NO_DIA_COMPLETO)  DHDataEmissaoDocOrigem,
	a18.VA_DOC  DHValor,
	a15.ID_DOCUMENTO  Documento,
--	a15.ID_ANO_EMISSAO_DOC  ID_ANO_EMISSAO_DOC,
--	a19.ID_ANO_EMISSAO_DOC  ID_ANO,
--	a19.ID_MES_EMISSAO_DOC  ID_MES,
--	a19.ID_DIA_EMISSAO_DOC  ID_DIA,
	max(a114.NO_DIA_COMPLETO)  EmissaoDia,
--	a19.ID_DOCUMENTO  ID_DOCUMENTO0,
--	a19.ID_ANO_EMISSAO_DOC  ID_ANO_EMISSAO_DOC0,
	max(a113.VA_DOC)  DocValor
from	DWTG_Colunar_VBL.WD_DIA	a11
	join	DWTG_Colunar_VBL.WD_DOC_ORIGEM_DOC_HABIL	a13
	  on 	(a11.ID_ANO = a13.ID_ANO_EMISSAO and 
			a11.ID_DIA = a13.ID_DIA_EMISSAO and 
			a11.ID_MES = a13.ID_MES_EMISSAO)
	join	DWTG_Colunar_VBL.WD_COMPROMISSO	a14
	  on 	(a13.ID_DOC_HABIL = a14.ID_DOC_HABIL)
	join	DWTG_Colunar_VBL.WD_COMPROMISSO_DOCUMENTO	a15
	  on 	(a14.ID_COMPROMISSO = a15.ID_COMPROMISSO)
	join	(DWTG_Colunar_VBL.WD_NATUREZA_DESPESA_DETA	a16
	join	DWTG_Colunar_VBL.WD_ITEM_DOC_HABIL	a17
	  on 	(a16.ID_CATEGORIA_ECONOMICA_NADE = a17.ID_CATEGORIA_ECONOMICA_NADE and 
			a16.ID_ELEMENTO_DESPESA_NADE = a17.ID_ELEMENTO_DESPESA_NADE and 
			a16.ID_GRUPO_DESPESA_NADE = a17.ID_GRUPO_DESPESA_NADE and 
			a16.ID_MOAP_NADE = a17.ID_MOAP_NADE and 
			a16.ID_SUBITEM_NADE = a17.ID_SUBITEM_NADE))
	  on 	(a13.ID_DOC_HABIL = a17.ID_DOC_HABIL)
	join	DWTG_Colunar_VBL.WD_DOC_HABIL	a18
	  on 	(a13.ID_DOC_HABIL = a18.ID_DOC_HABIL)
	join	DWTG_Colunar_VBL.WD_DOCUMENTO	a19
	  on 	(a15.ID_ANO_EMISSAO_DOC = a19.ID_ANO_EMISSAO_DOC and 
	a15.ID_DOCUMENTO = a19.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO	a110
	  on 	(a19.ID_ANO_EMISSAO_DOC = a110.ID_ANO and 
			a19.ID_UG = a110.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a111
	  on 	(a110.ID_ANO = a111.ID_ANO and 
			a110.ID_ORGAO_UG = a111.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO	a112
	  on 	(a111.ID_ANO = a112.ID_ANO and 
			a111.ID_ORGAO_SUPE = a112.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WF_DOCUMENTO	a113
	  on 	(a15.ID_ANO_EMISSAO_DOC = a113.ID_ANO_EMISSAO_DOC and 
			a15.ID_DOCUMENTO = a113.ID_DOCUMENTO and 
			a19.ID_ANO_EMISSAO_DOC = a113.ID_ANO_EMISSAO_DOC and 
			a19.ID_DOCUMENTO = a113.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_DIA	a114
	  on 	(a19.ID_ANO_EMISSAO_DOC = a114.ID_ANO and 
			a19.ID_DIA_EMISSAO_DOC = a114.ID_DIA and 
			a19.ID_MES_EMISSAO_DOC = a114.ID_MES)
	join	DWTG_Colunar_VBL.WD_UG	a115
	  on 	(a110.ID_UG = a115.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI	a116
	  on 	(a112.ID_ORGAO_MAXI = a116.ID_ORGAO_MAXI)
where	(a18.ID_ANO_EMISSAO in (2021)
 and a18.ID_TP_DOC_HABIL in ('NP')
 and a19.ID_TP_DOCUMENTO in ('OB')
-- and a110.ID_UG in (130024)
 )
group by	
	a112.ID_ORGAO_MAXI,
	a110.ID_UG,
	a16.ID_CATEGORIA_ECONOMICA_NADE,
	a16.ID_GRUPO_DESPESA_NADE,
	a16.ID_MOAP_NADE,
	a16.ID_ELEMENTO_DESPESA_NADE,
	a16.ID_SUBITEM_NADE,
	a13.ID_DOC_HABIL,
	a11.ID_DIA,
	a11.ID_MES,
	a11.ID_ANO,
	a18.VA_DOC,
	a15.ID_DOCUMENTO,
	a15.ID_ANO_EMISSAO_DOC,
	a19.ID_ANO_EMISSAO_DOC,
	a19.ID_MES_EMISSAO_DOC,
	a19.ID_DIA_EMISSAO_DOC,
	a19.ID_DOCUMENTO,
	a19.ID_ANO_EMISSAO_DOC