select	
--	a12.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
--	max(a123.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
	a14.ID_ORGAO_UG  						ID_ORGAO,
	max(a112.NO_ORGAO)  					NO_ORGAO,
	a11.ID_ACAO_PT  						ID_ACAO_PT,
	max(a113.NO_ACAO_PT)  					NO_ACAO_PT,
	a11.ID_FUNCAO_PT  						ID_FUNCAO_PT,
	max(a115.NO_FUNCAO_PT)  				NO_FUNCAO_PT,
	a11.ID_SUBFUNCAO_PT  					ID_SUBFUNCAO_PT,
	max(a118.NO_SUBFUNCAO_PT)  				NO_SUBFUNCAO_PT,
	a11.ID_CATEGORIA_ECONOMICA_NADE  		ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE  				ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE  						ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE  			ID_ELEMENTO_DESPESA_NADE,
	a11.ID_SUBITEM_NADE  					ID_SUBITEM_NADE,
	max(a117.CO_NATUREZA_DESPESA_DETA)  	CO_NATUREZA_DESPESA_DETA,
	max(a117.NO_NATUREZA_DESPESA_DETA)  	NO_NATUREZA_DESPESA_DETA,
	a14.ID_UG  								ID_UG_EXEC,
	max(a110.NO_UG)  						NO_UG,
	a19.ID_ORGAO_MAXI  						ID_ORGAO_MAXI,
	max(a122.NO_ORGAO_MAXI)  				NO_ORGAO_MAXI,
	a111.ID_UF  							ID_UF,
	max(a126.NO_UF)  						NO_UF,
	a112.ID_PODER_ORGAO  					ID_PODER_ORGAO,
	max(a127.NO_PODER_ORGAO)  				NO_PODER_ORGAO,
	a112.ID_TP_ADMIN_ORGAO  				ID_TP_ADMIN_ORGAO,
	max(a128.NO_TP_ADMIN_ORGAO)  			NO_TP_ADMIN_ORGAO,
	a110.ID_ESFERA_ADMIN_UG  				ID_ESFERA_ADMIN_UG,
	max(a125.NO_ESFERA_ADMIN_UG)  			NO_ESFERA_ADMIN_UG,
	a13.ID_TP_NE  							ID_TP_NE,
	max(a119.NO_TP_NE)  					NO_TP_NE,
	a13.ID_MODALIDADE_LICITACAO_NE  		ID_MODALIDADE_LICITACAO_NE,
	max(a116.NO_MODALIDADE_LICITACAO_NE)	NO_MODALIDADE_LICITACAO_NE,
	a11.ID_ANO_LANC  						ID_ANO,
	a11.ID_MES_LANC  						ID_MES,
	a11.ID_DIA_LANC  						ID_DIA,
	max(a114.NO_DIA_COMPLETO)  				NO_DIA_COMPLETO,
	a17.ID_ORGAO_MAXI  						ID_ORGAO_MAXI_UO,
	max(a121.NO_ORGAO_MAXI)  				NO_ORGAO_MAXI_UO,
	a15.ID_ORGAO_UO  						ID_ORGAO_UO,
	max(a120.NO_ORGAO)  					NO_ORGAO_UO,
	sum((a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO))  DESPESAS_PAGAS
from	
	DWTG_Colunar_VBL.WF_LANCAMENTO							a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON		a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
			a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WD_DOC_NE						a13
	  on 	(a11.ID_DOCUMENTO_CCOR = a13.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO				a14
	  on 	(a11.ID_ANO_LANC = a14.ID_ANO and 
			a11.ID_UG_EXEC = a14.ID_UG)
	join	DWTG_Colunar_VBL.WD_UO_EXERCICIO				a15
	  on 	(a11.ID_ANO_LANC = a15.ID_ANO and 
			a11.ID_UO = a15.ID_UO)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO				a16
	  on 	(a15.ID_ANO = a16.ID_ANO and 
			a15.ID_ORGAO_UO = a16.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO		a17
	  on 	(a16.ID_ANO = a17.ID_ANO and 
			a16.ID_ORGAO_SUPE = a17.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO				a18
	  on 	(a14.ID_ANO = a18.ID_ANO and 
			a14.ID_ORGAO_UG = a18.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO		a19
	  on 	(a18.ID_ANO = a19.ID_ANO and 
			a18.ID_ORGAO_SUPE = a19.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_UG							a110
	  on 	(a14.ID_UG = a110.ID_UG)
	join	DWTG_Colunar_VBL.WD_MUNICIPIO					a111
	  on 	(a110.ID_MUNICIPIO_UG = a111.ID_MUNICIPIO)
	join	DWTG_Colunar_VBL.WD_ORGAO						a112
	  on 	(a14.ID_ORGAO_UG = a112.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ACAO_PT						a113
	  on 	(a11.ID_ACAO_PT = a113.ID_ACAO_PT)
	join	DWTG_Colunar_VBL.WD_DIA							a114
	  on 	(a11.ID_ANO_LANC = a114.ID_ANO and 
			a11.ID_DIA_LANC = a114.ID_DIA and 
			a11.ID_MES_LANC = a114.ID_MES)
	join	DWTG_Colunar_VBL.WD_FUNCAO_PT					a115
	  on 	(a11.ID_FUNCAO_PT = a115.ID_FUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_MODALIDADE_LICITACAO_NE		a116
	  on 	(a13.ID_MODALIDADE_LICITACAO_NE = a116.ID_MODALIDADE_LICITACAO_NE)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA_DETA		a117
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a117.ID_CATEGORIA_ECONOMICA_NADE and 
			a11.ID_ELEMENTO_DESPESA_NADE = a117.ID_ELEMENTO_DESPESA_NADE and 
			a11.ID_GRUPO_DESPESA_NADE = a117.ID_GRUPO_DESPESA_NADE and 
			a11.ID_MOAP_NADE = a117.ID_MOAP_NADE and 
			a11.ID_SUBITEM_NADE = a117.ID_SUBITEM_NADE)
	join	DWTG_Colunar_VBL.WD_SUBFUNCAO_PT				a118
	  on 	(a11.ID_SUBFUNCAO_PT = a118.ID_SUBFUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_TP_NE						a119
	  on 	(a13.ID_TP_NE = a119.ID_TP_NE)
	join	DWTG_Colunar_VBL.WD_ORGAO						a120
	  on 	(a15.ID_ORGAO_UO = a120.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI					a121
	  on 	(a17.ID_ORGAO_MAXI = a121.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI					a122
	  on 	(a19.ID_ORGAO_MAXI = a122.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO	a123
	  on 	(a12.ID_ITEM_INFORMACAO = a123.ID_ITEM_INFORMACAO)
	join	DWTG_Colunar_VBL.WD_MES_BASE					a124
	  on 	(a11.ID_MES_LANC = a124.ID_MES)
	join	DWTG_Colunar_VBL.WD_ESFERA_ADMIN_UG				a125
	  on 	(a110.ID_ESFERA_ADMIN_UG = a125.ID_ESFERA_ADMIN_UG)
	join	DWTG_Colunar_VBL.WD_UF							a126
	  on 	(a111.ID_UF = a126.ID_UF)
	join	DWTG_Colunar_VBL.WD_PODER_ORGAO					a127
	  on 	(a112.ID_PODER_ORGAO = a127.ID_PODER_ORGAO)
	join	DWTG_Colunar_VBL.WD_TP_ADMIN_ORGAO				a128
	  on 	(a112.ID_TP_ADMIN_ORGAO = a128.ID_TP_ADMIN_ORGAO)
where	
	(a11.ID_CATEGORIA_ECONOMICA_NADE = 3
	 and (a11.ID_GRUPO_DESPESA_NADE = 3
	 and (a11.ID_MOAP_NADE = 90
	 and a11.ID_ELEMENTO_DESPESA_NADE in (30, 37, 39)))
	 ----------------------------------------------------------------------
	 and a11.ID_CATEGORIA_ECONOMICA_NADE = 3
	 and (a11.ID_GRUPO_DESPESA_NADE = 3
	 and (a11.ID_MOAP_NADE = 90
	 and ((a11.ID_ELEMENTO_DESPESA_NADE = 37
	 and a11.ID_SUBITEM_NADE in (1, 2, 3))
	 or ((a11.ID_ELEMENTO_DESPESA_NADE = 30 and a11.ID_SUBITEM_NADE = 9)
	 or  (a11.ID_ELEMENTO_DESPESA_NADE = 39 and a11.ID_SUBITEM_NADE=50)))))
	 ----------------------------------------------------------------------
--	 and a110.ID_ESFERA_ADMIN_UG in (0)
--	 and a112.ID_PODER_ORGAO in (0)
--	 and a112.ID_TP_ADMIN_ORGAO in (1, 3, 4)
	 and a12.ID_ITEM_INFORMACAO in (423)
	 and a110.ID_MOEDA_UG in (790)
	 and a11.ID_ANO_LANC in (2015, 2016, 2017, 2018)--, 2019, 2020)
--	 and a11.ID_MES_LANC in (2)
	 and a19.ID_ORGAO_MAXI in (36000, 52000, 25000, 26000, 30000)--, 39000, 24000, 22000))
group by	
	a12.ID_ITEM_INFORMACAO,
	a11.ID_ANO_LANC,
	a11.ID_MES_LANC,
	a14.ID_ORGAO_UG,
	a11.ID_ACAO_PT,
	a11.ID_FUNCAO_PT,
	a11.ID_SUBFUNCAO_PT,
	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a11.ID_SUBITEM_NADE,
	a14.ID_UG,
	a19.ID_ORGAO_MAXI,
	a111.ID_UF,
	a112.ID_PODER_ORGAO,
	a112.ID_TP_ADMIN_ORGAO,
	a110.ID_ESFERA_ADMIN_UG,
	a13.ID_TP_NE,
	a13.ID_MODALIDADE_LICITACAO_NE,
	a11.ID_ANO_LANC,
	a11.ID_MES_LANC,
	a11.ID_DIA_LANC,
	a17.ID_ORGAO_MAXI,
	a15.ID_ORGAO_UO