select
	max(a12.ID_ITEM_INFORMACAO)				ID_ITEM_INFORMACAO,
	max(a11.ID_ANO_LANC)  					ID_ANO,
	max(a13.ID_MES)  						ID_MES,
	max(a18.ID_ORGAO_MAXI)  				ID_ORGAO_MAXI,
	max(a16.ID_ORGAO_UO)  					ID_ORGAO,
	max(a110.ID_ORGAO_MAXI)  				ID_ORGAO_MAXI_UG,
	max(a15.ID_ORGAO_UG)  					ID_ORGAO_UG,
	max(a15.ID_UG)  						ID_UG_EXEC,
	max(a112.ID_UF)  						ID_UF,
	max(a114.ID_TP_ADMIN_ORGAO) 			ID_TP_ADMIN_ORGAO,
	max(a11.ID_FUNCAO_PT)  					ID_FUNCAO_PT,
	max(a11.ID_SUBFUNCAO_PT)  				ID_SUBFUNCAO_PT,
	max(a11.ID_ACAO_PT)  					ID_ACAO_PT,
	max(a124.CO_NATUREZA_DESPESA)  			ID_NATUREZA_DESPESA,
	max(a120.CO_NATUREZA_DESPESA_DETA)		ID_NATUREZA_DESPESA_DETA,
	max(a14.ID_MODALIDADE_LICITACAO_NE)		ID_MODALIDADE_LICITACAO_NE,
	max(a14.ID_TP_NE)						ID_TP_NE,
	max(a117.NO_ITEM_INFORMACAO)  			NO_ITEM_INFORMACAO,
	max(a122.NO_ORGAO_MAXI)  				NO_ORGAO_MAXI,
	max(a114.NO_ORGAO)  					NO_ORGAO,
	max(a123.NO_ORGAO_MAXI)  				NO_ORGAO_MAXI_UG,
	max(a113.NO_ORGAO)  					NO_ORGAO_UG,
	max(a111.NO_UG)  						NO_UG,
	max(a125.NO_UF)  						NO_UF,
	max(a126.NO_TP_ADMIN_ORGAO)  			NO_TP_ADMIN_ORGAO,
	max(a116.NO_FUNCAO_PT)  				NO_FUNCAO_PT,
	max(a121.NO_SUBFUNCAO_PT)  				NO_SUBFUNCAO_PT,
	max(a115.NO_ACAO_PT) 					NO_ACAO_PT,
	max(a124.NO_NATUREZA_DESPESA)  			NO_NATUREZA_DESPESA,
	max(a120.NO_NATUREZA_DESPESA_DETA)  	NO_NATUREZA_DESPESA_DETA,
	max(a118.NO_MODALIDADE_LICITACAO_NE) 	NO_MODALIDADE_LICITACAO_NE,
	max(a127.NO_TP_NE)						NO_TP_NE,
--	sum(case when a12.ID_ITEM_INFORMACAO = 421 then (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) ELSE 0 end) DESPESAS_EMPENHADAS,
--	sum(case when a12.ID_ITEM_INFORMACAO = 423 then (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) ELSE 0 end) DESPESAS_PAGAS
	SUM(CASE WHEN a11.ID_MES_LANC = 1 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES01,
	SUM(CASE WHEN a11.ID_MES_LANC = 2 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES02,
	SUM(CASE WHEN a11.ID_MES_LANC = 3 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES03,
	SUM(CASE WHEN a11.ID_MES_LANC = 4 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES04,
	SUM(CASE WHEN a11.ID_MES_LANC = 5 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES05,
	SUM(CASE WHEN a11.ID_MES_LANC = 6 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES06,
	SUM(CASE WHEN a11.ID_MES_LANC = 7 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES07,
	SUM(CASE WHEN a11.ID_MES_LANC = 8 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES08,
	SUM(CASE WHEN a11.ID_MES_LANC = 9 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES09,
	SUM(CASE WHEN a11.ID_MES_LANC = 10 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES10,
	SUM(CASE WHEN a11.ID_MES_LANC = 11 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES11,
	SUM(CASE WHEN a11.ID_MES_LANC = 12 THEN a11.VA_MOVIMENTO_LIQUIDO END) MES12
from	
	DWTG_Colunar_VBL.wf_lancamento_ep20						a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON		a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
			a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WA_MES_ACUM_SEM_ANO			a13
	  on 	(a11.ID_MES_LANC = a13.ID_MES_ACUM_ANO_MOVIMENTO)
	join	DWTG_Colunar_VBL.WD_DOC_NE						a14
	  on 	(a11.ID_DOCUMENTO_CCOR = a14.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO				a15
	  on 	(a11.ID_ANO_LANC = a15.ID_ANO and 
			a11.ID_UG_EXEC = a15.ID_UG)
	join	DWTG_Colunar_VBL.WD_UO_EXERCICIO				a16
	  on 	(a11.ID_ANO_LANC = a16.ID_ANO and 
			a11.ID_UO = a16.ID_UO)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO				a17
	  on 	(a16.ID_ANO = a17.ID_ANO and 
			a16.ID_ORGAO_UO = a17.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO		a18
	  on 	(a17.ID_ANO = a18.ID_ANO and 
			a17.ID_ORGAO_SUPE = a18.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO				a19
	  on 	(a15.ID_ANO = a19.ID_ANO and 
			a15.ID_ORGAO_UG = a19.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO		a110
	  on 	(a19.ID_ANO = a110.ID_ANO and 
			a19.ID_ORGAO_SUPE = a110.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_UG							a111
	  on 	(a15.ID_UG = a111.ID_UG)
	join	DWTG_Colunar_VBL.WD_MUNICIPIO					a112
	  on 	(a111.ID_MUNICIPIO_UG = a112.ID_MUNICIPIO)
	join	DWTG_Colunar_VBL.WD_ORGAO						a113
	  on 	(a16.ID_ORGAO_UO = a113.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO						a114
	  on 	(a15.ID_ORGAO_UG = a114.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ACAO_PT						a115
	  on 	(a11.ID_ACAO_PT = a115.ID_ACAO_PT)
	join	DWTG_Colunar_VBL.WD_FUNCAO_PT					a116
	  on 	(a11.ID_FUNCAO_PT = a116.ID_FUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO				a117
	  on 	(a12.ID_ITEM_INFORMACAO = a117.ID_ITEM_INFORMACAO)
	join	DWTG_Colunar_VBL.WD_MODALIDADE_LICITACAO_NE		a118
	  on 	(a14.ID_MODALIDADE_LICITACAO_NE = a118.ID_MODALIDADE_LICITACAO_NE)
	join	DWTG_Colunar_VBL.WD_MES_BASE					a119
	  on 	(a13.ID_MES = a119.ID_MES)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA_DETA		a120
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a120.ID_CATEGORIA_ECONOMICA_NADE and 
			a11.ID_ELEMENTO_DESPESA_NADE = a120.ID_ELEMENTO_DESPESA_NADE and 
			a11.ID_GRUPO_DESPESA_NADE = a120.ID_GRUPO_DESPESA_NADE and 
			a11.ID_MOAP_NADE = a120.ID_MOAP_NADE and 
			a11.ID_SUBITEM_NADE = a120.ID_SUBITEM_NADE)
	join	DWTG_Colunar_VBL.WD_SUBFUNCAO_PT				a121
	  on 	(a11.ID_SUBFUNCAO_PT = a121.ID_SUBFUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI					a122
	  on 	(a18.ID_ORGAO_MAXI = a122.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI					a123
	  on 	(a110.ID_ORGAO_MAXI = a123.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA			a124
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a124.ID_CATEGORIA_ECONOMICA_NADE and 
			a11.ID_ELEMENTO_DESPESA_NADE = a124.ID_ELEMENTO_DESPESA_NADE and 
			a11.ID_GRUPO_DESPESA_NADE = a124.ID_GRUPO_DESPESA_NADE and 
			a11.ID_MOAP_NADE = a124.ID_MOAP_NADE)
	join	DWTG_Colunar_VBL.WD_UF							a125
	  on 	(a112.ID_UF = a125.ID_UF)
	join	DWTG_Colunar_VBL.WD_TP_ADMIN_ORGAO				a126
	  on 	(a114.ID_TP_ADMIN_ORGAO = a126.ID_TP_ADMIN_ORGAO)
  	join	DWTG_Colunar_VBL.WD_TP_NE						a127
	  on 	(a14.ID_TP_NE = a127.ID_TP_NE)
where	
	(a11.ID_CATEGORIA_ECONOMICA_NADE = 		3
	 and (a11.ID_GRUPO_DESPESA_NADE = 		3
	 and (a11.ID_MOAP_NADE = 				90
	 and a11.ID_ELEMENTO_DESPESA_NADE in 	(37, 39))) 											-- Natureza da Despesa
	 ----------------------------------------------
	 and a11.ID_CATEGORIA_ECONOMICA_NADE = 	3
	 and (a11.ID_GRUPO_DESPESA_NADE = 		3
	 and (a11.ID_MOAP_NADE = 				90
	 and ((a11.ID_ELEMENTO_DESPESA_NADE = 	39
	 and a11.ID_SUBITEM_NADE in 			(10, 79, 43, 5, 16, 78, 77, 2, 47, 58, 17)) 		-- Subitem da ND 339039
	 or (a11.ID_ELEMENTO_DESPESA_NADE = 	37
	 and a11.ID_SUBITEM_NADE in 			(1, 2, 3))))) 										-- Subitem da ND 339037
	 ----------------------------------------------
	 and a111.ID_ESFERA_ADMIN_UG in 		(0)
	 and a113.ID_PODER_ORGAO in 			(0)
	 and a12.ID_ITEM_INFORMACAO in 			(423)												-- (421, 423)
--	 and a18.ID_ORGAO_MAXI in 				(22000)
--	 and a15.ID_UG in 						(130024)
	 and a11.ID_ACAO_PT in 					(2000)
	 and a14.ID_TP_NE in					(3, 5)
	 and a111.ID_MOEDA_UG in 				(790)
	 and a11.ID_ANO_LANC in 				(2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018)
	 and a13.ID_MES in 						(12)
	 )
group by	
	a12.ID_ITEM_INFORMACAO,
	a11.ID_ANO_LANC,
	a13.ID_MES,
	a15.ID_ORGAO_UG,
	a11.ID_ACAO_PT,
	a11.ID_FUNCAO_PT,
	a11.ID_SUBFUNCAO_PT,
	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a11.ID_SUBITEM_NADE,
	a18.ID_ORGAO_MAXI,
	a15.ID_UG,
	a16.ID_ORGAO_UO,
	a110.ID_ORGAO_MAXI,
	a112.ID_UF,
	a114.ID_TP_ADMIN_ORGAO,
	a14.ID_MODALIDADE_LICITACAO_NE,
	a14.ID_TP_NE,
	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE
