SELECT
	m.NO_MODALIDADE_LICITACAO_NE,
	COUNT(DISTINCT ne.ID_ENTIDADE_FAVO_DOC),
	SUM(nei.VA_ITEM)
FROM DWTG_Colunar_VBL.WD_DOC_NE_ITEM nei
	JOIN DWTG_Colunar_VBL.WD_DOC_NE ne ON ne.ID_DOC_NE = nei.ID_DOC_NE
	JOIN DWTG_Colunar_VBL.WD_MODALIDADE_LICITACAO_NE m ON ne.ID_MODALIDADE_LICITACAO_NE = m.ID_MODALIDADE_LICITACAO_NE
WHERE ne.ID_MODALIDADE_LICITACAO_NE = 9
GROUP BY
	m.NO_MODALIDADE_LICITACAO_NE,
	ne.ID_ENTIDADE_FAVO_DOC