select	
	max(a17.CO_NATUREZA_DESPESA)  		CO_NATUREZA_DESPESA,
--	max(a17.NO_NATUREZA_DESPESA) 		NO_NATUREZA_DESPESA,
--	max(a19.NO_ITEM_INFORMACAO) 		NO_ITEM_INFORMACAO,
	a15.ID_ANO_TRANSACAO_DOC  			ID_ANO,
	a15.ID_MES_TRANSACAO_DOC  			ID_MES,
--	max(a18.SG_MES_COMPLETO)  			SG_MES_COMPLETO,
--	a14.ID_ORGAO_SUPE  					ID_ORGAO_SUPE,
--	max(a16.CO_ORGAO_SUPE)  			CO_ORGAO_SUPE,
	max(a16.NO_ORGAO_SUPE)  			NO_ORGAO_SUPE,
	sum((a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO))  MOVIMLQUIDOMOEDAORIGEMITEMINF
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2010' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2010,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2011' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2011,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2012' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2012,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2013' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2013,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2014' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2014,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2015' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2015,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2016' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2016,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2017' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2017,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2018' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2018,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2019' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2019,
--	SUM(CASE WHEN a15.ID_ANO_TRANSACAO_DOC = '2020' THEN (a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO) END) EMPENHADO2020
from		
			DWTG_Colunar_VBL.WF_LANCAMENTO					a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON		a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
			a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO				a13
	  on 	(a11.ID_ANO_LANC = a13.ID_ANO and 
			a11.ID_UG_EMIT_DOC = a13.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO				a14
	  on 	(a13.ID_ANO = a14.ID_ANO and 
			a13.ID_ORGAO_UG = a14.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_DOCUMENTO					a15
	  on 	(a11.ID_ANO_LANC = a15.ID_ANO_EMISSAO_DOC and 
			a11.ID_DOCUMENTO_LANC = a15.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE					a16
	  on 	(a14.ID_ORGAO_SUPE = a16.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA			a17
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a17.ID_CATEGORIA_ECONOMICA_NADE and 
			a11.ID_ELEMENTO_DESPESA_NADE = a17.ID_ELEMENTO_DESPESA_NADE and 
			a11.ID_GRUPO_DESPESA_NADE = a17.ID_GRUPO_DESPESA_NADE and 
			a11.ID_MOAP_NADE = a17.ID_MOAP_NADE)
	join	DWTG_Colunar_VBL.WD_MES							a18
	  on 	(a15.ID_ANO_TRANSACAO_DOC = a18.ID_ANO and 
			a15.ID_MES_TRANSACAO_DOC = a18.ID_MES)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO				a19
	  on 	(a12.ID_ITEM_INFORMACAO = a19.ID_ITEM_INFORMACAO)
    join	DWTG_Colunar_VBL.WD_DOCUMENTO					a115
	  on 	(a11.ID_ANO_LANC = a115.ID_ANO_EMISSAO_DOC and 
			a11.ID_DOCUMENTO_LANC = a15.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_DOC_RO						a116
	  on 	(a115.ID_DOC_RO = a116.ID_DOC_RO)
	join	DWTG_Colunar_VBL.WD_DOC_NE						a117
	  on 	(a116.ID_DOC_NE = a117.ID_DOC_NE)
where 
--	(	--a15.ID_MES_TRANSACAO_DOC = 6
	(	a15.ID_ANO_TRANSACAO_DOC in (2018, 2019, 2020) --(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)
	and (a11.ID_CATEGORIA_ECONOMICA_NADE = 3 and a11.ID_GRUPO_DESPESA_NADE = 3 and a11.ID_MOAP_NADE = 90 and a11.ID_ELEMENTO_DESPESA_NADE = 30)
	and a12.ID_ITEM_INFORMACAO in (421)
	and a14.ID_ORGAO_SUPE in (22000)
	and a117.NO_SISTEMA_ORIGEM in ('SIASG')
	)
group by
	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a12.ID_ITEM_INFORMACAO,
	a15.ID_ANO_TRANSACAO_DOC,
	a15.ID_MES_TRANSACAO_DOC,
	a14.ID_ORGAO_SUPE
	
	
	
	
	
	
-----------------------------------------------------------------------------------------------------------	
	
select	a11.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE  ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
	max(a19.CO_NATUREZA_DESPESA)  CO_NATUREZA_DESPESA,
	max(a19.NO_NATUREZA_DESPESA)  NO_NATUREZA_DESPESA,
	a12.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
	max(a111.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
	max(a111.CO_ITEM_INFORMACAO)  CO_ITEM_INFORMACAO,
	a15.ID_ANO_TRANSACAO_DOC  ID_ANO,
	a15.ID_MES_TRANSACAO_DOC  ID_MES,
	max(a110.SG_MES_COMPLETO)  SG_MES_COMPLETO,
	a14.ID_ORGAO_SUPE  ID_ORGAO_SUPE,
	max(a18.CO_ORGAO_SUPE)  CO_ORGAO_SUPE,
	max(a18.NO_ORGAO_SUPE)  NO_ORGAO_SUPE,
	sum((a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO))  MOVIMLQUIDOMOEDAORIGEMITEMINF
from	DWTG_Colunar_VBL.WF_LANCAMENTO	a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON	a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
			a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO	a13
	  on 	(a11.ID_ANO_LANC = a13.ID_ANO and 
			a11.ID_UG_EMIT_DOC = a13.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a14
	  on 	(a13.ID_ANO = a14.ID_ANO and 
			a13.ID_ORGAO_UG = a14.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_DOCUMENTO	a15
	  on 	(a11.ID_ANO_LANC = a15.ID_ANO_EMISSAO_DOC and 
			a11.ID_DOCUMENTO_LANC = a15.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_DOC_RO	a16
	  on 	(a15.ID_DOC_RO = a16.ID_DOC_RO)
	join	DWTG_Colunar_VBL.WD_DOC_NE	a17
	  on 	(a16.ID_DOC_NE = a17.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE	a18
	  on 	(a14.ID_ORGAO_SUPE = a18.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA	a19
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a19.ID_CATEGORIA_ECONOMICA_NADE and 
			a11.ID_ELEMENTO_DESPESA_NADE = a19.ID_ELEMENTO_DESPESA_NADE and 
			a11.ID_GRUPO_DESPESA_NADE = a19.ID_GRUPO_DESPESA_NADE and 
			a11.ID_MOAP_NADE = a19.ID_MOAP_NADE)
	join	DWTG_Colunar_VBL.WD_MES	a110
	  on 	(a15.ID_ANO_TRANSACAO_DOC = a110.ID_ANO and 
			a15.ID_MES_TRANSACAO_DOC = a110.ID_MES)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO	a111
	  on 	(a12.ID_ITEM_INFORMACAO = a111.ID_ITEM_INFORMACAO)
where	(a15.ID_MES_TRANSACAO_DOC = 6
 and a15.ID_ANO_TRANSACAO_DOC in (2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020)
 and (a11.ID_CATEGORIA_ECONOMICA_NADE = 3 and a11.ID_GRUPO_DESPESA_NADE = 3 and a11.ID_MOAP_NADE = 90 and a11.ID_ELEMENTO_DESPESA_NADE = 30)
 and a12.ID_ITEM_INFORMACAO in (421)
 and a14.ID_ORGAO_SUPE in (22000)
 and a17.NO_SISTEMA_ORIGEM in ('SIASG'))
group by	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a12.ID_ITEM_INFORMACAO,
	a15.ID_ANO_TRANSACAO_DOC,
	a15.ID_MES_TRANSACAO_DOC,
	a14.ID_ORGAO_SUPE
	
------------------------------------------------------------------------------------------------
	
	
	
select	a11.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE  ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
	max(a17.CO_NATUREZA_DESPESA)  CO_NATUREZA_DESPESA,
	max(a17.NO_NATUREZA_DESPESA)  NO_NATUREZA_DESPESA,
	a12.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
	max(a19.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
	max(a19.CO_ITEM_INFORMACAO)  CO_ITEM_INFORMACAO,
	a13.ID_ANO_TRANSACAO_DOC  ID_ANO,
	a13.ID_MES_TRANSACAO_DOC  ID_MES,
	max(a18.SG_MES_COMPLETO)  SG_MES_COMPLETO,
	a15.ID_ORGAO_SUPE  ID_ORGAO_SUPE,
	max(a16.CO_ORGAO_SUPE)  CO_ORGAO_SUPE,
	max(a16.NO_ORGAO_SUPE)  NO_ORGAO_SUPE,
	sum((a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO))  MOVIMLQUIDOMOEDAORIGEMITEMINF
from	DWTG_Colunar_VBL.WF_LANCAMENTO	a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON	a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
	a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WD_DOCUMENTO	a13
	  on 	(a11.ID_ANO_LANC = a13.ID_ANO_EMISSAO_DOC and 
	a11.ID_DOCUMENTO_LANC = a13.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO	a14
	  on 	(a11.ID_ANO_LANC = a14.ID_ANO and 
	a11.ID_UG_EMIT_DOC = a14.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a15
	  on 	(a14.ID_ANO = a15.ID_ANO and 
	a14.ID_ORGAO_UG = a15.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE	a16
	  on 	(a15.ID_ORGAO_SUPE = a16.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA	a17
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a17.ID_CATEGORIA_ECONOMICA_NADE and 
	a11.ID_ELEMENTO_DESPESA_NADE = a17.ID_ELEMENTO_DESPESA_NADE and 
	a11.ID_GRUPO_DESPESA_NADE = a17.ID_GRUPO_DESPESA_NADE and 
	a11.ID_MOAP_NADE = a17.ID_MOAP_NADE)
	join	DWTG_Colunar_VBL.WD_MES	a18
	  on 	(a13.ID_ANO_TRANSACAO_DOC = a18.ID_ANO and 
	a13.ID_MES_TRANSACAO_DOC = a18.ID_MES)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO	a19
	  on 	(a12.ID_ITEM_INFORMACAO = a19.ID_ITEM_INFORMACAO)
where	(a13.ID_MES_TRANSACAO_DOC = 6
 and a13.ID_ANO_TRANSACAO_DOC in (2020, 2019, 2018, 2017)
 and (a11.ID_CATEGORIA_ECONOMICA_NADE = 3 and a11.ID_GRUPO_DESPESA_NADE = 3 and a11.ID_MOAP_NADE = 90 and a11.ID_ELEMENTO_DESPESA_NADE = 30)
 and a12.ID_ITEM_INFORMACAO in (421)
 and a15.ID_ORGAO_SUPE in (22000)
 and a13.CO_SISTEMA_ORIGEM in ('SIASG'))
group by	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a12.ID_ITEM_INFORMACAO,
	a13.ID_ANO_TRANSACAO_DOC,
	a13.ID_MES_TRANSACAO_DOC,
	a15.ID_ORGAO_SUPE
	
	
---------------------------------------------------------
	
select	a11.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE  ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
	max(a19.CO_NATUREZA_DESPESA)  CO_NATUREZA_DESPESA,
	max(a19.NO_NATUREZA_DESPESA)  NO_NATUREZA_DESPESA,
	a12.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
	max(a110.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
	max(a110.CO_ITEM_INFORMACAO)  CO_ITEM_INFORMACAO,
	a14.ID_ORGAO_SUPE  ID_ORGAO_SUPE,
	max(a18.CO_ORGAO_SUPE)  CO_ORGAO_SUPE,
	max(a18.NO_ORGAO_SUPE)  NO_ORGAO_SUPE,
	a11.ID_ANO_LANC  ID_ANO,
	sum((a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO))  MOVIMLQUIDOMOEDAORIGEMITEMINF
from	DWTG_Colunar_VBL.WF_LANCAMENTO	a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON	a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
	a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO	a13
	  on 	(a11.ID_ANO_LANC = a13.ID_ANO and 
	a11.ID_UG_EMIT_DOC = a13.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a14
	  on 	(a13.ID_ANO = a14.ID_ANO and 
	a13.ID_ORGAO_UG = a14.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_DOCUMENTO	a15
	  on 	(a11.ID_ANO_LANC = a15.ID_ANO_EMISSAO_DOC and 
	a11.ID_DOCUMENTO_LANC = a15.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_DOC_RO	a16
	  on 	(a15.ID_DOC_RO = a16.ID_DOC_RO)
	join	DWTG_Colunar_VBL.WD_DOC_NE	a17
	  on 	(a16.ID_DOC_NE = a17.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE	a18
	  on 	(a14.ID_ORGAO_SUPE = a18.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA	a19
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a19.ID_CATEGORIA_ECONOMICA_NADE and 
	a11.ID_ELEMENTO_DESPESA_NADE = a19.ID_ELEMENTO_DESPESA_NADE and 
	a11.ID_GRUPO_DESPESA_NADE = a19.ID_GRUPO_DESPESA_NADE and 
	a11.ID_MOAP_NADE = a19.ID_MOAP_NADE)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO	a110
	  on 	(a12.ID_ITEM_INFORMACAO = a110.ID_ITEM_INFORMACAO)
where	((a11.ID_CATEGORIA_ECONOMICA_NADE = 3 and a11.ID_GRUPO_DESPESA_NADE = 3 and a11.ID_MOAP_NADE = 90 and a11.ID_ELEMENTO_DESPESA_NADE = 30)
 and a12.ID_ITEM_INFORMACAO in (421)
 and a14.ID_ORGAO_SUPE in (22000)
 and a11.ID_ANO_LANC in (2020, 2019, 2018)
 and a11.ID_ORCA_FISCAL_ORGAO_EXEC_H in (0)
 and a17.NO_SISTEMA_ORIGEM in ('SIASG'))
group by	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a12.ID_ITEM_INFORMACAO,
	a14.ID_ORGAO_SUPE,
	a11.ID_ANO_LANC