select	
	max(a18.CO_MODALIDADE_LICITACAO_NE)  CO_MODALIDADE_LICITACAO_NE,
	max(a18.NO_MODALIDADE_LICITACAO_NE)  NO_MODALIDADE_LICITACAO_NE,
	coalesce(pa11.ID_DOCUMENTO, pa12.ID_DOCUMENTO)  ID_DOCUMENTO,
	max(a19.NO_TP_NE)  NO_TP_NE,
	a13.ID_ENTIDADE_FAVO_DOC  ID_ENTIDADE,
	max(a17.NO_ENTIDADE)  NO_ENTIDADE,
	LPAD(a13.ID_DIA_EMISSAO_DOC,2,0)||'/'||LPAD(a13.ID_MES_EMISSAO_DOC,2,0)||'/'||a13.ID_ANO_EMISSAO_DOC ID_DATA,
	max(a16.NO_DIA_COMPLETO)  NO_DIA_COMPLETO,
	coalesce(pa11.ID_DOCUMENTO0, pa12.ID_DOCUMENTO0)  ID_DOCUMENTO0,
	max(a15.VA_NE)  VA_NE,
	coalesce(pa11.ID_DOC_NE_REFE, pa12.ID_DOC_NE_REFE)  ID_DOC_NE_REFE,
	max(pa11.SALDORCONTACONTBIL)  SALDORCONTACONTBIL,
	max(pa12.SALDOINICIALRCONTACONTABIL)  SALDOINICIALRCONTACONTABIL
from	(select	a11.ID_DOCUMENTO_CCOR  ID_DOCUMENTO,
		a17.ID_DOC_NE  ID_DOCUMENTO0,
		a17.ID_DOC_NE_REFE  ID_DOC_NE_REFE,
		a15.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
		sum((a11.VA_MOVIMENTO_LIQUIDO * a13.PE_TAXA))  SALDORCONTACONTBIL
	from	DWTG_Colunar_VBL.WF_LANCAMENTO	a11
		join	DWTG_Colunar_VBL.WD_MOEDA	a12
		  on 	(a11.ID_MOEDA_UG_EXEC_H = a12.ID_MOEDA)
		join	DWTG_Colunar_VBL.WD_TAXA_CAMBIO_MENSAL	a13
		  on 	(a12.ID_MOEDA = a13.ID_MOEDA_ORIGEM)
		join	DWTG_Colunar_VBL.WA_MES_ACUM_SEM_ANO	a14
		  on 	(a11.ID_MES_LANC = a14.ID_MES_ACUM_ANO_SALDO)
		join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON	a15
		  on 	(a11.ID_ANO_LANC = a15.ID_ANO_ITEM_CONTA and 
		a11.ID_CONTA_CONTABIL_LANC = a15.ID_CONTA_CONTABIL)
		join	DWTG_Colunar_VBL.WD_DOCUMENTO	a16
		  on 	(a11.ID_ANO_LANC = a16.ID_ANO_EMISSAO_DOC and 
		a11.ID_DOCUMENTO_LANC = a16.ID_DOCUMENTO)
		join	DWTG_Colunar_VBL.WD_DOC_NE	a17
		  on 	(a16.ID_DOC_NE = a17.ID_DOC_NE)
		join	DWTG_Colunar_VBL.WD_DOC_NE	a18
		  on 	(a11.ID_DOCUMENTO_CCOR = a18.ID_DOC_NE)
	where	(a15.ID_ITEM_INFORMACAO in (421, 423)
	 and a18.ID_ANO_EMISSAO_DOC in (2020)
	 and a17.ID_MODALIDADE_LICITACAO_NE in (6, 12)
	 and a13.ID_ANO = a11.ID_ANO_LANC
	 and a13.ID_MES = a14.ID_MES)
	group by	a11.ID_DOCUMENTO_CCOR,
		a17.ID_DOC_NE,
		a17.ID_DOC_NE_REFE,
		a15.ID_ITEM_INFORMACAO
	)	pa11
	full outer join	(select	a11.ID_DOCUMENTO_CCOR  ID_DOCUMENTO,
		a16.ID_DOC_NE  ID_DOCUMENTO0,
		a16.ID_DOC_NE_REFE  ID_DOC_NE_REFE,
		a14.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
		sum((a11.VA_MOVIMENTO_LIQUIDO * a13.PE_TAXA))  SALDOINICIALRCONTACONTABIL
	from	DWTG_Colunar_VBL.WF_LANCAMENTO	a11
		join	DWTG_Colunar_VBL.WD_MOEDA	a12
		  on 	(a11.ID_MOEDA_UG_EXEC_H = a12.ID_MOEDA)
		join	DWTG_Colunar_VBL.WD_TAXA_CAMBIO_MENSAL	a13
		  on 	(a12.ID_MOEDA = a13.ID_MOEDA_ORIGEM)
		join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON	a14
		  on 	(a11.ID_ANO_LANC = a14.ID_ANO_ITEM_CONTA and 
		a11.ID_CONTA_CONTABIL_LANC = a14.ID_CONTA_CONTABIL)
		join	DWTG_Colunar_VBL.WD_DOCUMENTO	a15
		  on 	(a11.ID_ANO_LANC = a15.ID_ANO_EMISSAO_DOC and 
		a11.ID_DOCUMENTO_LANC = a15.ID_DOCUMENTO)
		join	DWTG_Colunar_VBL.WD_DOC_NE	a16
		  on 	(a15.ID_DOC_NE = a16.ID_DOC_NE)
		join	DWTG_Colunar_VBL.WD_DOC_NE	a17
		  on 	(a11.ID_DOCUMENTO_CCOR = a17.ID_DOC_NE)
	where	(a13.ID_ANO = a11.ID_ANO_LANC
	 and a13.ID_MES = 0
	 and a14.ID_ITEM_INFORMACAO in (421, 423)
	 and a17.ID_ANO_EMISSAO_DOC in (2020)
	 and a16.ID_MODALIDADE_LICITACAO_NE in (6, 12))
	group by	a11.ID_DOCUMENTO_CCOR,
		a16.ID_DOC_NE,
		a16.ID_DOC_NE_REFE,
		a14.ID_ITEM_INFORMACAO
	)	pa12
	  on 	(pa11.ID_DOCUMENTO = pa12.ID_DOCUMENTO and 
	pa11.ID_DOCUMENTO0 = pa12.ID_DOCUMENTO0 and 
	pa11.ID_DOC_NE_REFE = pa12.ID_DOC_NE_REFE and 
	pa11.ID_ITEM_INFORMACAO = pa12.ID_ITEM_INFORMACAO)
	join	DWTG_Colunar_VBL.WD_DOC_NE	a13
	  on 	(coalesce(pa11.ID_DOCUMENTO, pa12.ID_DOCUMENTO) = a13.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO	a14
	  on 	(coalesce(pa11.ID_ITEM_INFORMACAO, pa12.ID_ITEM_INFORMACAO) = a14.ID_ITEM_INFORMACAO)
	join	DWTG_Colunar_VBL.WF_DOC_NE	a15
	  on 	(coalesce(pa11.ID_DOCUMENTO0, pa12.ID_DOCUMENTO0) = a15.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_DIA	a16
	  on 	(a13.ID_ANO_EMISSAO_DOC = a16.ID_ANO and 
	a13.ID_DIA_EMISSAO_DOC = a16.ID_DIA and 
	a13.ID_MES_EMISSAO_DOC = a16.ID_MES)
	join	DWTG_Colunar_VBL.WD_ENTIDADE	a17
	  on 	(a13.ID_ENTIDADE_FAVO_DOC = a17.ID_ENTIDADE and 
	a13.ID_TP_ENTIDADE_FAVO_DOC = a17.ID_TP_ENTIDADE)
	join	DWTG_Colunar_VBL.WD_MODALIDADE_LICITACAO_NE	a18
	  on 	(a13.ID_MODALIDADE_LICITACAO_NE = a18.ID_MODALIDADE_LICITACAO_NE)
	join	DWTG_Colunar_VBL.WD_TP_NE	a19
	  on 	(a13.ID_TP_NE = a19.ID_TP_NE)
group by	coalesce(pa11.ID_ITEM_INFORMACAO, pa12.ID_ITEM_INFORMACAO),
	a13.ID_MODALIDADE_LICITACAO_NE,
	coalesce(pa11.ID_DOCUMENTO, pa12.ID_DOCUMENTO),
	a13.ID_TP_NE,
	a13.ID_TP_ENTIDADE_FAVO_DOC,
	a13.ID_ENTIDADE_FAVO_DOC,
	a13.ID_ANO_EMISSAO_DOC,
	a13.ID_MES_EMISSAO_DOC,
	a13.ID_DIA_EMISSAO_DOC,
	coalesce(pa11.ID_DOCUMENTO0, pa12.ID_DOCUMENTO0),
	coalesce(pa11.ID_DOC_NE_REFE, pa12.ID_DOC_NE_REFE);
	
/* 
select	
	a13.ID_TP_ENTIDADE_FAVO_DOC  ID_TP_ENTIDADE,
	a13.ID_ENTIDADE_FAVO_DOC  ID_ENTIDADE,
	max(a17.NO_ENTIDADE)  NO_ENTIDADE,
	a13.ID_ANO_EMISSAO_DOC  ID_ANO,
	a13.ID_MES_EMISSAO_DOC  ID_MES,
	a13.ID_DIA_EMISSAO_DOC  ID_DIA,
*/