select	a12.ID_ITEM_INFORMACAO  ID_ITEM_INFORMACAO,
	max(a127.NO_ITEM_INFORMACAO)  NO_ITEM_INFORMACAO,
	max(a127.CO_ITEM_INFORMACAO)  CO_ITEM_INFORMACAO,
	a11.ID_ANO_LANC  ID_ANO,
	a11.ID_MES_LANC  ID_MES,
	max(a120.NO_MES)  NO_MES,
	a18.ID_ORGAO_UG  ID_ORGAO,
	max(a117.CO_ORGAO)  CO_ORGAO,
	max(a117.NO_ORGAO)  NO_ORGAO,
	a11.ID_ACAO_PT  ID_ACAO_PT,
	max(a118.NO_ACAO_PT)  NO_ACAO_PT,
	a11.ID_FUNCAO_PT  ID_FUNCAO_PT,
	max(a119.NO_FUNCAO_PT)  ID_FUNCAO_PT0,
	a11.ID_SUBFUNCAO_PT  ID_SUBFUNCAO_PT,
	max(a124.NO_SUBFUNCAO_PT)  NO_SUBFUNCAO_PT,
	a11.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE  ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE,
	a11.ID_SUBITEM_NADE  ID_SUBITEM_NADE,
	max(a123.CO_NATUREZA_DESPESA_DETA)  CO_NATUREZA_DESPESA_DETA,
	max(a123.NO_NATUREZA_DESPESA_DETA)  NO_NATUREZA_DESPESA_DETA,
	a111.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
	max(a125.CO_ORGAO_MAXI)  CO_ORGAO_MAXI,
	max(a125.NO_ORGAO_MAXI)  NO_ORGAO_MAXI,
	a18.ID_UG  ID_UG_EXEC,
	max(a114.CO_UG)  CO_UG,
	max(a114.NO_UG)  NO_UG,
	a19.ID_ORGAO_UO  ID_ORGAO0,
	max(a116.CO_ORGAO)  CO_ORGAO0,
	max(a116.NO_ORGAO)  NO_ORGAO0,
	a113.ID_ORGAO_MAXI  ID_ORGAO_MAXI0,
	max(a126.CO_ORGAO_MAXI)  CO_ORGAO_MAXI0,
	max(a126.NO_ORGAO_MAXI)  NO_ORGAO_MAXI0,
	a115.ID_UF  ID_UF,
	max(a129.NO_UF)  NO_UF,
	a117.ID_TP_ADMIN_ORGAO  ID_TP_ADMIN_ORGAO,
	max(a130.NO_TP_ADMIN_ORGAO)  NO_TP_ADMIN_ORGAO,
	a17.ID_MODALIDADE_LICITACAO_NE  ID_MODALIDADE_LICITACAO_NE,
	max(a121.CO_MODALIDADE_LICITACAO_NE)  CO_MODALIDADE_LICITACAO_NE,
	max(a121.NO_MODALIDADE_LICITACAO_NE)  NO_MODALIDADE_LICITACAO_NE,
	a11.ID_CATEGORIA_ECONOMICA_NADE  ID_CATEGORIA_ECONOMICA_NADE0,
	a11.ID_GRUPO_DESPESA_NADE  ID_GRUPO_DESPESA_NADE0,
	a11.ID_MOAP_NADE  ID_MOAP_NADE0,
	a11.ID_ELEMENTO_DESPESA_NADE  ID_ELEMENTO_DESPESA_NADE0,
	max(a128.CO_NATUREZA_DESPESA)  CO_NATUREZA_DESPESA,
	max(a128.NO_NATUREZA_DESPESA)  NO_NATUREZA_DESPESA,
	a16.ID_TP_NE  ID_TP_NE,
	max(a122.NO_TP_NE)  NO_TP_NE,
	sum((a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO))  MOVIMLQUIDOMOEDAORIGEMITEMINF
from	DWTG_Colunar_VBL.WF_LANCAMENTO	a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON	a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
	a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WD_DOCUMENTO	a13
	  on 	(a11.ID_ANO_LANC = a13.ID_ANO_EMISSAO_DOC and 
	a11.ID_DOCUMENTO_LANC = a13.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_DOC_RO	a14
	  on 	(a13.ID_DOC_RO = a14.ID_DOC_RO)
	join	DWTG_Colunar_VBL.WD_DOC_NE	a15
	  on 	(a14.ID_DOC_NE = a15.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_DOC_NE	a16
	  on 	(a11.ID_DOCUMENTO_CCOR_ORCA = a16.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_AMPARO_LEGAL	a17
	  on 	(a16.ID_AMPARO_LEGAL = a17.ID_AMPARO_LEGAL)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO	a18
	  on 	(a11.ID_ANO_LANC = a18.ID_ANO and 
	a11.ID_UG_EXEC = a18.ID_UG)
	join	DWTG_Colunar_VBL.WD_UO_EXERCICIO	a19
	  on 	(a11.ID_ANO_LANC = a19.ID_ANO and 
	a11.ID_UO = a19.ID_UO)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a110
	  on 	(a19.ID_ANO = a110.ID_ANO and 
	a19.ID_ORGAO_UO = a110.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO	a111
	  on 	(a110.ID_ANO = a111.ID_ANO and 
	a110.ID_ORGAO_SUPE = a111.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a112
	  on 	(a18.ID_ANO = a112.ID_ANO and 
	a18.ID_ORGAO_UG = a112.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO	a113
	  on 	(a112.ID_ANO = a113.ID_ANO and 
	a112.ID_ORGAO_SUPE = a113.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_UG	a114
	  on 	(a18.ID_UG = a114.ID_UG)
	join	DWTG_Colunar_VBL.WD_MUNICIPIO	a115
	  on 	(a114.ID_MUNICIPIO_UG = a115.ID_MUNICIPIO)
	join	DWTG_Colunar_VBL.WD_ORGAO	a116
	  on 	(a19.ID_ORGAO_UO = a116.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO	a117
	  on 	(a18.ID_ORGAO_UG = a117.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ACAO_PT	a118
	  on 	(a11.ID_ACAO_PT = a118.ID_ACAO_PT)
	join	DWTG_Colunar_VBL.WD_FUNCAO_PT	a119
	  on 	(a11.ID_FUNCAO_PT = a119.ID_FUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_MES_BASE	a120
	  on 	(a11.ID_MES_LANC = a120.ID_MES)
	join	DWTG_Colunar_VBL.WD_MODALIDADE_LICITACAO_NE	a121
	  on 	(a17.ID_MODALIDADE_LICITACAO_NE = a121.ID_MODALIDADE_LICITACAO_NE)
	join	DWTG_Colunar_VBL.WD_TP_NE	a122
	  on 	(a16.ID_TP_NE = a122.ID_TP_NE)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA_DETA	a123
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a123.ID_CATEGORIA_ECONOMICA_NADE and 
	a11.ID_ELEMENTO_DESPESA_NADE = a123.ID_ELEMENTO_DESPESA_NADE and 
	a11.ID_GRUPO_DESPESA_NADE = a123.ID_GRUPO_DESPESA_NADE and 
	a11.ID_MOAP_NADE = a123.ID_MOAP_NADE and 
	a11.ID_SUBITEM_NADE = a123.ID_SUBITEM_NADE)
	join	DWTG_Colunar_VBL.WD_SUBFUNCAO_PT	a124
	  on 	(a11.ID_SUBFUNCAO_PT = a124.ID_SUBFUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI	a125
	  on 	(a111.ID_ORGAO_MAXI = a125.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI	a126
	  on 	(a113.ID_ORGAO_MAXI = a126.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO	a127
	  on 	(a12.ID_ITEM_INFORMACAO = a127.ID_ITEM_INFORMACAO)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA	a128
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a128.ID_CATEGORIA_ECONOMICA_NADE and 
	a11.ID_ELEMENTO_DESPESA_NADE = a128.ID_ELEMENTO_DESPESA_NADE and 
	a11.ID_GRUPO_DESPESA_NADE = a128.ID_GRUPO_DESPESA_NADE and 
	a11.ID_MOAP_NADE = a128.ID_MOAP_NADE)
	join	DWTG_Colunar_VBL.WD_UF	a129
	  on 	(a115.ID_UF = a129.ID_UF)
	join	DWTG_Colunar_VBL.WD_TP_ADMIN_ORGAO	a130
	  on 	(a117.ID_TP_ADMIN_ORGAO = a130.ID_TP_ADMIN_ORGAO)
where	(a114.ID_ESFERA_ADMIN_UG in (0)
 and a116.ID_PODER_ORGAO in (0)
 and a12.ID_ITEM_INFORMACAO in (421, 423)
 and a18.ID_UG in (120628)
 and a114.ID_MOEDA_UG in (790)
 and a15.ID_ANO_EMISSAO_DOC in (2021))
group by	a12.ID_ITEM_INFORMACAO,
	a11.ID_ANO_LANC,
	a11.ID_MES_LANC,
	a18.ID_ORGAO_UG,
	a11.ID_ACAO_PT,
	a11.ID_FUNCAO_PT,
	a11.ID_SUBFUNCAO_PT,
	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a11.ID_SUBITEM_NADE,
	a111.ID_ORGAO_MAXI,
	a18.ID_UG,
	a19.ID_ORGAO_UO,
	a113.ID_ORGAO_MAXI,
	a115.ID_UF,
	a117.ID_TP_ADMIN_ORGAO,
	a17.ID_MODALIDADE_LICITACAO_NE,
	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a16.ID_TP_NE