select	
--	a12.ID_ITEM_INFORMACAO  				ID_ITEM_INFORMACAO,
--	max(a118.NO_ITEM_INFORMACAO)  			NO_ITEM_INFORMACAO,
--	a11.ID_ANO_LANC  						ID_ANO,
--	a11.ID_MES_LANC  						ID_MES,
--	max(a119.NO_MES)  						NO_MES,
	a17.ID_ESFERA_ADMIN_UG  				ID_ESFERA_ADMIN_UG,
	a19.ID_PODER_ORGAO  					ID_PODER_ORGAO,
	a19.ID_TP_ADMIN_ORGAO  					ID_TP_ADMIN_ORGAO,
--	a17.ID_ORGAO_MAXI  						ID_ORGAO_MAXI_UO,
--	max(a121.NO_ORGAO_MAXI)  				NO_ORGAO_MAXI_UO,
--	a15.ID_ORGAO_UO  						ID_ORGAO_UO,
--	max(a120.NO_ORGAO)  					NO_ORGAO_UO,
	a16.ID_ORGAO_MAXI  						ID_ORGAO_MAXI,
	a14.ID_ORGAO_UG  						ID_ORGAO,
	a14.ID_UG  								ID_UG_EXEC,
	a18.ID_UF  								ID_UF,
	a11.ID_FUNCAO_PT  						ID_FUNCAO_PT,
	a11.ID_SUBFUNCAO_PT  					ID_SUBFUNCAO_PT,
	a11.ID_ACAO_PT  						ID_ACAO_PT,
--	a11.ID_CATEGORIA_ECONOMICA_NADE			ID_CATEGORIA_ECONOMICA_NADE,
--	a11.ID_GRUPO_DESPESA_NADE  				ID_GRUPO_DESPESA_NADE,
--	a11.ID_MOAP_NADE  						ID_MOAP_NADE,
--	a11.ID_ELEMENTO_DESPESA_NADE  			ID_ELEMENTO_DESPESA_NADE,
--	a11.ID_SUBITEM_NADE  					ID_SUBITEM_NADE,
	max(a114.CO_NATUREZA_DESPESA_DETA)  	CO_NATUREZA_DESPESA_DETA,
	a13.ID_MODALIDADE_LICITACAO_NE  		ID_MODALIDADE_LICITACAO_NE,
	a13.ID_TP_NE  							ID_TP_NE,
	max(a120.NO_ESFERA_ADMIN_UG)  			NO_ESFERA_ADMIN_UG,
	max(a122.NO_PODER_ORGAO)  				NO_PODER_ORGAO,
	max(a123.NO_TP_ADMIN_ORGAO)  			NO_TP_ADMIN_ORGAO,
	max(a117.NO_ORGAO_MAXI)  				NO_ORGAO_MAXI,
	max(a19.NO_ORGAO)  						NO_ORGAO,
	max(a17.NO_UG)  						NO_UG,
	max(a121.NO_UF)  						NO_UF,
	max(a112.NO_FUNCAO_PT)  				NO_FUNCAO_PT,
	max(a115.NO_SUBFUNCAO_PT)	  			NO_SUBFUNCAO_PT,
	max(a110.NO_ACAO_PT)  					NO_ACAO_PT,
	max(a114.NO_NATUREZA_DESPESA_DETA)  	NO_NATUREZA_DESPESA_DETA,
	max(a113.NO_MODALIDADE_LICITACAO_NE)  	NO_MODALIDADE_LICITACAO_NE,
	max(a116.NO_TP_NE)  					NO_TP_NE,
	a11.ID_ANO_LANC  						ID_ANO,
	a11.ID_MES_LANC  						ID_MES,
	a11.ID_DIA_LANC  						ID_DIA,
	max(a111.NO_DIA_COMPLETO)  				NO_DIA_COMPLETO,
	sum((a11.VA_MOVIMENTO_LIQUIDO * a12.IN_OPERACAO_EXPRESSAO))  DESPESAS_PAGAS
from	
			DWTG_Colunar_VBL.WF_LANCAMENTO					a11
	join	DWTG_Colunar_VBL.WD_ITEM_DECODIFICADO_CCON		a12
	  on 	(a11.ID_ANO_LANC = a12.ID_ANO_ITEM_CONTA and 
			a11.ID_CONTA_CONTABIL_LANC = a12.ID_CONTA_CONTABIL)
	join	DWTG_Colunar_VBL.WD_DOC_NE						a13
	  on 	(a11.ID_DOCUMENTO_CCOR = a13.ID_DOC_NE)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO				a14
	  on 	(a11.ID_ANO_LANC = a14.ID_ANO and 
			a11.ID_UG_EXEC = a14.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO				a15
	  on 	(a14.ID_ANO = a15.ID_ANO and 
			a14.ID_ORGAO_UG = a15.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO		a16
	  on 	(a15.ID_ANO = a16.ID_ANO and 
			a15.ID_ORGAO_SUPE = a16.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_UG							a17
	  on 	(a14.ID_UG = a17.ID_UG)
	join	DWTG_Colunar_VBL.WD_MUNICIPIO					a18
	  on 	(a17.ID_MUNICIPIO_UG = a18.ID_MUNICIPIO)
	join	DWTG_Colunar_VBL.WD_ORGAO						a19
	  on 	(a14.ID_ORGAO_UG = a19.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ACAO_PT						a110
	  on 	(a11.ID_ACAO_PT = a110.ID_ACAO_PT)
	join	DWTG_Colunar_VBL.WD_DIA							a111
	  on 	(a11.ID_ANO_LANC = a111.ID_ANO and 
			a11.ID_DIA_LANC = a111.ID_DIA and 
			a11.ID_MES_LANC = a111.ID_MES)
	join	DWTG_Colunar_VBL.WD_FUNCAO_PT					a112
	  on 	(a11.ID_FUNCAO_PT = a112.ID_FUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_MODALIDADE_LICITACAO_NE		a113
	  on 	(a13.ID_MODALIDADE_LICITACAO_NE = a113.ID_MODALIDADE_LICITACAO_NE)
	join	DWTG_Colunar_VBL.WD_NATUREZA_DESPESA_DETA		a114
	  on 	(a11.ID_CATEGORIA_ECONOMICA_NADE = a114.ID_CATEGORIA_ECONOMICA_NADE and 
			a11.ID_ELEMENTO_DESPESA_NADE = a114.ID_ELEMENTO_DESPESA_NADE and 
			a11.ID_GRUPO_DESPESA_NADE = a114.ID_GRUPO_DESPESA_NADE and 
			a11.ID_MOAP_NADE = a114.ID_MOAP_NADE and 
			a11.ID_SUBITEM_NADE = a114.ID_SUBITEM_NADE)
	join	DWTG_Colunar_VBL.WD_SUBFUNCAO_PT				a115
	  on 	(a11.ID_SUBFUNCAO_PT = a115.ID_SUBFUNCAO_PT)
	join	DWTG_Colunar_VBL.WD_TP_NE						a116
	  on 	(a13.ID_TP_NE = a116.ID_TP_NE)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI					a117
	  on 	(a16.ID_ORGAO_MAXI = a117.ID_ORGAO_MAXI)
	join	DWTG_Colunar_VBL.WD_ITEM_INFORMACAO				a118
	  on 	(a12.ID_ITEM_INFORMACAO = a118.ID_ITEM_INFORMACAO)
--	join	DWTG_Colunar_VBL.WD_MES_BASE					a119
--	  on 	(a11.ID_MES_LANC = a119.ID_MES)
	join	DWTG_Colunar_VBL.WD_ESFERA_ADMIN_UG				a120
	  on 	(a17.ID_ESFERA_ADMIN_UG = a120.ID_ESFERA_ADMIN_UG)
	join	DWTG_Colunar_VBL.WD_UF							a121
	  on 	(a18.ID_UF = a121.ID_UF)
	join	DWTG_Colunar_VBL.WD_PODER_ORGAO					a122
	  on 	(a19.ID_PODER_ORGAO = a122.ID_PODER_ORGAO)
	join	DWTG_Colunar_VBL.WD_TP_ADMIN_ORGAO				a123
	  on 	(a19.ID_TP_ADMIN_ORGAO = a123.ID_TP_ADMIN_ORGAO)
where
--		(a11.ID_CATEGORIA_ECONOMICA_NADE = 	3
--	and (a11.ID_GRUPO_DESPESA_NADE = 		3
--	and (a11.ID_MOAP_NADE = 				90
--	and a11.ID_ELEMENTO_DESPESA_NADE in 	(4, 14, 15, 30, 31, 32, 33, 34, 35, 36, 37, 39, 40)))			-- (4, 14, 15, 30, 31, 32, 33, 34, 35, 36, 37, 39, 40)
--	--------------------------------------------------------------------
		a11.ID_CATEGORIA_ECONOMICA_NADE = 	3
	and (a11.ID_GRUPO_DESPESA_NADE = 		3
	and (a11.ID_MOAP_NADE = 				90
	and ((a11.ID_ELEMENTO_DESPESA_NADE = 	37 and a11.ID_SUBITEM_NADE in (1, 2, 3))
	or ((a11.ID_ELEMENTO_DESPESA_NADE = 	30 and a11.ID_SUBITEM_NADE = 9)
	or  (a11.ID_ELEMENTO_DESPESA_NADE = 	39 and a11.ID_SUBITEM_NADE = 50)))))
--  --------------------------------------------------------------------
--	and a17.ID_ESFERA_ADMIN_UG in 	(0)
--	and a19.ID_PODER_ORGAO in 		(0)
--	and a19.ID_TP_ADMIN_ORGAO in 	(1, 3, 4)
	and	a12.ID_ITEM_INFORMACAO in 	(423)
	and a17.ID_MOEDA_UG in 			(790)
	and a11.ID_ANO_LANC in 			(2015, 2014, 2013, 2012) 		-- 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012
--	and a11.ID_MES_LANC in 			(1, 2)
	and a14.ID_ORGAO_UG in 			(36000, 36201, 25000, 52121, 52111)
	and a11.VA_MOVIMENTO_LIQUIDO <> 0
group by	
--	a12.ID_ITEM_INFORMACAO,
	a11.ID_ANO_LANC,
	a11.ID_MES_LANC,
	a14.ID_ORGAO_UG,
	a11.ID_ACAO_PT,
	a11.ID_FUNCAO_PT,
	a11.ID_SUBFUNCAO_PT,
	a11.ID_CATEGORIA_ECONOMICA_NADE,
	a11.ID_GRUPO_DESPESA_NADE,
	a11.ID_MOAP_NADE,
	a11.ID_ELEMENTO_DESPESA_NADE,
	a11.ID_SUBITEM_NADE,
	a14.ID_UG,
	a16.ID_ORGAO_MAXI,
	a18.ID_UF,
	a19.ID_PODER_ORGAO,
	a19.ID_TP_ADMIN_ORGAO,
	a17.ID_ESFERA_ADMIN_UG,
	a13.ID_TP_NE,
	a13.ID_MODALIDADE_LICITACAO_NE,
	a11.ID_ANO_LANC,
	a11.ID_MES_LANC,
	a11.ID_DIA_LANC