SELECT 
	ID_ESPECIE_NE,ID_MODALIDADE_LICITACAO_NE,ID_UF_BENE_NE,ID_UG,ID_ENTIDADE_FAVO_DOC,ID_MES_EMISSAO_DOC,ID_ANO_EMISSAO_DOC,
	ID_MOAP_NADE,ID_ELEMENTO_DESPESA_NADE,ID_SUBITEM_NADE,QT_ITEM,VA_ITEM
	--DS_ITEM
FROM WD_DOC_NE JOIN WD_DOC_NE_ITEM ON WD_DOC_NE.ID_DOC_NE = WD_DOC_NE_ITEM.ID_DOC_NE
WHERE ID_ANO_EMISSAO_DOC > 2015