select
--	a113.ID_ORGAO_MAXI  ID_ORGAO_MAXI,
--	max(a119.CO_ORGAO_MAXI)  CO_ORGAO_MAXI,
	max(a119.NO_ORGAO_MAXI)  EmitenteOrgaoMaximo,
--	a18.ID_UG  ID_UG,
--	max(a112.CO_UG)  CO_UG,
	max(a112.NO_UG)  EmitenteUG,
	a13.ID_DOC_HABIL  DocumentoHabil,
	a16.VA_DOC  DHValor,
--	a11.ID_DIA  ID_DIA_ATESTE_DOC_HABIL,
--	a11.ID_MES  ID_MES_ATESTE_DOC_HABIL,
--	a11.ID_ANO  ID_ANO_ATESTE_DOC_HABIL,
--	max(a11.NO_DIA_COMPLETO)  NO_DIA_COMPLETO,
	max(lpad(a11.ID_ANO,4,2)||'-'||lpad(a11.ID_MES,2,0)||'-'||lpad(a11.ID_DIA,2,0)) DHDataEmissaoDocOrigem,
--	a16.ID_DIA_ATESTE_DOC_HABIL  ID_DIA_ATESTE_DOC_HABIL0,
--	a16.ID_MES_ATESTE_DOC_HABIL  ID_MES_ATESTE_DOC_HABIL0,
--	a16.ID_ANO_ATESTE_DOC_HABIL  ID_ANO_ATESTE_DOC_HABIL0,
--	max(a19.NO_DIA_COMPLETO)  NO_DIA_COMPLETO0,
	max(lpad(a16.ID_ANO_ATESTE_DOC_HABIL,4,2)||'-'||lpad(a16.ID_MES_ATESTE_DOC_HABIL,2,0)||'-'||lpad(a16.ID_DIA_ATESTE_DOC_HABIL,2,0)) DHDataAteste,
	a15.ID_DOCUMENTO  ID_DOCUMENTO,
--	a15.ID_ANO_EMISSAO_DOC  ID_ANO_EMISSAO_DOC,
--	a17.ID_ANO_EMISSAO_DOC  ID_ANO,
--	a17.ID_MES_EMISSAO_DOC  ID_MES,
--	a17.ID_DIA_EMISSAO_DOC  ID_DIA,
--	max(a111.NO_DIA_COMPLETO)  NO_DIA_COMPLETO1,
	max(lpad(a17.ID_ANO_EMISSAO_DOC,4,2)||'-'||lpad(a17.ID_MES_EMISSAO_DOC,2,0)||'-'||lpad(a17.ID_DIA_EMISSAO_DOC,2,0)) DataUltimoPagamento,
--	a17.ID_DOCUMENTO  ID_DOCUMENTO0,
--	a17.ID_ANO_EMISSAO_DOC  ID_ANO_EMISSAO_DOC0,
	sum(a110.VA_DOC)  ValorPagoAcumulado
from	DWTG_Colunar_VBL.WD_DIA	a11
	join	DWTG_Colunar_VBL.WD_DOC_ORIGEM_DOC_HABIL	a13
	  on 	(a11.ID_ANO = a13.ID_ANO_EMISSAO and 
			a11.ID_DIA = a13.ID_DIA_EMISSAO and 
			a11.ID_MES = a13.ID_MES_EMISSAO)
	join	DWTG_Colunar_VBL.WD_COMPROMISSO	a14
	  on 	(a13.ID_DOC_HABIL = a14.ID_DOC_HABIL)
	join	DWTG_Colunar_VBL.WD_COMPROMISSO_DOCUMENTO	a15
	  on 	(a14.ID_COMPROMISSO = a15.ID_COMPROMISSO)
	join	DWTG_Colunar_VBL.WD_DOC_HABIL	a16
	  on 	(a13.ID_DOC_HABIL = a16.ID_DOC_HABIL)
	join	DWTG_Colunar_VBL.WD_DOCUMENTO	a17
	  on 	(a15.ID_ANO_EMISSAO_DOC = a17.ID_ANO_EMISSAO_DOC and 
			a15.ID_DOCUMENTO = a17.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_UG_EXERCICIO	a18
	  on 	(a17.ID_ANO_EMISSAO_DOC = a18.ID_ANO and 
			a17.ID_UG = a18.ID_UG)
	join	DWTG_Colunar_VBL.WD_DIA	a19
	  on 	(a16.ID_ANO_ATESTE_DOC_HABIL = a19.ID_ANO and 
			a16.ID_DIA_ATESTE_DOC_HABIL = a19.ID_DIA and 
			a16.ID_MES_ATESTE_DOC_HABIL = a19.ID_MES)
	join	DWTG_Colunar_VBL.WF_DOCUMENTO	a110
	  on 	(a15.ID_ANO_EMISSAO_DOC = a110.ID_ANO_EMISSAO_DOC and 
			a15.ID_DOCUMENTO = a110.ID_DOCUMENTO and 
			a17.ID_ANO_EMISSAO_DOC = a110.ID_ANO_EMISSAO_DOC and 
			a17.ID_DOCUMENTO = a110.ID_DOCUMENTO)
	join	DWTG_Colunar_VBL.WD_DIA	a111
	  on 	(a17.ID_ANO_EMISSAO_DOC = a111.ID_ANO and 
			a17.ID_DIA_EMISSAO_DOC = a111.ID_DIA and 
			a17.ID_MES_EMISSAO_DOC = a111.ID_MES)
	join	DWTG_Colunar_VBL.WD_UG	a112
	  on 	(a18.ID_UG = a112.ID_UG)
	join	DWTG_Colunar_VBL.WD_ORGAO_EXERCICIO	a212
	  on 	(a18.ID_ANO = a212.ID_ANO and 
			a18.ID_ORGAO_UG = a212.ID_ORGAO)
	join	DWTG_Colunar_VBL.WD_ORGAO_SUPE_EXERCICIO	a113
	  on 	(a212.ID_ANO = a113.ID_ANO and 
			a212.ID_ORGAO_SUPE = a113.ID_ORGAO_SUPE)
	join	DWTG_Colunar_VBL.WD_ORGAO_MAXI	a119
	  on 	(a113.ID_ORGAO_MAXI = a119.ID_ORGAO_MAXI) 
where	(a16.ID_ANO_EMISSAO in (2022)
 and a16.ID_TP_DOC_HABIL in ('NP')
 and a17.ID_TP_DOCUMENTO in ('OB')
 and a18.ID_UG in (130024)
 )
group by	
	a18.ID_UG,
	a13.ID_DOC_HABIL,
	a11.ID_DIA,
	a11.ID_MES,
	a11.ID_ANO,
	a16.VA_DOC,
	a16.ID_DIA_ATESTE_DOC_HABIL,
	a16.ID_MES_ATESTE_DOC_HABIL,
	a16.ID_ANO_ATESTE_DOC_HABIL,
	a15.ID_DOCUMENTO
--	a15.ID_ANO_EMISSAO_DOC
--	a17.ID_ANO_EMISSAO_DOC,
--	a17.ID_MES_EMISSAO_DOC,
--	a17.ID_DIA_EMISSAO_DOC,
--	a17.ID_DOCUMENTO,
--	a17.ID_ANO_EMISSAO_DOC